#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 147
#define LARGE_STATE_COUNT 47
#define SYMBOL_COUNT 31
#define ALIAS_COUNT 0
#define TOKEN_COUNT 14
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 4
#define MAX_ALIAS_SEQUENCE_LENGTH 6
#define PRODUCTION_ID_COUNT 7

enum ts_symbol_identifiers {
  anon_sym_STAR = 1,
  anon_sym__ = 2,
  anon_sym_STAR_STAR = 3,
  anon_sym___ = 4,
  anon_sym_BQUOTE = 5,
  aux_sym_code_span_token1 = 6,
  anon_sym_LBRACK = 7,
  anon_sym_RBRACK = 8,
  anon_sym_LPAREN = 9,
  anon_sym_RPAREN = 10,
  sym_link_destination = 11,
  aux_sym_text_token1 = 12,
  aux_sym_text_token2 = 13,
  sym_inline = 14,
  sym__inline_element = 15,
  sym_emphasis = 16,
  sym_strong_emphasis = 17,
  sym__inline_no_star = 18,
  sym__inline_no_underscore = 19,
  sym_code_span = 20,
  sym_link = 21,
  sym_link_text = 22,
  sym__link_text_element = 23,
  sym_link_label = 24,
  sym_text = 25,
  aux_sym_inline_repeat1 = 26,
  aux_sym_emphasis_repeat1 = 27,
  aux_sym_emphasis_repeat2 = 28,
  aux_sym_link_text_repeat1 = 29,
  aux_sym_text_repeat1 = 30,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_STAR] = "*",
  [anon_sym__] = "_",
  [anon_sym_STAR_STAR] = "**",
  [anon_sym___] = "__",
  [anon_sym_BQUOTE] = "`",
  [aux_sym_code_span_token1] = "code_span_content",
  [anon_sym_LBRACK] = "[",
  [anon_sym_RBRACK] = "]",
  [anon_sym_LPAREN] = "(",
  [anon_sym_RPAREN] = ")",
  [sym_link_destination] = "link_destination",
  [aux_sym_text_token1] = "text_token1",
  [aux_sym_text_token2] = "text_token2",
  [sym_inline] = "inline",
  [sym__inline_element] = "_inline_element",
  [sym_emphasis] = "emphasis",
  [sym_strong_emphasis] = "strong_emphasis",
  [sym__inline_no_star] = "_inline_no_star",
  [sym__inline_no_underscore] = "_inline_no_underscore",
  [sym_code_span] = "code_span",
  [sym_link] = "link",
  [sym_link_text] = "link_text",
  [sym__link_text_element] = "_link_text_element",
  [sym_link_label] = "link_label",
  [sym_text] = "text",
  [aux_sym_inline_repeat1] = "inline_repeat1",
  [aux_sym_emphasis_repeat1] = "emphasis_repeat1",
  [aux_sym_emphasis_repeat2] = "emphasis_repeat2",
  [aux_sym_link_text_repeat1] = "link_text_repeat1",
  [aux_sym_text_repeat1] = "text_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_STAR] = anon_sym_STAR,
  [anon_sym__] = anon_sym__,
  [anon_sym_STAR_STAR] = anon_sym_STAR_STAR,
  [anon_sym___] = anon_sym___,
  [anon_sym_BQUOTE] = anon_sym_BQUOTE,
  [aux_sym_code_span_token1] = aux_sym_code_span_token1,
  [anon_sym_LBRACK] = anon_sym_LBRACK,
  [anon_sym_RBRACK] = anon_sym_RBRACK,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [sym_link_destination] = sym_link_destination,
  [aux_sym_text_token1] = aux_sym_text_token1,
  [aux_sym_text_token2] = aux_sym_text_token2,
  [sym_inline] = sym_inline,
  [sym__inline_element] = sym__inline_element,
  [sym_emphasis] = sym_emphasis,
  [sym_strong_emphasis] = sym_strong_emphasis,
  [sym__inline_no_star] = sym__inline_no_star,
  [sym__inline_no_underscore] = sym__inline_no_underscore,
  [sym_code_span] = sym_code_span,
  [sym_link] = sym_link,
  [sym_link_text] = sym_link_text,
  [sym__link_text_element] = sym__link_text_element,
  [sym_link_label] = sym_link_label,
  [sym_text] = sym_text,
  [aux_sym_inline_repeat1] = aux_sym_inline_repeat1,
  [aux_sym_emphasis_repeat1] = aux_sym_emphasis_repeat1,
  [aux_sym_emphasis_repeat2] = aux_sym_emphasis_repeat2,
  [aux_sym_link_text_repeat1] = aux_sym_link_text_repeat1,
  [aux_sym_text_repeat1] = aux_sym_text_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_STAR] = {
    .visible = true,
    .named = false,
  },
  [anon_sym__] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_STAR_STAR] = {
    .visible = true,
    .named = false,
  },
  [anon_sym___] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_BQUOTE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_code_span_token1] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [sym_link_destination] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_text_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_text_token2] = {
    .visible = false,
    .named = false,
  },
  [sym_inline] = {
    .visible = true,
    .named = true,
  },
  [sym__inline_element] = {
    .visible = false,
    .named = true,
  },
  [sym_emphasis] = {
    .visible = true,
    .named = true,
  },
  [sym_strong_emphasis] = {
    .visible = true,
    .named = true,
  },
  [sym__inline_no_star] = {
    .visible = false,
    .named = true,
  },
  [sym__inline_no_underscore] = {
    .visible = false,
    .named = true,
  },
  [sym_code_span] = {
    .visible = true,
    .named = true,
  },
  [sym_link] = {
    .visible = true,
    .named = true,
  },
  [sym_link_text] = {
    .visible = true,
    .named = true,
  },
  [sym__link_text_element] = {
    .visible = false,
    .named = true,
  },
  [sym_link_label] = {
    .visible = true,
    .named = true,
  },
  [sym_text] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_inline_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_emphasis_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_emphasis_repeat2] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_link_text_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_text_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_content = 1,
  field_destination = 2,
  field_reference = 3,
  field_text = 4,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_content] = "content",
  [field_destination] = "destination",
  [field_reference] = "reference",
  [field_text] = "text",
};

static const TSFieldMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 1},
  [2] = {.index = 1, .length = 1},
  [3] = {.index = 2, .length = 1},
  [4] = {.index = 3, .length = 1},
  [5] = {.index = 4, .length = 2},
  [6] = {.index = 6, .length = 2},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_content, 1},
  [1] =
    {field_reference, 3},
  [2] =
    {field_destination, 3},
  [3] =
    {field_text, 1},
  [4] =
    {field_reference, 4},
    {field_text, 1},
  [6] =
    {field_destination, 4},
    {field_text, 1},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 4,
  [7] = 5,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 3,
  [14] = 4,
  [15] = 5,
  [16] = 4,
  [17] = 5,
  [18] = 4,
  [19] = 5,
  [20] = 20,
  [21] = 20,
  [22] = 22,
  [23] = 11,
  [24] = 12,
  [25] = 20,
  [26] = 22,
  [27] = 11,
  [28] = 12,
  [29] = 20,
  [30] = 22,
  [31] = 11,
  [32] = 12,
  [33] = 20,
  [34] = 22,
  [35] = 22,
  [36] = 8,
  [37] = 10,
  [38] = 8,
  [39] = 10,
  [40] = 10,
  [41] = 8,
  [42] = 10,
  [43] = 9,
  [44] = 9,
  [45] = 9,
  [46] = 8,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 51,
  [54] = 54,
  [55] = 54,
  [56] = 56,
  [57] = 56,
  [58] = 58,
  [59] = 58,
  [60] = 60,
  [61] = 61,
  [62] = 61,
  [63] = 60,
  [64] = 64,
  [65] = 65,
  [66] = 65,
  [67] = 67,
  [68] = 67,
  [69] = 69,
  [70] = 70,
  [71] = 71,
  [72] = 72,
  [73] = 73,
  [74] = 74,
  [75] = 64,
  [76] = 70,
  [77] = 61,
  [78] = 71,
  [79] = 72,
  [80] = 73,
  [81] = 60,
  [82] = 74,
  [83] = 61,
  [84] = 60,
  [85] = 69,
  [86] = 71,
  [87] = 73,
  [88] = 72,
  [89] = 65,
  [90] = 67,
  [91] = 74,
  [92] = 69,
  [93] = 65,
  [94] = 70,
  [95] = 73,
  [96] = 72,
  [97] = 67,
  [98] = 74,
  [99] = 69,
  [100] = 70,
  [101] = 71,
  [102] = 102,
  [103] = 103,
  [104] = 104,
  [105] = 105,
  [106] = 104,
  [107] = 103,
  [108] = 102,
  [109] = 103,
  [110] = 105,
  [111] = 111,
  [112] = 103,
  [113] = 104,
  [114] = 111,
  [115] = 102,
  [116] = 111,
  [117] = 102,
  [118] = 105,
  [119] = 111,
  [120] = 104,
  [121] = 105,
  [122] = 122,
  [123] = 123,
  [124] = 124,
  [125] = 125,
  [126] = 126,
  [127] = 127,
  [128] = 125,
  [129] = 127,
  [130] = 122,
  [131] = 126,
  [132] = 123,
  [133] = 126,
  [134] = 123,
  [135] = 135,
  [136] = 122,
  [137] = 126,
  [138] = 127,
  [139] = 122,
  [140] = 127,
  [141] = 123,
  [142] = 135,
  [143] = 125,
  [144] = 135,
  [145] = 125,
  [146] = 135,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(7);
      if (lookahead == '(') ADVANCE(17);
      if (lookahead == ')') ADVANCE(18);
      if (lookahead == '*') ADVANCE(8);
      if (lookahead == '[') ADVANCE(15);
      if (lookahead == ']') ADVANCE(16);
      if (lookahead == '_') ADVANCE(9);
      if (lookahead == '`') ADVANCE(12);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      END_STATE();
    case 1:
      if (lookahead == ')') ADVANCE(18);
      if (lookahead == '\n' ||
          lookahead == '\r') SKIP(1);
      if (('\t' <= lookahead && lookahead <= '\f') ||
          lookahead == ' ') ADVANCE(19);
      if (lookahead != 0) ADVANCE(20);
      END_STATE();
    case 2:
      if (lookahead == '*') ADVANCE(8);
      if (lookahead == '[') ADVANCE(15);
      if (lookahead == '_') ADVANCE(24);
      if (lookahead == '`') ADVANCE(12);
      if (lookahead == '\n' ||
          lookahead == '\r') SKIP(2);
      if (('\t' <= lookahead && lookahead <= '\f') ||
          lookahead == ' ') ADVANCE(21);
      if (lookahead != 0 &&
          lookahead != ']') ADVANCE(22);
      END_STATE();
    case 3:
      if (lookahead == '*') ADVANCE(23);
      if (lookahead == '[') ADVANCE(15);
      if (lookahead == '_') ADVANCE(9);
      if (lookahead == '`') ADVANCE(12);
      if (lookahead == '\n' ||
          lookahead == '\r') SKIP(3);
      if (('\t' <= lookahead && lookahead <= '\f') ||
          lookahead == ' ') ADVANCE(21);
      if (lookahead != 0 &&
          lookahead != ']') ADVANCE(22);
      END_STATE();
    case 4:
      if (lookahead == '*') ADVANCE(23);
      if (lookahead == '[') ADVANCE(15);
      if (lookahead == '_') ADVANCE(24);
      if (lookahead == '`') ADVANCE(12);
      if (lookahead == '\n' ||
          lookahead == '\r') SKIP(4);
      if (('\t' <= lookahead && lookahead <= '\f') ||
          lookahead == ' ') ADVANCE(21);
      if (lookahead != 0 &&
          lookahead != ']') ADVANCE(22);
      END_STATE();
    case 5:
      if (lookahead == '`') ADVANCE(12);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(13);
      if (lookahead != 0) ADVANCE(14);
      END_STATE();
    case 6:
      if (eof) ADVANCE(7);
      if (lookahead == '*') ADVANCE(8);
      if (lookahead == '[') ADVANCE(15);
      if (lookahead == ']') ADVANCE(16);
      if (lookahead == '_') ADVANCE(9);
      if (lookahead == '`') ADVANCE(12);
      if (lookahead == '\n' ||
          lookahead == '\r') SKIP(6);
      if (('\t' <= lookahead && lookahead <= '\f') ||
          lookahead == ' ') ADVANCE(21);
      if (lookahead != 0) ADVANCE(22);
      END_STATE();
    case 7:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 8:
      ACCEPT_TOKEN(anon_sym_STAR);
      if (lookahead == '*') ADVANCE(10);
      END_STATE();
    case 9:
      ACCEPT_TOKEN(anon_sym__);
      if (lookahead == '_') ADVANCE(11);
      END_STATE();
    case 10:
      ACCEPT_TOKEN(anon_sym_STAR_STAR);
      END_STATE();
    case 11:
      ACCEPT_TOKEN(anon_sym___);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(anon_sym_BQUOTE);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(aux_sym_code_span_token1);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(13);
      if (lookahead != 0 &&
          lookahead != '`') ADVANCE(14);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(aux_sym_code_span_token1);
      if (lookahead != 0 &&
          lookahead != '`') ADVANCE(14);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(sym_link_destination);
      if (lookahead == '\t' ||
          lookahead == 0x0b ||
          lookahead == '\f' ||
          lookahead == ' ') ADVANCE(19);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ')') ADVANCE(20);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(sym_link_destination);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != ')') ADVANCE(20);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(aux_sym_text_token1);
      if (lookahead == '\t' ||
          lookahead == 0x0b ||
          lookahead == '\f' ||
          lookahead == ' ') ADVANCE(21);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != '*' &&
          lookahead != '[' &&
          lookahead != ']' &&
          lookahead != '_' &&
          lookahead != '`') ADVANCE(22);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(aux_sym_text_token1);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '*' &&
          lookahead != '[' &&
          lookahead != ']' &&
          lookahead != '_' &&
          lookahead != '`') ADVANCE(22);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(aux_sym_text_token2);
      if (lookahead == '*') ADVANCE(10);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(aux_sym_text_token2);
      if (lookahead == '_') ADVANCE(11);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 6},
  [2] = {.lex_state = 6},
  [3] = {.lex_state = 6},
  [4] = {.lex_state = 6},
  [5] = {.lex_state = 6},
  [6] = {.lex_state = 6},
  [7] = {.lex_state = 6},
  [8] = {.lex_state = 6},
  [9] = {.lex_state = 6},
  [10] = {.lex_state = 6},
  [11] = {.lex_state = 6},
  [12] = {.lex_state = 6},
  [13] = {.lex_state = 6},
  [14] = {.lex_state = 6},
  [15] = {.lex_state = 6},
  [16] = {.lex_state = 6},
  [17] = {.lex_state = 6},
  [18] = {.lex_state = 6},
  [19] = {.lex_state = 6},
  [20] = {.lex_state = 6},
  [21] = {.lex_state = 6},
  [22] = {.lex_state = 6},
  [23] = {.lex_state = 6},
  [24] = {.lex_state = 6},
  [25] = {.lex_state = 6},
  [26] = {.lex_state = 6},
  [27] = {.lex_state = 6},
  [28] = {.lex_state = 6},
  [29] = {.lex_state = 6},
  [30] = {.lex_state = 6},
  [31] = {.lex_state = 6},
  [32] = {.lex_state = 6},
  [33] = {.lex_state = 6},
  [34] = {.lex_state = 6},
  [35] = {.lex_state = 6},
  [36] = {.lex_state = 6},
  [37] = {.lex_state = 6},
  [38] = {.lex_state = 6},
  [39] = {.lex_state = 6},
  [40] = {.lex_state = 6},
  [41] = {.lex_state = 6},
  [42] = {.lex_state = 6},
  [43] = {.lex_state = 6},
  [44] = {.lex_state = 6},
  [45] = {.lex_state = 6},
  [46] = {.lex_state = 6},
  [47] = {.lex_state = 6},
  [48] = {.lex_state = 6},
  [49] = {.lex_state = 6},
  [50] = {.lex_state = 2},
  [51] = {.lex_state = 2},
  [52] = {.lex_state = 3},
  [53] = {.lex_state = 2},
  [54] = {.lex_state = 3},
  [55] = {.lex_state = 3},
  [56] = {.lex_state = 4},
  [57] = {.lex_state = 4},
  [58] = {.lex_state = 4},
  [59] = {.lex_state = 4},
  [60] = {.lex_state = 6},
  [61] = {.lex_state = 6},
  [62] = {.lex_state = 6},
  [63] = {.lex_state = 6},
  [64] = {.lex_state = 6},
  [65] = {.lex_state = 6},
  [66] = {.lex_state = 6},
  [67] = {.lex_state = 6},
  [68] = {.lex_state = 6},
  [69] = {.lex_state = 6},
  [70] = {.lex_state = 6},
  [71] = {.lex_state = 6},
  [72] = {.lex_state = 6},
  [73] = {.lex_state = 6},
  [74] = {.lex_state = 6},
  [75] = {.lex_state = 6},
  [76] = {.lex_state = 6},
  [77] = {.lex_state = 3},
  [78] = {.lex_state = 6},
  [79] = {.lex_state = 6},
  [80] = {.lex_state = 6},
  [81] = {.lex_state = 3},
  [82] = {.lex_state = 6},
  [83] = {.lex_state = 2},
  [84] = {.lex_state = 2},
  [85] = {.lex_state = 6},
  [86] = {.lex_state = 3},
  [87] = {.lex_state = 3},
  [88] = {.lex_state = 3},
  [89] = {.lex_state = 3},
  [90] = {.lex_state = 3},
  [91] = {.lex_state = 3},
  [92] = {.lex_state = 3},
  [93] = {.lex_state = 2},
  [94] = {.lex_state = 3},
  [95] = {.lex_state = 2},
  [96] = {.lex_state = 2},
  [97] = {.lex_state = 2},
  [98] = {.lex_state = 2},
  [99] = {.lex_state = 2},
  [100] = {.lex_state = 2},
  [101] = {.lex_state = 2},
  [102] = {.lex_state = 0},
  [103] = {.lex_state = 1},
  [104] = {.lex_state = 5},
  [105] = {.lex_state = 1},
  [106] = {.lex_state = 5},
  [107] = {.lex_state = 1},
  [108] = {.lex_state = 0},
  [109] = {.lex_state = 1},
  [110] = {.lex_state = 1},
  [111] = {.lex_state = 0},
  [112] = {.lex_state = 1},
  [113] = {.lex_state = 5},
  [114] = {.lex_state = 0},
  [115] = {.lex_state = 0},
  [116] = {.lex_state = 0},
  [117] = {.lex_state = 0},
  [118] = {.lex_state = 1},
  [119] = {.lex_state = 0},
  [120] = {.lex_state = 5},
  [121] = {.lex_state = 1},
  [122] = {.lex_state = 0},
  [123] = {.lex_state = 0},
  [124] = {.lex_state = 0},
  [125] = {.lex_state = 0},
  [126] = {.lex_state = 0},
  [127] = {.lex_state = 0},
  [128] = {.lex_state = 0},
  [129] = {.lex_state = 0},
  [130] = {.lex_state = 0},
  [131] = {.lex_state = 0},
  [132] = {.lex_state = 0},
  [133] = {.lex_state = 0},
  [134] = {.lex_state = 0},
  [135] = {.lex_state = 0},
  [136] = {.lex_state = 0},
  [137] = {.lex_state = 0},
  [138] = {.lex_state = 0},
  [139] = {.lex_state = 0},
  [140] = {.lex_state = 0},
  [141] = {.lex_state = 0},
  [142] = {.lex_state = 0},
  [143] = {.lex_state = 0},
  [144] = {.lex_state = 0},
  [145] = {.lex_state = 0},
  [146] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_STAR] = ACTIONS(1),
    [anon_sym__] = ACTIONS(1),
    [anon_sym_STAR_STAR] = ACTIONS(1),
    [anon_sym___] = ACTIONS(1),
    [anon_sym_BQUOTE] = ACTIONS(1),
    [anon_sym_LBRACK] = ACTIONS(1),
    [anon_sym_RBRACK] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [aux_sym_text_token2] = ACTIONS(1),
  },
  [1] = {
    [sym_inline] = STATE(124),
    [sym__inline_element] = STATE(2),
    [sym_emphasis] = STATE(2),
    [sym_strong_emphasis] = STATE(2),
    [sym_code_span] = STATE(2),
    [sym_link] = STATE(2),
    [sym_text] = STATE(2),
    [aux_sym_inline_repeat1] = STATE(2),
    [aux_sym_text_repeat1] = STATE(62),
    [anon_sym_STAR] = ACTIONS(3),
    [anon_sym__] = ACTIONS(5),
    [anon_sym_STAR_STAR] = ACTIONS(7),
    [anon_sym___] = ACTIONS(9),
    [anon_sym_BQUOTE] = ACTIONS(11),
    [anon_sym_LBRACK] = ACTIONS(13),
    [aux_sym_text_token1] = ACTIONS(15),
    [aux_sym_text_token2] = ACTIONS(17),
  },
  [2] = {
    [sym__inline_element] = STATE(3),
    [sym_emphasis] = STATE(3),
    [sym_strong_emphasis] = STATE(3),
    [sym_code_span] = STATE(3),
    [sym_link] = STATE(3),
    [sym_text] = STATE(3),
    [aux_sym_inline_repeat1] = STATE(3),
    [aux_sym_text_repeat1] = STATE(62),
    [ts_builtin_sym_end] = ACTIONS(19),
    [anon_sym_STAR] = ACTIONS(3),
    [anon_sym__] = ACTIONS(5),
    [anon_sym_STAR_STAR] = ACTIONS(7),
    [anon_sym___] = ACTIONS(9),
    [anon_sym_BQUOTE] = ACTIONS(11),
    [anon_sym_LBRACK] = ACTIONS(13),
    [aux_sym_text_token1] = ACTIONS(15),
    [aux_sym_text_token2] = ACTIONS(17),
  },
  [3] = {
    [sym__inline_element] = STATE(3),
    [sym_emphasis] = STATE(3),
    [sym_strong_emphasis] = STATE(3),
    [sym_code_span] = STATE(3),
    [sym_link] = STATE(3),
    [sym_text] = STATE(3),
    [aux_sym_inline_repeat1] = STATE(3),
    [aux_sym_text_repeat1] = STATE(62),
    [ts_builtin_sym_end] = ACTIONS(21),
    [anon_sym_STAR] = ACTIONS(23),
    [anon_sym__] = ACTIONS(26),
    [anon_sym_STAR_STAR] = ACTIONS(29),
    [anon_sym___] = ACTIONS(32),
    [anon_sym_BQUOTE] = ACTIONS(35),
    [anon_sym_LBRACK] = ACTIONS(38),
    [aux_sym_text_token1] = ACTIONS(41),
    [aux_sym_text_token2] = ACTIONS(44),
  },
  [4] = {
    [sym__inline_element] = STATE(29),
    [sym_emphasis] = STATE(29),
    [sym_strong_emphasis] = STATE(29),
    [sym_code_span] = STATE(29),
    [sym_link] = STATE(29),
    [sym_text] = STATE(29),
    [aux_sym_inline_repeat1] = STATE(29),
    [aux_sym_text_repeat1] = STATE(61),
    [ts_builtin_sym_end] = ACTIONS(47),
    [anon_sym_STAR] = ACTIONS(49),
    [anon_sym__] = ACTIONS(49),
    [anon_sym_STAR_STAR] = ACTIONS(49),
    [anon_sym___] = ACTIONS(49),
    [anon_sym_BQUOTE] = ACTIONS(49),
    [anon_sym_LBRACK] = ACTIONS(49),
    [aux_sym_text_token1] = ACTIONS(47),
    [aux_sym_text_token2] = ACTIONS(49),
  },
  [5] = {
    [sym__inline_element] = STATE(30),
    [sym_emphasis] = STATE(30),
    [sym_strong_emphasis] = STATE(30),
    [sym_code_span] = STATE(30),
    [sym_link] = STATE(30),
    [sym_text] = STATE(30),
    [aux_sym_inline_repeat1] = STATE(30),
    [aux_sym_text_repeat1] = STATE(61),
    [ts_builtin_sym_end] = ACTIONS(47),
    [anon_sym_STAR] = ACTIONS(49),
    [anon_sym__] = ACTIONS(49),
    [anon_sym_STAR_STAR] = ACTIONS(49),
    [anon_sym___] = ACTIONS(49),
    [anon_sym_BQUOTE] = ACTIONS(49),
    [anon_sym_LBRACK] = ACTIONS(49),
    [aux_sym_text_token1] = ACTIONS(47),
    [aux_sym_text_token2] = ACTIONS(49),
  },
  [6] = {
    [sym__inline_element] = STATE(29),
    [sym_emphasis] = STATE(29),
    [sym_strong_emphasis] = STATE(29),
    [sym_code_span] = STATE(29),
    [sym_link] = STATE(29),
    [sym_text] = STATE(29),
    [aux_sym_inline_repeat1] = STATE(29),
    [aux_sym_text_repeat1] = STATE(61),
    [anon_sym_STAR] = ACTIONS(49),
    [anon_sym__] = ACTIONS(49),
    [anon_sym_STAR_STAR] = ACTIONS(49),
    [anon_sym___] = ACTIONS(49),
    [anon_sym_BQUOTE] = ACTIONS(49),
    [anon_sym_LBRACK] = ACTIONS(51),
    [anon_sym_RBRACK] = ACTIONS(49),
    [aux_sym_text_token1] = ACTIONS(47),
    [aux_sym_text_token2] = ACTIONS(49),
  },
  [7] = {
    [sym__inline_element] = STATE(30),
    [sym_emphasis] = STATE(30),
    [sym_strong_emphasis] = STATE(30),
    [sym_code_span] = STATE(30),
    [sym_link] = STATE(30),
    [sym_text] = STATE(30),
    [aux_sym_inline_repeat1] = STATE(30),
    [aux_sym_text_repeat1] = STATE(61),
    [anon_sym_STAR] = ACTIONS(49),
    [anon_sym__] = ACTIONS(49),
    [anon_sym_STAR_STAR] = ACTIONS(49),
    [anon_sym___] = ACTIONS(49),
    [anon_sym_BQUOTE] = ACTIONS(49),
    [anon_sym_LBRACK] = ACTIONS(51),
    [anon_sym_RBRACK] = ACTIONS(49),
    [aux_sym_text_token1] = ACTIONS(47),
    [aux_sym_text_token2] = ACTIONS(49),
  },
  [8] = {
    [sym__inline_element] = STATE(29),
    [sym_emphasis] = STATE(29),
    [sym_strong_emphasis] = STATE(29),
    [sym_code_span] = STATE(29),
    [sym_link] = STATE(29),
    [sym_text] = STATE(29),
    [aux_sym_inline_repeat1] = STATE(29),
    [aux_sym_text_repeat1] = STATE(61),
    [anon_sym_STAR] = ACTIONS(53),
    [anon_sym__] = ACTIONS(55),
    [anon_sym_STAR_STAR] = ACTIONS(57),
    [anon_sym___] = ACTIONS(59),
    [anon_sym_BQUOTE] = ACTIONS(61),
    [anon_sym_LBRACK] = ACTIONS(51),
    [aux_sym_text_token1] = ACTIONS(63),
    [aux_sym_text_token2] = ACTIONS(65),
  },
  [9] = {
    [sym_emphasis] = STATE(47),
    [sym_strong_emphasis] = STATE(47),
    [sym_code_span] = STATE(47),
    [sym_link_text] = STATE(135),
    [sym__link_text_element] = STATE(47),
    [sym_text] = STATE(47),
    [aux_sym_link_text_repeat1] = STATE(47),
    [aux_sym_text_repeat1] = STATE(61),
    [anon_sym_STAR] = ACTIONS(53),
    [anon_sym__] = ACTIONS(55),
    [anon_sym_STAR_STAR] = ACTIONS(67),
    [anon_sym___] = ACTIONS(69),
    [anon_sym_BQUOTE] = ACTIONS(61),
    [anon_sym_RBRACK] = ACTIONS(71),
    [aux_sym_text_token1] = ACTIONS(63),
    [aux_sym_text_token2] = ACTIONS(65),
  },
  [10] = {
    [sym__inline_element] = STATE(35),
    [sym_emphasis] = STATE(35),
    [sym_strong_emphasis] = STATE(35),
    [sym_code_span] = STATE(35),
    [sym_link] = STATE(35),
    [sym_text] = STATE(35),
    [aux_sym_inline_repeat1] = STATE(35),
    [aux_sym_text_repeat1] = STATE(61),
    [anon_sym_STAR] = ACTIONS(53),
    [anon_sym__] = ACTIONS(55),
    [anon_sym_STAR_STAR] = ACTIONS(57),
    [anon_sym___] = ACTIONS(59),
    [anon_sym_BQUOTE] = ACTIONS(61),
    [anon_sym_LBRACK] = ACTIONS(51),
    [aux_sym_text_token1] = ACTIONS(63),
    [aux_sym_text_token2] = ACTIONS(65),
  },
  [11] = {
    [sym_emphasis] = STATE(48),
    [sym_strong_emphasis] = STATE(48),
    [sym_code_span] = STATE(48),
    [sym__link_text_element] = STATE(48),
    [sym_link_label] = STATE(126),
    [sym_text] = STATE(48),
    [aux_sym_link_text_repeat1] = STATE(48),
    [aux_sym_text_repeat1] = STATE(61),
    [anon_sym_STAR] = ACTIONS(53),
    [anon_sym__] = ACTIONS(55),
    [anon_sym_STAR_STAR] = ACTIONS(67),
    [anon_sym___] = ACTIONS(69),
    [anon_sym_BQUOTE] = ACTIONS(61),
    [anon_sym_RBRACK] = ACTIONS(73),
    [aux_sym_text_token1] = ACTIONS(63),
    [aux_sym_text_token2] = ACTIONS(65),
  },
  [12] = {
    [sym_emphasis] = STATE(48),
    [sym_strong_emphasis] = STATE(48),
    [sym_code_span] = STATE(48),
    [sym__link_text_element] = STATE(48),
    [sym_link_label] = STATE(129),
    [sym_text] = STATE(48),
    [aux_sym_link_text_repeat1] = STATE(48),
    [aux_sym_text_repeat1] = STATE(61),
    [anon_sym_STAR] = ACTIONS(53),
    [anon_sym__] = ACTIONS(55),
    [anon_sym_STAR_STAR] = ACTIONS(67),
    [anon_sym___] = ACTIONS(69),
    [anon_sym_BQUOTE] = ACTIONS(61),
    [anon_sym_RBRACK] = ACTIONS(75),
    [aux_sym_text_token1] = ACTIONS(63),
    [aux_sym_text_token2] = ACTIONS(65),
  },
  [13] = {
    [sym__inline_element] = STATE(13),
    [sym_emphasis] = STATE(13),
    [sym_strong_emphasis] = STATE(13),
    [sym_code_span] = STATE(13),
    [sym_link] = STATE(13),
    [sym_text] = STATE(13),
    [aux_sym_inline_repeat1] = STATE(13),
    [aux_sym_text_repeat1] = STATE(61),
    [anon_sym_STAR] = ACTIONS(77),
    [anon_sym__] = ACTIONS(80),
    [anon_sym_STAR_STAR] = ACTIONS(83),
    [anon_sym___] = ACTIONS(86),
    [anon_sym_BQUOTE] = ACTIONS(89),
    [anon_sym_LBRACK] = ACTIONS(92),
    [aux_sym_text_token1] = ACTIONS(95),
    [aux_sym_text_token2] = ACTIONS(98),
  },
  [14] = {
    [sym__inline_element] = STATE(29),
    [sym_emphasis] = STATE(29),
    [sym_strong_emphasis] = STATE(29),
    [sym_code_span] = STATE(29),
    [sym_link] = STATE(29),
    [sym_text] = STATE(29),
    [aux_sym_inline_repeat1] = STATE(29),
    [aux_sym_text_repeat1] = STATE(61),
    [anon_sym_STAR] = ACTIONS(49),
    [anon_sym__] = ACTIONS(55),
    [anon_sym_STAR_STAR] = ACTIONS(49),
    [anon_sym___] = ACTIONS(49),
    [anon_sym_BQUOTE] = ACTIONS(49),
    [anon_sym_LBRACK] = ACTIONS(49),
    [aux_sym_text_token1] = ACTIONS(47),
    [aux_sym_text_token2] = ACTIONS(49),
  },
  [15] = {
    [sym__inline_element] = STATE(30),
    [sym_emphasis] = STATE(30),
    [sym_strong_emphasis] = STATE(30),
    [sym_code_span] = STATE(30),
    [sym_link] = STATE(30),
    [sym_text] = STATE(30),
    [aux_sym_inline_repeat1] = STATE(30),
    [aux_sym_text_repeat1] = STATE(61),
    [anon_sym_STAR] = ACTIONS(49),
    [anon_sym__] = ACTIONS(55),
    [anon_sym_STAR_STAR] = ACTIONS(49),
    [anon_sym___] = ACTIONS(49),
    [anon_sym_BQUOTE] = ACTIONS(49),
    [anon_sym_LBRACK] = ACTIONS(49),
    [aux_sym_text_token1] = ACTIONS(47),
    [aux_sym_text_token2] = ACTIONS(49),
  },
  [16] = {
    [sym__inline_element] = STATE(29),
    [sym_emphasis] = STATE(29),
    [sym_strong_emphasis] = STATE(29),
    [sym_code_span] = STATE(29),
    [sym_link] = STATE(29),
    [sym_text] = STATE(29),
    [aux_sym_inline_repeat1] = STATE(29),
    [aux_sym_text_repeat1] = STATE(61),
    [anon_sym_STAR] = ACTIONS(53),
    [anon_sym__] = ACTIONS(49),
    [anon_sym_STAR_STAR] = ACTIONS(49),
    [anon_sym___] = ACTIONS(49),
    [anon_sym_BQUOTE] = ACTIONS(49),
    [anon_sym_LBRACK] = ACTIONS(49),
    [aux_sym_text_token1] = ACTIONS(47),
    [aux_sym_text_token2] = ACTIONS(49),
  },
  [17] = {
    [sym__inline_element] = STATE(30),
    [sym_emphasis] = STATE(30),
    [sym_strong_emphasis] = STATE(30),
    [sym_code_span] = STATE(30),
    [sym_link] = STATE(30),
    [sym_text] = STATE(30),
    [aux_sym_inline_repeat1] = STATE(30),
    [aux_sym_text_repeat1] = STATE(61),
    [anon_sym_STAR] = ACTIONS(53),
    [anon_sym__] = ACTIONS(49),
    [anon_sym_STAR_STAR] = ACTIONS(49),
    [anon_sym___] = ACTIONS(49),
    [anon_sym_BQUOTE] = ACTIONS(49),
    [anon_sym_LBRACK] = ACTIONS(49),
    [aux_sym_text_token1] = ACTIONS(47),
    [aux_sym_text_token2] = ACTIONS(49),
  },
  [18] = {
    [sym__inline_element] = STATE(29),
    [sym_emphasis] = STATE(29),
    [sym_strong_emphasis] = STATE(29),
    [sym_code_span] = STATE(29),
    [sym_link] = STATE(29),
    [sym_text] = STATE(29),
    [aux_sym_inline_repeat1] = STATE(29),
    [aux_sym_text_repeat1] = STATE(61),
    [anon_sym_STAR] = ACTIONS(49),
    [anon_sym__] = ACTIONS(49),
    [anon_sym_STAR_STAR] = ACTIONS(49),
    [anon_sym___] = ACTIONS(49),
    [anon_sym_BQUOTE] = ACTIONS(49),
    [anon_sym_LBRACK] = ACTIONS(49),
    [aux_sym_text_token1] = ACTIONS(47),
    [aux_sym_text_token2] = ACTIONS(49),
  },
  [19] = {
    [sym__inline_element] = STATE(30),
    [sym_emphasis] = STATE(30),
    [sym_strong_emphasis] = STATE(30),
    [sym_code_span] = STATE(30),
    [sym_link] = STATE(30),
    [sym_text] = STATE(30),
    [aux_sym_inline_repeat1] = STATE(30),
    [aux_sym_text_repeat1] = STATE(61),
    [anon_sym_STAR] = ACTIONS(49),
    [anon_sym__] = ACTIONS(49),
    [anon_sym_STAR_STAR] = ACTIONS(49),
    [anon_sym___] = ACTIONS(49),
    [anon_sym_BQUOTE] = ACTIONS(49),
    [anon_sym_LBRACK] = ACTIONS(49),
    [aux_sym_text_token1] = ACTIONS(47),
    [aux_sym_text_token2] = ACTIONS(49),
  },
  [20] = {
    [sym__inline_element] = STATE(13),
    [sym_emphasis] = STATE(13),
    [sym_strong_emphasis] = STATE(13),
    [sym_code_span] = STATE(13),
    [sym_link] = STATE(13),
    [sym_text] = STATE(13),
    [aux_sym_inline_repeat1] = STATE(13),
    [aux_sym_text_repeat1] = STATE(61),
    [anon_sym_STAR] = ACTIONS(53),
    [anon_sym__] = ACTIONS(55),
    [anon_sym_STAR_STAR] = ACTIONS(101),
    [anon_sym___] = ACTIONS(59),
    [anon_sym_BQUOTE] = ACTIONS(61),
    [anon_sym_LBRACK] = ACTIONS(51),
    [aux_sym_text_token1] = ACTIONS(63),
    [aux_sym_text_token2] = ACTIONS(65),
  },
  [21] = {
    [sym__inline_element] = STATE(13),
    [sym_emphasis] = STATE(13),
    [sym_strong_emphasis] = STATE(13),
    [sym_code_span] = STATE(13),
    [sym_link] = STATE(13),
    [sym_text] = STATE(13),
    [aux_sym_inline_repeat1] = STATE(13),
    [aux_sym_text_repeat1] = STATE(61),
    [anon_sym_STAR] = ACTIONS(53),
    [anon_sym__] = ACTIONS(55),
    [anon_sym_STAR_STAR] = ACTIONS(103),
    [anon_sym___] = ACTIONS(59),
    [anon_sym_BQUOTE] = ACTIONS(61),
    [anon_sym_LBRACK] = ACTIONS(51),
    [aux_sym_text_token1] = ACTIONS(63),
    [aux_sym_text_token2] = ACTIONS(65),
  },
  [22] = {
    [sym__inline_element] = STATE(13),
    [sym_emphasis] = STATE(13),
    [sym_strong_emphasis] = STATE(13),
    [sym_code_span] = STATE(13),
    [sym_link] = STATE(13),
    [sym_text] = STATE(13),
    [aux_sym_inline_repeat1] = STATE(13),
    [aux_sym_text_repeat1] = STATE(61),
    [anon_sym_STAR] = ACTIONS(53),
    [anon_sym__] = ACTIONS(55),
    [anon_sym_STAR_STAR] = ACTIONS(57),
    [anon_sym___] = ACTIONS(105),
    [anon_sym_BQUOTE] = ACTIONS(61),
    [anon_sym_LBRACK] = ACTIONS(51),
    [aux_sym_text_token1] = ACTIONS(63),
    [aux_sym_text_token2] = ACTIONS(65),
  },
  [23] = {
    [sym_emphasis] = STATE(48),
    [sym_strong_emphasis] = STATE(48),
    [sym_code_span] = STATE(48),
    [sym__link_text_element] = STATE(48),
    [sym_link_label] = STATE(131),
    [sym_text] = STATE(48),
    [aux_sym_link_text_repeat1] = STATE(48),
    [aux_sym_text_repeat1] = STATE(61),
    [anon_sym_STAR] = ACTIONS(53),
    [anon_sym__] = ACTIONS(55),
    [anon_sym_STAR_STAR] = ACTIONS(67),
    [anon_sym___] = ACTIONS(69),
    [anon_sym_BQUOTE] = ACTIONS(61),
    [anon_sym_RBRACK] = ACTIONS(107),
    [aux_sym_text_token1] = ACTIONS(63),
    [aux_sym_text_token2] = ACTIONS(65),
  },
  [24] = {
    [sym_emphasis] = STATE(48),
    [sym_strong_emphasis] = STATE(48),
    [sym_code_span] = STATE(48),
    [sym__link_text_element] = STATE(48),
    [sym_link_label] = STATE(138),
    [sym_text] = STATE(48),
    [aux_sym_link_text_repeat1] = STATE(48),
    [aux_sym_text_repeat1] = STATE(61),
    [anon_sym_STAR] = ACTIONS(53),
    [anon_sym__] = ACTIONS(55),
    [anon_sym_STAR_STAR] = ACTIONS(67),
    [anon_sym___] = ACTIONS(69),
    [anon_sym_BQUOTE] = ACTIONS(61),
    [anon_sym_RBRACK] = ACTIONS(109),
    [aux_sym_text_token1] = ACTIONS(63),
    [aux_sym_text_token2] = ACTIONS(65),
  },
  [25] = {
    [sym__inline_element] = STATE(13),
    [sym_emphasis] = STATE(13),
    [sym_strong_emphasis] = STATE(13),
    [sym_code_span] = STATE(13),
    [sym_link] = STATE(13),
    [sym_text] = STATE(13),
    [aux_sym_inline_repeat1] = STATE(13),
    [aux_sym_text_repeat1] = STATE(61),
    [anon_sym_STAR] = ACTIONS(53),
    [anon_sym__] = ACTIONS(55),
    [anon_sym_STAR_STAR] = ACTIONS(111),
    [anon_sym___] = ACTIONS(59),
    [anon_sym_BQUOTE] = ACTIONS(61),
    [anon_sym_LBRACK] = ACTIONS(51),
    [aux_sym_text_token1] = ACTIONS(63),
    [aux_sym_text_token2] = ACTIONS(65),
  },
  [26] = {
    [sym__inline_element] = STATE(13),
    [sym_emphasis] = STATE(13),
    [sym_strong_emphasis] = STATE(13),
    [sym_code_span] = STATE(13),
    [sym_link] = STATE(13),
    [sym_text] = STATE(13),
    [aux_sym_inline_repeat1] = STATE(13),
    [aux_sym_text_repeat1] = STATE(61),
    [anon_sym_STAR] = ACTIONS(53),
    [anon_sym__] = ACTIONS(55),
    [anon_sym_STAR_STAR] = ACTIONS(57),
    [anon_sym___] = ACTIONS(113),
    [anon_sym_BQUOTE] = ACTIONS(61),
    [anon_sym_LBRACK] = ACTIONS(51),
    [aux_sym_text_token1] = ACTIONS(63),
    [aux_sym_text_token2] = ACTIONS(65),
  },
  [27] = {
    [sym_emphasis] = STATE(48),
    [sym_strong_emphasis] = STATE(48),
    [sym_code_span] = STATE(48),
    [sym__link_text_element] = STATE(48),
    [sym_link_label] = STATE(137),
    [sym_text] = STATE(48),
    [aux_sym_link_text_repeat1] = STATE(48),
    [aux_sym_text_repeat1] = STATE(61),
    [anon_sym_STAR] = ACTIONS(53),
    [anon_sym__] = ACTIONS(55),
    [anon_sym_STAR_STAR] = ACTIONS(67),
    [anon_sym___] = ACTIONS(69),
    [anon_sym_BQUOTE] = ACTIONS(61),
    [anon_sym_RBRACK] = ACTIONS(115),
    [aux_sym_text_token1] = ACTIONS(63),
    [aux_sym_text_token2] = ACTIONS(65),
  },
  [28] = {
    [sym_emphasis] = STATE(48),
    [sym_strong_emphasis] = STATE(48),
    [sym_code_span] = STATE(48),
    [sym__link_text_element] = STATE(48),
    [sym_link_label] = STATE(127),
    [sym_text] = STATE(48),
    [aux_sym_link_text_repeat1] = STATE(48),
    [aux_sym_text_repeat1] = STATE(61),
    [anon_sym_STAR] = ACTIONS(53),
    [anon_sym__] = ACTIONS(55),
    [anon_sym_STAR_STAR] = ACTIONS(67),
    [anon_sym___] = ACTIONS(69),
    [anon_sym_BQUOTE] = ACTIONS(61),
    [anon_sym_RBRACK] = ACTIONS(117),
    [aux_sym_text_token1] = ACTIONS(63),
    [aux_sym_text_token2] = ACTIONS(65),
  },
  [29] = {
    [sym__inline_element] = STATE(13),
    [sym_emphasis] = STATE(13),
    [sym_strong_emphasis] = STATE(13),
    [sym_code_span] = STATE(13),
    [sym_link] = STATE(13),
    [sym_text] = STATE(13),
    [aux_sym_inline_repeat1] = STATE(13),
    [aux_sym_text_repeat1] = STATE(61),
    [anon_sym_STAR] = ACTIONS(53),
    [anon_sym__] = ACTIONS(55),
    [anon_sym_STAR_STAR] = ACTIONS(119),
    [anon_sym___] = ACTIONS(59),
    [anon_sym_BQUOTE] = ACTIONS(61),
    [anon_sym_LBRACK] = ACTIONS(51),
    [aux_sym_text_token1] = ACTIONS(63),
    [aux_sym_text_token2] = ACTIONS(65),
  },
  [30] = {
    [sym__inline_element] = STATE(13),
    [sym_emphasis] = STATE(13),
    [sym_strong_emphasis] = STATE(13),
    [sym_code_span] = STATE(13),
    [sym_link] = STATE(13),
    [sym_text] = STATE(13),
    [aux_sym_inline_repeat1] = STATE(13),
    [aux_sym_text_repeat1] = STATE(61),
    [anon_sym_STAR] = ACTIONS(53),
    [anon_sym__] = ACTIONS(55),
    [anon_sym_STAR_STAR] = ACTIONS(57),
    [anon_sym___] = ACTIONS(121),
    [anon_sym_BQUOTE] = ACTIONS(61),
    [anon_sym_LBRACK] = ACTIONS(51),
    [aux_sym_text_token1] = ACTIONS(63),
    [aux_sym_text_token2] = ACTIONS(65),
  },
  [31] = {
    [sym_emphasis] = STATE(48),
    [sym_strong_emphasis] = STATE(48),
    [sym_code_span] = STATE(48),
    [sym__link_text_element] = STATE(48),
    [sym_link_label] = STATE(133),
    [sym_text] = STATE(48),
    [aux_sym_link_text_repeat1] = STATE(48),
    [aux_sym_text_repeat1] = STATE(61),
    [anon_sym_STAR] = ACTIONS(53),
    [anon_sym__] = ACTIONS(55),
    [anon_sym_STAR_STAR] = ACTIONS(67),
    [anon_sym___] = ACTIONS(69),
    [anon_sym_BQUOTE] = ACTIONS(61),
    [anon_sym_RBRACK] = ACTIONS(123),
    [aux_sym_text_token1] = ACTIONS(63),
    [aux_sym_text_token2] = ACTIONS(65),
  },
  [32] = {
    [sym_emphasis] = STATE(48),
    [sym_strong_emphasis] = STATE(48),
    [sym_code_span] = STATE(48),
    [sym__link_text_element] = STATE(48),
    [sym_link_label] = STATE(140),
    [sym_text] = STATE(48),
    [aux_sym_link_text_repeat1] = STATE(48),
    [aux_sym_text_repeat1] = STATE(61),
    [anon_sym_STAR] = ACTIONS(53),
    [anon_sym__] = ACTIONS(55),
    [anon_sym_STAR_STAR] = ACTIONS(67),
    [anon_sym___] = ACTIONS(69),
    [anon_sym_BQUOTE] = ACTIONS(61),
    [anon_sym_RBRACK] = ACTIONS(125),
    [aux_sym_text_token1] = ACTIONS(63),
    [aux_sym_text_token2] = ACTIONS(65),
  },
  [33] = {
    [sym__inline_element] = STATE(13),
    [sym_emphasis] = STATE(13),
    [sym_strong_emphasis] = STATE(13),
    [sym_code_span] = STATE(13),
    [sym_link] = STATE(13),
    [sym_text] = STATE(13),
    [aux_sym_inline_repeat1] = STATE(13),
    [aux_sym_text_repeat1] = STATE(61),
    [anon_sym_STAR] = ACTIONS(53),
    [anon_sym__] = ACTIONS(55),
    [anon_sym_STAR_STAR] = ACTIONS(127),
    [anon_sym___] = ACTIONS(59),
    [anon_sym_BQUOTE] = ACTIONS(61),
    [anon_sym_LBRACK] = ACTIONS(51),
    [aux_sym_text_token1] = ACTIONS(63),
    [aux_sym_text_token2] = ACTIONS(65),
  },
  [34] = {
    [sym__inline_element] = STATE(13),
    [sym_emphasis] = STATE(13),
    [sym_strong_emphasis] = STATE(13),
    [sym_code_span] = STATE(13),
    [sym_link] = STATE(13),
    [sym_text] = STATE(13),
    [aux_sym_inline_repeat1] = STATE(13),
    [aux_sym_text_repeat1] = STATE(61),
    [anon_sym_STAR] = ACTIONS(53),
    [anon_sym__] = ACTIONS(55),
    [anon_sym_STAR_STAR] = ACTIONS(57),
    [anon_sym___] = ACTIONS(129),
    [anon_sym_BQUOTE] = ACTIONS(61),
    [anon_sym_LBRACK] = ACTIONS(51),
    [aux_sym_text_token1] = ACTIONS(63),
    [aux_sym_text_token2] = ACTIONS(65),
  },
  [35] = {
    [sym__inline_element] = STATE(13),
    [sym_emphasis] = STATE(13),
    [sym_strong_emphasis] = STATE(13),
    [sym_code_span] = STATE(13),
    [sym_link] = STATE(13),
    [sym_text] = STATE(13),
    [aux_sym_inline_repeat1] = STATE(13),
    [aux_sym_text_repeat1] = STATE(61),
    [anon_sym_STAR] = ACTIONS(53),
    [anon_sym__] = ACTIONS(55),
    [anon_sym_STAR_STAR] = ACTIONS(57),
    [anon_sym___] = ACTIONS(131),
    [anon_sym_BQUOTE] = ACTIONS(61),
    [anon_sym_LBRACK] = ACTIONS(51),
    [aux_sym_text_token1] = ACTIONS(63),
    [aux_sym_text_token2] = ACTIONS(65),
  },
  [36] = {
    [sym__inline_element] = STATE(21),
    [sym_emphasis] = STATE(21),
    [sym_strong_emphasis] = STATE(21),
    [sym_code_span] = STATE(21),
    [sym_link] = STATE(21),
    [sym_text] = STATE(21),
    [aux_sym_inline_repeat1] = STATE(21),
    [aux_sym_text_repeat1] = STATE(61),
    [anon_sym_STAR] = ACTIONS(53),
    [anon_sym__] = ACTIONS(55),
    [anon_sym_STAR_STAR] = ACTIONS(57),
    [anon_sym___] = ACTIONS(59),
    [anon_sym_BQUOTE] = ACTIONS(61),
    [anon_sym_LBRACK] = ACTIONS(51),
    [aux_sym_text_token1] = ACTIONS(63),
    [aux_sym_text_token2] = ACTIONS(65),
  },
  [37] = {
    [sym__inline_element] = STATE(22),
    [sym_emphasis] = STATE(22),
    [sym_strong_emphasis] = STATE(22),
    [sym_code_span] = STATE(22),
    [sym_link] = STATE(22),
    [sym_text] = STATE(22),
    [aux_sym_inline_repeat1] = STATE(22),
    [aux_sym_text_repeat1] = STATE(61),
    [anon_sym_STAR] = ACTIONS(53),
    [anon_sym__] = ACTIONS(55),
    [anon_sym_STAR_STAR] = ACTIONS(57),
    [anon_sym___] = ACTIONS(59),
    [anon_sym_BQUOTE] = ACTIONS(61),
    [anon_sym_LBRACK] = ACTIONS(51),
    [aux_sym_text_token1] = ACTIONS(63),
    [aux_sym_text_token2] = ACTIONS(65),
  },
  [38] = {
    [sym__inline_element] = STATE(25),
    [sym_emphasis] = STATE(25),
    [sym_strong_emphasis] = STATE(25),
    [sym_code_span] = STATE(25),
    [sym_link] = STATE(25),
    [sym_text] = STATE(25),
    [aux_sym_inline_repeat1] = STATE(25),
    [aux_sym_text_repeat1] = STATE(61),
    [anon_sym_STAR] = ACTIONS(53),
    [anon_sym__] = ACTIONS(55),
    [anon_sym_STAR_STAR] = ACTIONS(57),
    [anon_sym___] = ACTIONS(59),
    [anon_sym_BQUOTE] = ACTIONS(61),
    [anon_sym_LBRACK] = ACTIONS(51),
    [aux_sym_text_token1] = ACTIONS(63),
    [aux_sym_text_token2] = ACTIONS(65),
  },
  [39] = {
    [sym__inline_element] = STATE(26),
    [sym_emphasis] = STATE(26),
    [sym_strong_emphasis] = STATE(26),
    [sym_code_span] = STATE(26),
    [sym_link] = STATE(26),
    [sym_text] = STATE(26),
    [aux_sym_inline_repeat1] = STATE(26),
    [aux_sym_text_repeat1] = STATE(61),
    [anon_sym_STAR] = ACTIONS(53),
    [anon_sym__] = ACTIONS(55),
    [anon_sym_STAR_STAR] = ACTIONS(57),
    [anon_sym___] = ACTIONS(59),
    [anon_sym_BQUOTE] = ACTIONS(61),
    [anon_sym_LBRACK] = ACTIONS(51),
    [aux_sym_text_token1] = ACTIONS(63),
    [aux_sym_text_token2] = ACTIONS(65),
  },
  [40] = {
    [sym__inline_element] = STATE(30),
    [sym_emphasis] = STATE(30),
    [sym_strong_emphasis] = STATE(30),
    [sym_code_span] = STATE(30),
    [sym_link] = STATE(30),
    [sym_text] = STATE(30),
    [aux_sym_inline_repeat1] = STATE(30),
    [aux_sym_text_repeat1] = STATE(61),
    [anon_sym_STAR] = ACTIONS(53),
    [anon_sym__] = ACTIONS(55),
    [anon_sym_STAR_STAR] = ACTIONS(57),
    [anon_sym___] = ACTIONS(59),
    [anon_sym_BQUOTE] = ACTIONS(61),
    [anon_sym_LBRACK] = ACTIONS(51),
    [aux_sym_text_token1] = ACTIONS(63),
    [aux_sym_text_token2] = ACTIONS(65),
  },
  [41] = {
    [sym__inline_element] = STATE(33),
    [sym_emphasis] = STATE(33),
    [sym_strong_emphasis] = STATE(33),
    [sym_code_span] = STATE(33),
    [sym_link] = STATE(33),
    [sym_text] = STATE(33),
    [aux_sym_inline_repeat1] = STATE(33),
    [aux_sym_text_repeat1] = STATE(61),
    [anon_sym_STAR] = ACTIONS(53),
    [anon_sym__] = ACTIONS(55),
    [anon_sym_STAR_STAR] = ACTIONS(57),
    [anon_sym___] = ACTIONS(59),
    [anon_sym_BQUOTE] = ACTIONS(61),
    [anon_sym_LBRACK] = ACTIONS(51),
    [aux_sym_text_token1] = ACTIONS(63),
    [aux_sym_text_token2] = ACTIONS(65),
  },
  [42] = {
    [sym__inline_element] = STATE(34),
    [sym_emphasis] = STATE(34),
    [sym_strong_emphasis] = STATE(34),
    [sym_code_span] = STATE(34),
    [sym_link] = STATE(34),
    [sym_text] = STATE(34),
    [aux_sym_inline_repeat1] = STATE(34),
    [aux_sym_text_repeat1] = STATE(61),
    [anon_sym_STAR] = ACTIONS(53),
    [anon_sym__] = ACTIONS(55),
    [anon_sym_STAR_STAR] = ACTIONS(57),
    [anon_sym___] = ACTIONS(59),
    [anon_sym_BQUOTE] = ACTIONS(61),
    [anon_sym_LBRACK] = ACTIONS(51),
    [aux_sym_text_token1] = ACTIONS(63),
    [aux_sym_text_token2] = ACTIONS(65),
  },
  [43] = {
    [sym_emphasis] = STATE(47),
    [sym_strong_emphasis] = STATE(47),
    [sym_code_span] = STATE(47),
    [sym_link_text] = STATE(142),
    [sym__link_text_element] = STATE(47),
    [sym_text] = STATE(47),
    [aux_sym_link_text_repeat1] = STATE(47),
    [aux_sym_text_repeat1] = STATE(61),
    [anon_sym_STAR] = ACTIONS(53),
    [anon_sym__] = ACTIONS(55),
    [anon_sym_STAR_STAR] = ACTIONS(67),
    [anon_sym___] = ACTIONS(69),
    [anon_sym_BQUOTE] = ACTIONS(61),
    [anon_sym_RBRACK] = ACTIONS(133),
    [aux_sym_text_token1] = ACTIONS(63),
    [aux_sym_text_token2] = ACTIONS(65),
  },
  [44] = {
    [sym_emphasis] = STATE(47),
    [sym_strong_emphasis] = STATE(47),
    [sym_code_span] = STATE(47),
    [sym_link_text] = STATE(144),
    [sym__link_text_element] = STATE(47),
    [sym_text] = STATE(47),
    [aux_sym_link_text_repeat1] = STATE(47),
    [aux_sym_text_repeat1] = STATE(61),
    [anon_sym_STAR] = ACTIONS(53),
    [anon_sym__] = ACTIONS(55),
    [anon_sym_STAR_STAR] = ACTIONS(67),
    [anon_sym___] = ACTIONS(69),
    [anon_sym_BQUOTE] = ACTIONS(61),
    [anon_sym_RBRACK] = ACTIONS(135),
    [aux_sym_text_token1] = ACTIONS(63),
    [aux_sym_text_token2] = ACTIONS(65),
  },
  [45] = {
    [sym_emphasis] = STATE(47),
    [sym_strong_emphasis] = STATE(47),
    [sym_code_span] = STATE(47),
    [sym_link_text] = STATE(146),
    [sym__link_text_element] = STATE(47),
    [sym_text] = STATE(47),
    [aux_sym_link_text_repeat1] = STATE(47),
    [aux_sym_text_repeat1] = STATE(61),
    [anon_sym_STAR] = ACTIONS(53),
    [anon_sym__] = ACTIONS(55),
    [anon_sym_STAR_STAR] = ACTIONS(67),
    [anon_sym___] = ACTIONS(69),
    [anon_sym_BQUOTE] = ACTIONS(61),
    [anon_sym_RBRACK] = ACTIONS(137),
    [aux_sym_text_token1] = ACTIONS(63),
    [aux_sym_text_token2] = ACTIONS(65),
  },
  [46] = {
    [sym__inline_element] = STATE(20),
    [sym_emphasis] = STATE(20),
    [sym_strong_emphasis] = STATE(20),
    [sym_code_span] = STATE(20),
    [sym_link] = STATE(20),
    [sym_text] = STATE(20),
    [aux_sym_inline_repeat1] = STATE(20),
    [aux_sym_text_repeat1] = STATE(61),
    [anon_sym_STAR] = ACTIONS(53),
    [anon_sym__] = ACTIONS(55),
    [anon_sym_STAR_STAR] = ACTIONS(57),
    [anon_sym___] = ACTIONS(59),
    [anon_sym_BQUOTE] = ACTIONS(61),
    [anon_sym_LBRACK] = ACTIONS(51),
    [aux_sym_text_token1] = ACTIONS(63),
    [aux_sym_text_token2] = ACTIONS(65),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 10,
    ACTIONS(53), 1,
      anon_sym_STAR,
    ACTIONS(55), 1,
      anon_sym__,
    ACTIONS(61), 1,
      anon_sym_BQUOTE,
    ACTIONS(63), 1,
      aux_sym_text_token1,
    ACTIONS(65), 1,
      aux_sym_text_token2,
    ACTIONS(67), 1,
      anon_sym_STAR_STAR,
    ACTIONS(69), 1,
      anon_sym___,
    ACTIONS(139), 1,
      anon_sym_RBRACK,
    STATE(61), 1,
      aux_sym_text_repeat1,
    STATE(49), 6,
      sym_emphasis,
      sym_strong_emphasis,
      sym_code_span,
      sym__link_text_element,
      sym_text,
      aux_sym_link_text_repeat1,
  [36] = 10,
    ACTIONS(53), 1,
      anon_sym_STAR,
    ACTIONS(55), 1,
      anon_sym__,
    ACTIONS(61), 1,
      anon_sym_BQUOTE,
    ACTIONS(63), 1,
      aux_sym_text_token1,
    ACTIONS(65), 1,
      aux_sym_text_token2,
    ACTIONS(67), 1,
      anon_sym_STAR_STAR,
    ACTIONS(69), 1,
      anon_sym___,
    ACTIONS(141), 1,
      anon_sym_RBRACK,
    STATE(61), 1,
      aux_sym_text_repeat1,
    STATE(49), 6,
      sym_emphasis,
      sym_strong_emphasis,
      sym_code_span,
      sym__link_text_element,
      sym_text,
      aux_sym_link_text_repeat1,
  [72] = 10,
    ACTIONS(143), 1,
      anon_sym_STAR,
    ACTIONS(146), 1,
      anon_sym__,
    ACTIONS(149), 1,
      anon_sym_STAR_STAR,
    ACTIONS(152), 1,
      anon_sym___,
    ACTIONS(155), 1,
      anon_sym_BQUOTE,
    ACTIONS(158), 1,
      anon_sym_RBRACK,
    ACTIONS(160), 1,
      aux_sym_text_token1,
    ACTIONS(163), 1,
      aux_sym_text_token2,
    STATE(61), 1,
      aux_sym_text_repeat1,
    STATE(49), 6,
      sym_emphasis,
      sym_strong_emphasis,
      sym_code_span,
      sym__link_text_element,
      sym_text,
      aux_sym_link_text_repeat1,
  [108] = 9,
    ACTIONS(166), 1,
      anon_sym_STAR,
    ACTIONS(168), 1,
      anon_sym_STAR_STAR,
    ACTIONS(171), 1,
      anon_sym___,
    ACTIONS(174), 1,
      anon_sym_BQUOTE,
    ACTIONS(177), 1,
      anon_sym_LBRACK,
    ACTIONS(180), 1,
      aux_sym_text_token1,
    ACTIONS(183), 1,
      aux_sym_text_token2,
    STATE(83), 1,
      aux_sym_text_repeat1,
    STATE(50), 6,
      sym_strong_emphasis,
      sym__inline_no_star,
      sym_code_span,
      sym_link,
      sym_text,
      aux_sym_emphasis_repeat1,
  [141] = 9,
    ACTIONS(186), 1,
      anon_sym_STAR,
    ACTIONS(188), 1,
      anon_sym_STAR_STAR,
    ACTIONS(190), 1,
      anon_sym___,
    ACTIONS(192), 1,
      anon_sym_BQUOTE,
    ACTIONS(194), 1,
      anon_sym_LBRACK,
    ACTIONS(196), 1,
      aux_sym_text_token1,
    ACTIONS(198), 1,
      aux_sym_text_token2,
    STATE(83), 1,
      aux_sym_text_repeat1,
    STATE(50), 6,
      sym_strong_emphasis,
      sym__inline_no_star,
      sym_code_span,
      sym_link,
      sym_text,
      aux_sym_emphasis_repeat1,
  [174] = 9,
    ACTIONS(200), 1,
      anon_sym__,
    ACTIONS(202), 1,
      anon_sym_STAR_STAR,
    ACTIONS(205), 1,
      anon_sym___,
    ACTIONS(208), 1,
      anon_sym_BQUOTE,
    ACTIONS(211), 1,
      anon_sym_LBRACK,
    ACTIONS(214), 1,
      aux_sym_text_token1,
    ACTIONS(217), 1,
      aux_sym_text_token2,
    STATE(77), 1,
      aux_sym_text_repeat1,
    STATE(52), 6,
      sym_strong_emphasis,
      sym__inline_no_underscore,
      sym_code_span,
      sym_link,
      sym_text,
      aux_sym_emphasis_repeat2,
  [207] = 9,
    ACTIONS(188), 1,
      anon_sym_STAR_STAR,
    ACTIONS(190), 1,
      anon_sym___,
    ACTIONS(192), 1,
      anon_sym_BQUOTE,
    ACTIONS(194), 1,
      anon_sym_LBRACK,
    ACTIONS(196), 1,
      aux_sym_text_token1,
    ACTIONS(198), 1,
      aux_sym_text_token2,
    ACTIONS(220), 1,
      anon_sym_STAR,
    STATE(83), 1,
      aux_sym_text_repeat1,
    STATE(50), 6,
      sym_strong_emphasis,
      sym__inline_no_star,
      sym_code_span,
      sym_link,
      sym_text,
      aux_sym_emphasis_repeat1,
  [240] = 9,
    ACTIONS(220), 1,
      anon_sym__,
    ACTIONS(222), 1,
      anon_sym_STAR_STAR,
    ACTIONS(224), 1,
      anon_sym___,
    ACTIONS(226), 1,
      anon_sym_BQUOTE,
    ACTIONS(228), 1,
      anon_sym_LBRACK,
    ACTIONS(230), 1,
      aux_sym_text_token1,
    ACTIONS(232), 1,
      aux_sym_text_token2,
    STATE(77), 1,
      aux_sym_text_repeat1,
    STATE(52), 6,
      sym_strong_emphasis,
      sym__inline_no_underscore,
      sym_code_span,
      sym_link,
      sym_text,
      aux_sym_emphasis_repeat2,
  [273] = 9,
    ACTIONS(186), 1,
      anon_sym__,
    ACTIONS(222), 1,
      anon_sym_STAR_STAR,
    ACTIONS(224), 1,
      anon_sym___,
    ACTIONS(226), 1,
      anon_sym_BQUOTE,
    ACTIONS(228), 1,
      anon_sym_LBRACK,
    ACTIONS(230), 1,
      aux_sym_text_token1,
    ACTIONS(232), 1,
      aux_sym_text_token2,
    STATE(77), 1,
      aux_sym_text_repeat1,
    STATE(52), 6,
      sym_strong_emphasis,
      sym__inline_no_underscore,
      sym_code_span,
      sym_link,
      sym_text,
      aux_sym_emphasis_repeat2,
  [306] = 8,
    ACTIONS(222), 1,
      anon_sym_STAR_STAR,
    ACTIONS(224), 1,
      anon_sym___,
    ACTIONS(226), 1,
      anon_sym_BQUOTE,
    ACTIONS(228), 1,
      anon_sym_LBRACK,
    ACTIONS(230), 1,
      aux_sym_text_token1,
    ACTIONS(232), 1,
      aux_sym_text_token2,
    STATE(77), 1,
      aux_sym_text_repeat1,
    STATE(54), 6,
      sym_strong_emphasis,
      sym__inline_no_underscore,
      sym_code_span,
      sym_link,
      sym_text,
      aux_sym_emphasis_repeat2,
  [336] = 8,
    ACTIONS(222), 1,
      anon_sym_STAR_STAR,
    ACTIONS(224), 1,
      anon_sym___,
    ACTIONS(226), 1,
      anon_sym_BQUOTE,
    ACTIONS(228), 1,
      anon_sym_LBRACK,
    ACTIONS(230), 1,
      aux_sym_text_token1,
    ACTIONS(232), 1,
      aux_sym_text_token2,
    STATE(77), 1,
      aux_sym_text_repeat1,
    STATE(55), 6,
      sym_strong_emphasis,
      sym__inline_no_underscore,
      sym_code_span,
      sym_link,
      sym_text,
      aux_sym_emphasis_repeat2,
  [366] = 8,
    ACTIONS(188), 1,
      anon_sym_STAR_STAR,
    ACTIONS(190), 1,
      anon_sym___,
    ACTIONS(192), 1,
      anon_sym_BQUOTE,
    ACTIONS(194), 1,
      anon_sym_LBRACK,
    ACTIONS(196), 1,
      aux_sym_text_token1,
    ACTIONS(198), 1,
      aux_sym_text_token2,
    STATE(83), 1,
      aux_sym_text_repeat1,
    STATE(51), 6,
      sym_strong_emphasis,
      sym__inline_no_star,
      sym_code_span,
      sym_link,
      sym_text,
      aux_sym_emphasis_repeat1,
  [396] = 8,
    ACTIONS(188), 1,
      anon_sym_STAR_STAR,
    ACTIONS(190), 1,
      anon_sym___,
    ACTIONS(192), 1,
      anon_sym_BQUOTE,
    ACTIONS(194), 1,
      anon_sym_LBRACK,
    ACTIONS(196), 1,
      aux_sym_text_token1,
    ACTIONS(198), 1,
      aux_sym_text_token2,
    STATE(83), 1,
      aux_sym_text_repeat1,
    STATE(53), 6,
      sym_strong_emphasis,
      sym__inline_no_star,
      sym_code_span,
      sym_link,
      sym_text,
      aux_sym_emphasis_repeat1,
  [426] = 4,
    ACTIONS(236), 1,
      aux_sym_text_token1,
    ACTIONS(239), 1,
      aux_sym_text_token2,
    STATE(60), 1,
      aux_sym_text_repeat1,
    ACTIONS(234), 7,
      anon_sym_STAR,
      anon_sym__,
      anon_sym_STAR_STAR,
      anon_sym___,
      anon_sym_BQUOTE,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
  [445] = 4,
    ACTIONS(244), 1,
      aux_sym_text_token1,
    ACTIONS(246), 1,
      aux_sym_text_token2,
    STATE(60), 1,
      aux_sym_text_repeat1,
    ACTIONS(242), 7,
      anon_sym_STAR,
      anon_sym__,
      anon_sym_STAR_STAR,
      anon_sym___,
      anon_sym_BQUOTE,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
  [464] = 5,
    ACTIONS(248), 1,
      ts_builtin_sym_end,
    ACTIONS(250), 1,
      aux_sym_text_token1,
    ACTIONS(252), 1,
      aux_sym_text_token2,
    STATE(63), 1,
      aux_sym_text_repeat1,
    ACTIONS(242), 6,
      anon_sym_STAR,
      anon_sym__,
      anon_sym_STAR_STAR,
      anon_sym___,
      anon_sym_BQUOTE,
      anon_sym_LBRACK,
  [485] = 5,
    ACTIONS(254), 1,
      ts_builtin_sym_end,
    ACTIONS(256), 1,
      aux_sym_text_token1,
    ACTIONS(259), 1,
      aux_sym_text_token2,
    STATE(63), 1,
      aux_sym_text_repeat1,
    ACTIONS(234), 6,
      anon_sym_STAR,
      anon_sym__,
      anon_sym_STAR_STAR,
      anon_sym___,
      anon_sym_BQUOTE,
      anon_sym_LBRACK,
  [506] = 2,
    ACTIONS(262), 2,
      ts_builtin_sym_end,
      aux_sym_text_token1,
    ACTIONS(264), 7,
      anon_sym_STAR,
      anon_sym__,
      anon_sym_STAR_STAR,
      anon_sym___,
      anon_sym_BQUOTE,
      anon_sym_LBRACK,
      aux_sym_text_token2,
  [520] = 2,
    ACTIONS(268), 1,
      aux_sym_text_token1,
    ACTIONS(266), 8,
      anon_sym_STAR,
      anon_sym__,
      anon_sym_STAR_STAR,
      anon_sym___,
      anon_sym_BQUOTE,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      aux_sym_text_token2,
  [534] = 2,
    ACTIONS(268), 2,
      ts_builtin_sym_end,
      aux_sym_text_token1,
    ACTIONS(266), 7,
      anon_sym_STAR,
      anon_sym__,
      anon_sym_STAR_STAR,
      anon_sym___,
      anon_sym_BQUOTE,
      anon_sym_LBRACK,
      aux_sym_text_token2,
  [548] = 2,
    ACTIONS(272), 1,
      aux_sym_text_token1,
    ACTIONS(270), 8,
      anon_sym_STAR,
      anon_sym__,
      anon_sym_STAR_STAR,
      anon_sym___,
      anon_sym_BQUOTE,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      aux_sym_text_token2,
  [562] = 2,
    ACTIONS(272), 2,
      ts_builtin_sym_end,
      aux_sym_text_token1,
    ACTIONS(270), 7,
      anon_sym_STAR,
      anon_sym__,
      anon_sym_STAR_STAR,
      anon_sym___,
      anon_sym_BQUOTE,
      anon_sym_LBRACK,
      aux_sym_text_token2,
  [576] = 2,
    ACTIONS(274), 2,
      ts_builtin_sym_end,
      aux_sym_text_token1,
    ACTIONS(276), 7,
      anon_sym_STAR,
      anon_sym__,
      anon_sym_STAR_STAR,
      anon_sym___,
      anon_sym_BQUOTE,
      anon_sym_LBRACK,
      aux_sym_text_token2,
  [590] = 2,
    ACTIONS(278), 2,
      ts_builtin_sym_end,
      aux_sym_text_token1,
    ACTIONS(280), 7,
      anon_sym_STAR,
      anon_sym__,
      anon_sym_STAR_STAR,
      anon_sym___,
      anon_sym_BQUOTE,
      anon_sym_LBRACK,
      aux_sym_text_token2,
  [604] = 2,
    ACTIONS(282), 2,
      ts_builtin_sym_end,
      aux_sym_text_token1,
    ACTIONS(284), 7,
      anon_sym_STAR,
      anon_sym__,
      anon_sym_STAR_STAR,
      anon_sym___,
      anon_sym_BQUOTE,
      anon_sym_LBRACK,
      aux_sym_text_token2,
  [618] = 2,
    ACTIONS(286), 2,
      ts_builtin_sym_end,
      aux_sym_text_token1,
    ACTIONS(288), 7,
      anon_sym_STAR,
      anon_sym__,
      anon_sym_STAR_STAR,
      anon_sym___,
      anon_sym_BQUOTE,
      anon_sym_LBRACK,
      aux_sym_text_token2,
  [632] = 2,
    ACTIONS(290), 2,
      ts_builtin_sym_end,
      aux_sym_text_token1,
    ACTIONS(292), 7,
      anon_sym_STAR,
      anon_sym__,
      anon_sym_STAR_STAR,
      anon_sym___,
      anon_sym_BQUOTE,
      anon_sym_LBRACK,
      aux_sym_text_token2,
  [646] = 2,
    ACTIONS(294), 2,
      ts_builtin_sym_end,
      aux_sym_text_token1,
    ACTIONS(296), 7,
      anon_sym_STAR,
      anon_sym__,
      anon_sym_STAR_STAR,
      anon_sym___,
      anon_sym_BQUOTE,
      anon_sym_LBRACK,
      aux_sym_text_token2,
  [660] = 2,
    ACTIONS(262), 1,
      aux_sym_text_token1,
    ACTIONS(264), 8,
      anon_sym_STAR,
      anon_sym__,
      anon_sym_STAR_STAR,
      anon_sym___,
      anon_sym_BQUOTE,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      aux_sym_text_token2,
  [674] = 2,
    ACTIONS(278), 1,
      aux_sym_text_token1,
    ACTIONS(280), 7,
      anon_sym_STAR,
      anon_sym__,
      anon_sym_STAR_STAR,
      anon_sym___,
      anon_sym_BQUOTE,
      anon_sym_LBRACK,
      aux_sym_text_token2,
  [687] = 4,
    ACTIONS(298), 1,
      aux_sym_text_token1,
    ACTIONS(300), 1,
      aux_sym_text_token2,
    STATE(81), 1,
      aux_sym_text_repeat1,
    ACTIONS(242), 5,
      anon_sym__,
      anon_sym_STAR_STAR,
      anon_sym___,
      anon_sym_BQUOTE,
      anon_sym_LBRACK,
  [704] = 2,
    ACTIONS(282), 1,
      aux_sym_text_token1,
    ACTIONS(284), 7,
      anon_sym_STAR,
      anon_sym__,
      anon_sym_STAR_STAR,
      anon_sym___,
      anon_sym_BQUOTE,
      anon_sym_LBRACK,
      aux_sym_text_token2,
  [717] = 2,
    ACTIONS(286), 1,
      aux_sym_text_token1,
    ACTIONS(288), 7,
      anon_sym_STAR,
      anon_sym__,
      anon_sym_STAR_STAR,
      anon_sym___,
      anon_sym_BQUOTE,
      anon_sym_LBRACK,
      aux_sym_text_token2,
  [730] = 2,
    ACTIONS(290), 1,
      aux_sym_text_token1,
    ACTIONS(292), 7,
      anon_sym_STAR,
      anon_sym__,
      anon_sym_STAR_STAR,
      anon_sym___,
      anon_sym_BQUOTE,
      anon_sym_LBRACK,
      aux_sym_text_token2,
  [743] = 4,
    ACTIONS(302), 1,
      aux_sym_text_token1,
    ACTIONS(305), 1,
      aux_sym_text_token2,
    STATE(81), 1,
      aux_sym_text_repeat1,
    ACTIONS(234), 5,
      anon_sym__,
      anon_sym_STAR_STAR,
      anon_sym___,
      anon_sym_BQUOTE,
      anon_sym_LBRACK,
  [760] = 2,
    ACTIONS(294), 1,
      aux_sym_text_token1,
    ACTIONS(296), 7,
      anon_sym_STAR,
      anon_sym__,
      anon_sym_STAR_STAR,
      anon_sym___,
      anon_sym_BQUOTE,
      anon_sym_LBRACK,
      aux_sym_text_token2,
  [773] = 4,
    ACTIONS(308), 1,
      aux_sym_text_token1,
    ACTIONS(310), 1,
      aux_sym_text_token2,
    STATE(84), 1,
      aux_sym_text_repeat1,
    ACTIONS(242), 5,
      anon_sym_STAR,
      anon_sym_STAR_STAR,
      anon_sym___,
      anon_sym_BQUOTE,
      anon_sym_LBRACK,
  [790] = 4,
    ACTIONS(312), 1,
      aux_sym_text_token1,
    ACTIONS(315), 1,
      aux_sym_text_token2,
    STATE(84), 1,
      aux_sym_text_repeat1,
    ACTIONS(234), 5,
      anon_sym_STAR,
      anon_sym_STAR_STAR,
      anon_sym___,
      anon_sym_BQUOTE,
      anon_sym_LBRACK,
  [807] = 2,
    ACTIONS(274), 1,
      aux_sym_text_token1,
    ACTIONS(276), 7,
      anon_sym_STAR,
      anon_sym__,
      anon_sym_STAR_STAR,
      anon_sym___,
      anon_sym_BQUOTE,
      anon_sym_LBRACK,
      aux_sym_text_token2,
  [820] = 2,
    ACTIONS(282), 1,
      aux_sym_text_token1,
    ACTIONS(284), 6,
      anon_sym__,
      anon_sym_STAR_STAR,
      anon_sym___,
      anon_sym_BQUOTE,
      anon_sym_LBRACK,
      aux_sym_text_token2,
  [832] = 2,
    ACTIONS(290), 1,
      aux_sym_text_token1,
    ACTIONS(292), 6,
      anon_sym__,
      anon_sym_STAR_STAR,
      anon_sym___,
      anon_sym_BQUOTE,
      anon_sym_LBRACK,
      aux_sym_text_token2,
  [844] = 2,
    ACTIONS(286), 1,
      aux_sym_text_token1,
    ACTIONS(288), 6,
      anon_sym__,
      anon_sym_STAR_STAR,
      anon_sym___,
      anon_sym_BQUOTE,
      anon_sym_LBRACK,
      aux_sym_text_token2,
  [856] = 2,
    ACTIONS(268), 1,
      aux_sym_text_token1,
    ACTIONS(266), 6,
      anon_sym__,
      anon_sym_STAR_STAR,
      anon_sym___,
      anon_sym_BQUOTE,
      anon_sym_LBRACK,
      aux_sym_text_token2,
  [868] = 2,
    ACTIONS(272), 1,
      aux_sym_text_token1,
    ACTIONS(270), 6,
      anon_sym__,
      anon_sym_STAR_STAR,
      anon_sym___,
      anon_sym_BQUOTE,
      anon_sym_LBRACK,
      aux_sym_text_token2,
  [880] = 2,
    ACTIONS(294), 1,
      aux_sym_text_token1,
    ACTIONS(296), 6,
      anon_sym__,
      anon_sym_STAR_STAR,
      anon_sym___,
      anon_sym_BQUOTE,
      anon_sym_LBRACK,
      aux_sym_text_token2,
  [892] = 2,
    ACTIONS(274), 1,
      aux_sym_text_token1,
    ACTIONS(276), 6,
      anon_sym__,
      anon_sym_STAR_STAR,
      anon_sym___,
      anon_sym_BQUOTE,
      anon_sym_LBRACK,
      aux_sym_text_token2,
  [904] = 2,
    ACTIONS(268), 1,
      aux_sym_text_token1,
    ACTIONS(266), 6,
      anon_sym_STAR,
      anon_sym_STAR_STAR,
      anon_sym___,
      anon_sym_BQUOTE,
      anon_sym_LBRACK,
      aux_sym_text_token2,
  [916] = 2,
    ACTIONS(278), 1,
      aux_sym_text_token1,
    ACTIONS(280), 6,
      anon_sym__,
      anon_sym_STAR_STAR,
      anon_sym___,
      anon_sym_BQUOTE,
      anon_sym_LBRACK,
      aux_sym_text_token2,
  [928] = 2,
    ACTIONS(290), 1,
      aux_sym_text_token1,
    ACTIONS(292), 6,
      anon_sym_STAR,
      anon_sym_STAR_STAR,
      anon_sym___,
      anon_sym_BQUOTE,
      anon_sym_LBRACK,
      aux_sym_text_token2,
  [940] = 2,
    ACTIONS(286), 1,
      aux_sym_text_token1,
    ACTIONS(288), 6,
      anon_sym_STAR,
      anon_sym_STAR_STAR,
      anon_sym___,
      anon_sym_BQUOTE,
      anon_sym_LBRACK,
      aux_sym_text_token2,
  [952] = 2,
    ACTIONS(272), 1,
      aux_sym_text_token1,
    ACTIONS(270), 6,
      anon_sym_STAR,
      anon_sym_STAR_STAR,
      anon_sym___,
      anon_sym_BQUOTE,
      anon_sym_LBRACK,
      aux_sym_text_token2,
  [964] = 2,
    ACTIONS(294), 1,
      aux_sym_text_token1,
    ACTIONS(296), 6,
      anon_sym_STAR,
      anon_sym_STAR_STAR,
      anon_sym___,
      anon_sym_BQUOTE,
      anon_sym_LBRACK,
      aux_sym_text_token2,
  [976] = 2,
    ACTIONS(274), 1,
      aux_sym_text_token1,
    ACTIONS(276), 6,
      anon_sym_STAR,
      anon_sym_STAR_STAR,
      anon_sym___,
      anon_sym_BQUOTE,
      anon_sym_LBRACK,
      aux_sym_text_token2,
  [988] = 2,
    ACTIONS(278), 1,
      aux_sym_text_token1,
    ACTIONS(280), 6,
      anon_sym_STAR,
      anon_sym_STAR_STAR,
      anon_sym___,
      anon_sym_BQUOTE,
      anon_sym_LBRACK,
      aux_sym_text_token2,
  [1000] = 2,
    ACTIONS(282), 1,
      aux_sym_text_token1,
    ACTIONS(284), 6,
      anon_sym_STAR,
      anon_sym_STAR_STAR,
      anon_sym___,
      anon_sym_BQUOTE,
      anon_sym_LBRACK,
      aux_sym_text_token2,
  [1012] = 2,
    ACTIONS(318), 1,
      anon_sym_LBRACK,
    ACTIONS(320), 1,
      anon_sym_LPAREN,
  [1019] = 2,
    ACTIONS(115), 1,
      anon_sym_RPAREN,
    ACTIONS(322), 1,
      sym_link_destination,
  [1026] = 2,
    ACTIONS(324), 1,
      anon_sym_BQUOTE,
    ACTIONS(326), 1,
      aux_sym_code_span_token1,
  [1033] = 2,
    ACTIONS(117), 1,
      anon_sym_RPAREN,
    ACTIONS(328), 1,
      sym_link_destination,
  [1040] = 2,
    ACTIONS(330), 1,
      anon_sym_BQUOTE,
    ACTIONS(332), 1,
      aux_sym_code_span_token1,
  [1047] = 2,
    ACTIONS(73), 1,
      anon_sym_RPAREN,
    ACTIONS(334), 1,
      sym_link_destination,
  [1054] = 2,
    ACTIONS(336), 1,
      anon_sym_LBRACK,
    ACTIONS(338), 1,
      anon_sym_LPAREN,
  [1061] = 2,
    ACTIONS(123), 1,
      anon_sym_RPAREN,
    ACTIONS(340), 1,
      sym_link_destination,
  [1068] = 2,
    ACTIONS(125), 1,
      anon_sym_RPAREN,
    ACTIONS(342), 1,
      sym_link_destination,
  [1075] = 2,
    ACTIONS(344), 1,
      anon_sym_LBRACK,
    ACTIONS(346), 1,
      anon_sym_LPAREN,
  [1082] = 2,
    ACTIONS(107), 1,
      anon_sym_RPAREN,
    ACTIONS(348), 1,
      sym_link_destination,
  [1089] = 2,
    ACTIONS(350), 1,
      anon_sym_BQUOTE,
    ACTIONS(352), 1,
      aux_sym_code_span_token1,
  [1096] = 2,
    ACTIONS(354), 1,
      anon_sym_LBRACK,
    ACTIONS(356), 1,
      anon_sym_LPAREN,
  [1103] = 2,
    ACTIONS(358), 1,
      anon_sym_LBRACK,
    ACTIONS(360), 1,
      anon_sym_LPAREN,
  [1110] = 2,
    ACTIONS(362), 1,
      anon_sym_LBRACK,
    ACTIONS(364), 1,
      anon_sym_LPAREN,
  [1117] = 2,
    ACTIONS(366), 1,
      anon_sym_LBRACK,
    ACTIONS(368), 1,
      anon_sym_LPAREN,
  [1124] = 2,
    ACTIONS(109), 1,
      anon_sym_RPAREN,
    ACTIONS(370), 1,
      sym_link_destination,
  [1131] = 2,
    ACTIONS(372), 1,
      anon_sym_LBRACK,
    ACTIONS(374), 1,
      anon_sym_LPAREN,
  [1138] = 2,
    ACTIONS(376), 1,
      anon_sym_BQUOTE,
    ACTIONS(378), 1,
      aux_sym_code_span_token1,
  [1145] = 2,
    ACTIONS(75), 1,
      anon_sym_RPAREN,
    ACTIONS(380), 1,
      sym_link_destination,
  [1152] = 1,
    ACTIONS(382), 1,
      anon_sym_RPAREN,
  [1156] = 1,
    ACTIONS(384), 1,
      anon_sym_RPAREN,
  [1160] = 1,
    ACTIONS(386), 1,
      ts_builtin_sym_end,
  [1164] = 1,
    ACTIONS(388), 1,
      anon_sym_BQUOTE,
  [1168] = 1,
    ACTIONS(390), 1,
      anon_sym_RBRACK,
  [1172] = 1,
    ACTIONS(392), 1,
      anon_sym_RBRACK,
  [1176] = 1,
    ACTIONS(394), 1,
      anon_sym_BQUOTE,
  [1180] = 1,
    ACTIONS(396), 1,
      anon_sym_RBRACK,
  [1184] = 1,
    ACTIONS(398), 1,
      anon_sym_RPAREN,
  [1188] = 1,
    ACTIONS(400), 1,
      anon_sym_RBRACK,
  [1192] = 1,
    ACTIONS(402), 1,
      anon_sym_RPAREN,
  [1196] = 1,
    ACTIONS(404), 1,
      anon_sym_RBRACK,
  [1200] = 1,
    ACTIONS(406), 1,
      anon_sym_RPAREN,
  [1204] = 1,
    ACTIONS(408), 1,
      anon_sym_RBRACK,
  [1208] = 1,
    ACTIONS(410), 1,
      anon_sym_RPAREN,
  [1212] = 1,
    ACTIONS(412), 1,
      anon_sym_RBRACK,
  [1216] = 1,
    ACTIONS(414), 1,
      anon_sym_RBRACK,
  [1220] = 1,
    ACTIONS(416), 1,
      anon_sym_RPAREN,
  [1224] = 1,
    ACTIONS(418), 1,
      anon_sym_RBRACK,
  [1228] = 1,
    ACTIONS(420), 1,
      anon_sym_RPAREN,
  [1232] = 1,
    ACTIONS(422), 1,
      anon_sym_RBRACK,
  [1236] = 1,
    ACTIONS(424), 1,
      anon_sym_BQUOTE,
  [1240] = 1,
    ACTIONS(426), 1,
      anon_sym_RBRACK,
  [1244] = 1,
    ACTIONS(428), 1,
      anon_sym_BQUOTE,
  [1248] = 1,
    ACTIONS(430), 1,
      anon_sym_RBRACK,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(47)] = 0,
  [SMALL_STATE(48)] = 36,
  [SMALL_STATE(49)] = 72,
  [SMALL_STATE(50)] = 108,
  [SMALL_STATE(51)] = 141,
  [SMALL_STATE(52)] = 174,
  [SMALL_STATE(53)] = 207,
  [SMALL_STATE(54)] = 240,
  [SMALL_STATE(55)] = 273,
  [SMALL_STATE(56)] = 306,
  [SMALL_STATE(57)] = 336,
  [SMALL_STATE(58)] = 366,
  [SMALL_STATE(59)] = 396,
  [SMALL_STATE(60)] = 426,
  [SMALL_STATE(61)] = 445,
  [SMALL_STATE(62)] = 464,
  [SMALL_STATE(63)] = 485,
  [SMALL_STATE(64)] = 506,
  [SMALL_STATE(65)] = 520,
  [SMALL_STATE(66)] = 534,
  [SMALL_STATE(67)] = 548,
  [SMALL_STATE(68)] = 562,
  [SMALL_STATE(69)] = 576,
  [SMALL_STATE(70)] = 590,
  [SMALL_STATE(71)] = 604,
  [SMALL_STATE(72)] = 618,
  [SMALL_STATE(73)] = 632,
  [SMALL_STATE(74)] = 646,
  [SMALL_STATE(75)] = 660,
  [SMALL_STATE(76)] = 674,
  [SMALL_STATE(77)] = 687,
  [SMALL_STATE(78)] = 704,
  [SMALL_STATE(79)] = 717,
  [SMALL_STATE(80)] = 730,
  [SMALL_STATE(81)] = 743,
  [SMALL_STATE(82)] = 760,
  [SMALL_STATE(83)] = 773,
  [SMALL_STATE(84)] = 790,
  [SMALL_STATE(85)] = 807,
  [SMALL_STATE(86)] = 820,
  [SMALL_STATE(87)] = 832,
  [SMALL_STATE(88)] = 844,
  [SMALL_STATE(89)] = 856,
  [SMALL_STATE(90)] = 868,
  [SMALL_STATE(91)] = 880,
  [SMALL_STATE(92)] = 892,
  [SMALL_STATE(93)] = 904,
  [SMALL_STATE(94)] = 916,
  [SMALL_STATE(95)] = 928,
  [SMALL_STATE(96)] = 940,
  [SMALL_STATE(97)] = 952,
  [SMALL_STATE(98)] = 964,
  [SMALL_STATE(99)] = 976,
  [SMALL_STATE(100)] = 988,
  [SMALL_STATE(101)] = 1000,
  [SMALL_STATE(102)] = 1012,
  [SMALL_STATE(103)] = 1019,
  [SMALL_STATE(104)] = 1026,
  [SMALL_STATE(105)] = 1033,
  [SMALL_STATE(106)] = 1040,
  [SMALL_STATE(107)] = 1047,
  [SMALL_STATE(108)] = 1054,
  [SMALL_STATE(109)] = 1061,
  [SMALL_STATE(110)] = 1068,
  [SMALL_STATE(111)] = 1075,
  [SMALL_STATE(112)] = 1082,
  [SMALL_STATE(113)] = 1089,
  [SMALL_STATE(114)] = 1096,
  [SMALL_STATE(115)] = 1103,
  [SMALL_STATE(116)] = 1110,
  [SMALL_STATE(117)] = 1117,
  [SMALL_STATE(118)] = 1124,
  [SMALL_STATE(119)] = 1131,
  [SMALL_STATE(120)] = 1138,
  [SMALL_STATE(121)] = 1145,
  [SMALL_STATE(122)] = 1152,
  [SMALL_STATE(123)] = 1156,
  [SMALL_STATE(124)] = 1160,
  [SMALL_STATE(125)] = 1164,
  [SMALL_STATE(126)] = 1168,
  [SMALL_STATE(127)] = 1172,
  [SMALL_STATE(128)] = 1176,
  [SMALL_STATE(129)] = 1180,
  [SMALL_STATE(130)] = 1184,
  [SMALL_STATE(131)] = 1188,
  [SMALL_STATE(132)] = 1192,
  [SMALL_STATE(133)] = 1196,
  [SMALL_STATE(134)] = 1200,
  [SMALL_STATE(135)] = 1204,
  [SMALL_STATE(136)] = 1208,
  [SMALL_STATE(137)] = 1212,
  [SMALL_STATE(138)] = 1216,
  [SMALL_STATE(139)] = 1220,
  [SMALL_STATE(140)] = 1224,
  [SMALL_STATE(141)] = 1228,
  [SMALL_STATE(142)] = 1232,
  [SMALL_STATE(143)] = 1236,
  [SMALL_STATE(144)] = 1240,
  [SMALL_STATE(145)] = 1244,
  [SMALL_STATE(146)] = 1248,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = false}}, SHIFT(58),
  [5] = {.entry = {.count = 1, .reusable = false}}, SHIFT(57),
  [7] = {.entry = {.count = 1, .reusable = false}}, SHIFT(46),
  [9] = {.entry = {.count = 1, .reusable = false}}, SHIFT(10),
  [11] = {.entry = {.count = 1, .reusable = false}}, SHIFT(113),
  [13] = {.entry = {.count = 1, .reusable = false}}, SHIFT(9),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(62),
  [17] = {.entry = {.count = 1, .reusable = false}}, SHIFT(62),
  [19] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_inline, 1, 0, 0),
  [21] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_inline_repeat1, 2, 0, 0),
  [23] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_inline_repeat1, 2, 0, 0), SHIFT_REPEAT(58),
  [26] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_inline_repeat1, 2, 0, 0), SHIFT_REPEAT(57),
  [29] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_inline_repeat1, 2, 0, 0), SHIFT_REPEAT(46),
  [32] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_inline_repeat1, 2, 0, 0), SHIFT_REPEAT(10),
  [35] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_inline_repeat1, 2, 0, 0), SHIFT_REPEAT(113),
  [38] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_inline_repeat1, 2, 0, 0), SHIFT_REPEAT(9),
  [41] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_inline_repeat1, 2, 0, 0), SHIFT_REPEAT(62),
  [44] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_inline_repeat1, 2, 0, 0), SHIFT_REPEAT(62),
  [47] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_strong_emphasis, 3, 0, 0),
  [49] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_strong_emphasis, 3, 0, 0),
  [51] = {.entry = {.count = 1, .reusable = false}}, SHIFT(45),
  [53] = {.entry = {.count = 1, .reusable = false}}, SHIFT(59),
  [55] = {.entry = {.count = 1, .reusable = false}}, SHIFT(56),
  [57] = {.entry = {.count = 1, .reusable = false}}, SHIFT(8),
  [59] = {.entry = {.count = 1, .reusable = false}}, SHIFT(40),
  [61] = {.entry = {.count = 1, .reusable = false}}, SHIFT(106),
  [63] = {.entry = {.count = 1, .reusable = true}}, SHIFT(61),
  [65] = {.entry = {.count = 1, .reusable = false}}, SHIFT(61),
  [67] = {.entry = {.count = 1, .reusable = false}}, SHIFT(41),
  [69] = {.entry = {.count = 1, .reusable = false}}, SHIFT(42),
  [71] = {.entry = {.count = 1, .reusable = false}}, SHIFT(111),
  [73] = {.entry = {.count = 1, .reusable = false}}, SHIFT(74),
  [75] = {.entry = {.count = 1, .reusable = false}}, SHIFT(71),
  [77] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_inline_repeat1, 2, 0, 0), SHIFT_REPEAT(59),
  [80] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_inline_repeat1, 2, 0, 0), SHIFT_REPEAT(56),
  [83] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_inline_repeat1, 2, 0, 0), SHIFT_REPEAT(8),
  [86] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_inline_repeat1, 2, 0, 0), SHIFT_REPEAT(40),
  [89] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_inline_repeat1, 2, 0, 0), SHIFT_REPEAT(106),
  [92] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_inline_repeat1, 2, 0, 0), SHIFT_REPEAT(45),
  [95] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_inline_repeat1, 2, 0, 0), SHIFT_REPEAT(61),
  [98] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_inline_repeat1, 2, 0, 0), SHIFT_REPEAT(61),
  [101] = {.entry = {.count = 1, .reusable = false}}, SHIFT(4),
  [103] = {.entry = {.count = 1, .reusable = false}}, SHIFT(14),
  [105] = {.entry = {.count = 1, .reusable = false}}, SHIFT(15),
  [107] = {.entry = {.count = 1, .reusable = false}}, SHIFT(98),
  [109] = {.entry = {.count = 1, .reusable = false}}, SHIFT(101),
  [111] = {.entry = {.count = 1, .reusable = false}}, SHIFT(16),
  [113] = {.entry = {.count = 1, .reusable = false}}, SHIFT(17),
  [115] = {.entry = {.count = 1, .reusable = false}}, SHIFT(91),
  [117] = {.entry = {.count = 1, .reusable = false}}, SHIFT(86),
  [119] = {.entry = {.count = 1, .reusable = false}}, SHIFT(18),
  [121] = {.entry = {.count = 1, .reusable = false}}, SHIFT(19),
  [123] = {.entry = {.count = 1, .reusable = false}}, SHIFT(82),
  [125] = {.entry = {.count = 1, .reusable = false}}, SHIFT(78),
  [127] = {.entry = {.count = 1, .reusable = false}}, SHIFT(6),
  [129] = {.entry = {.count = 1, .reusable = false}}, SHIFT(7),
  [131] = {.entry = {.count = 1, .reusable = false}}, SHIFT(5),
  [133] = {.entry = {.count = 1, .reusable = false}}, SHIFT(114),
  [135] = {.entry = {.count = 1, .reusable = false}}, SHIFT(116),
  [137] = {.entry = {.count = 1, .reusable = false}}, SHIFT(119),
  [139] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_link_text, 1, 0, 0),
  [141] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_link_label, 1, 0, 0),
  [143] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_link_text_repeat1, 2, 0, 0), SHIFT_REPEAT(59),
  [146] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_link_text_repeat1, 2, 0, 0), SHIFT_REPEAT(56),
  [149] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_link_text_repeat1, 2, 0, 0), SHIFT_REPEAT(41),
  [152] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_link_text_repeat1, 2, 0, 0), SHIFT_REPEAT(42),
  [155] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_link_text_repeat1, 2, 0, 0), SHIFT_REPEAT(106),
  [158] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_link_text_repeat1, 2, 0, 0),
  [160] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_link_text_repeat1, 2, 0, 0), SHIFT_REPEAT(61),
  [163] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_link_text_repeat1, 2, 0, 0), SHIFT_REPEAT(61),
  [166] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_emphasis_repeat1, 2, 0, 0),
  [168] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_emphasis_repeat1, 2, 0, 0), SHIFT_REPEAT(36),
  [171] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_emphasis_repeat1, 2, 0, 0), SHIFT_REPEAT(37),
  [174] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_emphasis_repeat1, 2, 0, 0), SHIFT_REPEAT(104),
  [177] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_emphasis_repeat1, 2, 0, 0), SHIFT_REPEAT(43),
  [180] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_emphasis_repeat1, 2, 0, 0), SHIFT_REPEAT(83),
  [183] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_emphasis_repeat1, 2, 0, 0), SHIFT_REPEAT(83),
  [186] = {.entry = {.count = 1, .reusable = false}}, SHIFT(64),
  [188] = {.entry = {.count = 1, .reusable = false}}, SHIFT(36),
  [190] = {.entry = {.count = 1, .reusable = false}}, SHIFT(37),
  [192] = {.entry = {.count = 1, .reusable = false}}, SHIFT(104),
  [194] = {.entry = {.count = 1, .reusable = false}}, SHIFT(43),
  [196] = {.entry = {.count = 1, .reusable = true}}, SHIFT(83),
  [198] = {.entry = {.count = 1, .reusable = false}}, SHIFT(83),
  [200] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_emphasis_repeat2, 2, 0, 0),
  [202] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_emphasis_repeat2, 2, 0, 0), SHIFT_REPEAT(38),
  [205] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_emphasis_repeat2, 2, 0, 0), SHIFT_REPEAT(39),
  [208] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_emphasis_repeat2, 2, 0, 0), SHIFT_REPEAT(120),
  [211] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_emphasis_repeat2, 2, 0, 0), SHIFT_REPEAT(44),
  [214] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_emphasis_repeat2, 2, 0, 0), SHIFT_REPEAT(77),
  [217] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_emphasis_repeat2, 2, 0, 0), SHIFT_REPEAT(77),
  [220] = {.entry = {.count = 1, .reusable = false}}, SHIFT(75),
  [222] = {.entry = {.count = 1, .reusable = false}}, SHIFT(38),
  [224] = {.entry = {.count = 1, .reusable = false}}, SHIFT(39),
  [226] = {.entry = {.count = 1, .reusable = false}}, SHIFT(120),
  [228] = {.entry = {.count = 1, .reusable = false}}, SHIFT(44),
  [230] = {.entry = {.count = 1, .reusable = true}}, SHIFT(77),
  [232] = {.entry = {.count = 1, .reusable = false}}, SHIFT(77),
  [234] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_text_repeat1, 2, 0, 0),
  [236] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_text_repeat1, 2, 0, 0), SHIFT_REPEAT(60),
  [239] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_text_repeat1, 2, 0, 0), SHIFT_REPEAT(60),
  [242] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_text, 1, 0, 0),
  [244] = {.entry = {.count = 1, .reusable = true}}, SHIFT(60),
  [246] = {.entry = {.count = 1, .reusable = false}}, SHIFT(60),
  [248] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_text, 1, 0, 0),
  [250] = {.entry = {.count = 1, .reusable = true}}, SHIFT(63),
  [252] = {.entry = {.count = 1, .reusable = false}}, SHIFT(63),
  [254] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_text_repeat1, 2, 0, 0),
  [256] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_text_repeat1, 2, 0, 0), SHIFT_REPEAT(63),
  [259] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_text_repeat1, 2, 0, 0), SHIFT_REPEAT(63),
  [262] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_emphasis, 3, 0, 0),
  [264] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_emphasis, 3, 0, 0),
  [266] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_code_span, 2, 0, 0),
  [268] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_code_span, 2, 0, 0),
  [270] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_code_span, 3, 0, 1),
  [272] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_code_span, 3, 0, 1),
  [274] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_link, 5, 0, 2),
  [276] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_link, 5, 0, 2),
  [278] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_link, 5, 0, 3),
  [280] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_link, 5, 0, 3),
  [282] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_link, 5, 0, 4),
  [284] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_link, 5, 0, 4),
  [286] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_link, 6, 0, 5),
  [288] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_link, 6, 0, 5),
  [290] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_link, 6, 0, 6),
  [292] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_link, 6, 0, 6),
  [294] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_link, 4, 0, 0),
  [296] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_link, 4, 0, 0),
  [298] = {.entry = {.count = 1, .reusable = true}}, SHIFT(81),
  [300] = {.entry = {.count = 1, .reusable = false}}, SHIFT(81),
  [302] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_text_repeat1, 2, 0, 0), SHIFT_REPEAT(81),
  [305] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_text_repeat1, 2, 0, 0), SHIFT_REPEAT(81),
  [308] = {.entry = {.count = 1, .reusable = true}}, SHIFT(84),
  [310] = {.entry = {.count = 1, .reusable = false}}, SHIFT(84),
  [312] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_text_repeat1, 2, 0, 0), SHIFT_REPEAT(84),
  [315] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_text_repeat1, 2, 0, 0), SHIFT_REPEAT(84),
  [318] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [320] = {.entry = {.count = 1, .reusable = true}}, SHIFT(110),
  [322] = {.entry = {.count = 1, .reusable = true}}, SHIFT(123),
  [324] = {.entry = {.count = 1, .reusable = false}}, SHIFT(93),
  [326] = {.entry = {.count = 1, .reusable = true}}, SHIFT(125),
  [328] = {.entry = {.count = 1, .reusable = true}}, SHIFT(130),
  [330] = {.entry = {.count = 1, .reusable = false}}, SHIFT(65),
  [332] = {.entry = {.count = 1, .reusable = true}}, SHIFT(128),
  [334] = {.entry = {.count = 1, .reusable = true}}, SHIFT(141),
  [336] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [338] = {.entry = {.count = 1, .reusable = true}}, SHIFT(121),
  [340] = {.entry = {.count = 1, .reusable = true}}, SHIFT(134),
  [342] = {.entry = {.count = 1, .reusable = true}}, SHIFT(122),
  [344] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [346] = {.entry = {.count = 1, .reusable = true}}, SHIFT(107),
  [348] = {.entry = {.count = 1, .reusable = true}}, SHIFT(132),
  [350] = {.entry = {.count = 1, .reusable = false}}, SHIFT(66),
  [352] = {.entry = {.count = 1, .reusable = true}}, SHIFT(143),
  [354] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [356] = {.entry = {.count = 1, .reusable = true}}, SHIFT(112),
  [358] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [360] = {.entry = {.count = 1, .reusable = true}}, SHIFT(118),
  [362] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [364] = {.entry = {.count = 1, .reusable = true}}, SHIFT(103),
  [366] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [368] = {.entry = {.count = 1, .reusable = true}}, SHIFT(105),
  [370] = {.entry = {.count = 1, .reusable = true}}, SHIFT(139),
  [372] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [374] = {.entry = {.count = 1, .reusable = true}}, SHIFT(109),
  [376] = {.entry = {.count = 1, .reusable = false}}, SHIFT(89),
  [378] = {.entry = {.count = 1, .reusable = true}}, SHIFT(145),
  [380] = {.entry = {.count = 1, .reusable = true}}, SHIFT(136),
  [382] = {.entry = {.count = 1, .reusable = true}}, SHIFT(80),
  [384] = {.entry = {.count = 1, .reusable = true}}, SHIFT(94),
  [386] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [388] = {.entry = {.count = 1, .reusable = true}}, SHIFT(97),
  [390] = {.entry = {.count = 1, .reusable = true}}, SHIFT(69),
  [392] = {.entry = {.count = 1, .reusable = true}}, SHIFT(88),
  [394] = {.entry = {.count = 1, .reusable = true}}, SHIFT(67),
  [396] = {.entry = {.count = 1, .reusable = true}}, SHIFT(72),
  [398] = {.entry = {.count = 1, .reusable = true}}, SHIFT(87),
  [400] = {.entry = {.count = 1, .reusable = true}}, SHIFT(99),
  [402] = {.entry = {.count = 1, .reusable = true}}, SHIFT(100),
  [404] = {.entry = {.count = 1, .reusable = true}}, SHIFT(85),
  [406] = {.entry = {.count = 1, .reusable = true}}, SHIFT(76),
  [408] = {.entry = {.count = 1, .reusable = true}}, SHIFT(108),
  [410] = {.entry = {.count = 1, .reusable = true}}, SHIFT(73),
  [412] = {.entry = {.count = 1, .reusable = true}}, SHIFT(92),
  [414] = {.entry = {.count = 1, .reusable = true}}, SHIFT(96),
  [416] = {.entry = {.count = 1, .reusable = true}}, SHIFT(95),
  [418] = {.entry = {.count = 1, .reusable = true}}, SHIFT(79),
  [420] = {.entry = {.count = 1, .reusable = true}}, SHIFT(70),
  [422] = {.entry = {.count = 1, .reusable = true}}, SHIFT(115),
  [424] = {.entry = {.count = 1, .reusable = true}}, SHIFT(68),
  [426] = {.entry = {.count = 1, .reusable = true}}, SHIFT(117),
  [428] = {.entry = {.count = 1, .reusable = true}}, SHIFT(90),
  [430] = {.entry = {.count = 1, .reusable = true}}, SHIFT(102),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_pandoc_markdown_inline(void) {
  static const TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
