#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 122
#define LARGE_STATE_COUNT 39
#define SYMBOL_COUNT 30
#define ALIAS_COUNT 0
#define TOKEN_COUNT 14
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 3
#define MAX_ALIAS_SEQUENCE_LENGTH 6
#define PRODUCTION_ID_COUNT 5

enum ts_symbol_identifiers {
  anon_sym_STAR = 1,
  anon_sym__ = 2,
  anon_sym_STAR_STAR = 3,
  anon_sym___ = 4,
  anon_sym_BQUOTE = 5,
  aux_sym_code_span_token1 = 6,
  anon_sym_LBRACK = 7,
  anon_sym_RBRACK = 8,
  anon_sym_LPAREN = 9,
  anon_sym_RPAREN = 10,
  sym_link_destination = 11,
  aux_sym_text_token1 = 12,
  aux_sym_text_token2 = 13,
  sym_inline = 14,
  sym__inline_element = 15,
  sym_emphasis = 16,
  sym_strong_emphasis = 17,
  sym__inline_no_star = 18,
  sym__inline_no_underscore = 19,
  sym_code_span = 20,
  sym_link = 21,
  sym_link_text = 22,
  sym__link_text_element = 23,
  sym_text = 24,
  aux_sym_inline_repeat1 = 25,
  aux_sym_emphasis_repeat1 = 26,
  aux_sym_emphasis_repeat2 = 27,
  aux_sym_link_text_repeat1 = 28,
  aux_sym_text_repeat1 = 29,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_STAR] = "*",
  [anon_sym__] = "_",
  [anon_sym_STAR_STAR] = "**",
  [anon_sym___] = "__",
  [anon_sym_BQUOTE] = "`",
  [aux_sym_code_span_token1] = "code_span_content",
  [anon_sym_LBRACK] = "[",
  [anon_sym_RBRACK] = "]",
  [anon_sym_LPAREN] = "(",
  [anon_sym_RPAREN] = ")",
  [sym_link_destination] = "link_destination",
  [aux_sym_text_token1] = "text_token1",
  [aux_sym_text_token2] = "text_token2",
  [sym_inline] = "inline",
  [sym__inline_element] = "_inline_element",
  [sym_emphasis] = "emphasis",
  [sym_strong_emphasis] = "strong_emphasis",
  [sym__inline_no_star] = "_inline_no_star",
  [sym__inline_no_underscore] = "_inline_no_underscore",
  [sym_code_span] = "code_span",
  [sym_link] = "link",
  [sym_link_text] = "link_text",
  [sym__link_text_element] = "_link_text_element",
  [sym_text] = "text",
  [aux_sym_inline_repeat1] = "inline_repeat1",
  [aux_sym_emphasis_repeat1] = "emphasis_repeat1",
  [aux_sym_emphasis_repeat2] = "emphasis_repeat2",
  [aux_sym_link_text_repeat1] = "link_text_repeat1",
  [aux_sym_text_repeat1] = "text_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_STAR] = anon_sym_STAR,
  [anon_sym__] = anon_sym__,
  [anon_sym_STAR_STAR] = anon_sym_STAR_STAR,
  [anon_sym___] = anon_sym___,
  [anon_sym_BQUOTE] = anon_sym_BQUOTE,
  [aux_sym_code_span_token1] = aux_sym_code_span_token1,
  [anon_sym_LBRACK] = anon_sym_LBRACK,
  [anon_sym_RBRACK] = anon_sym_RBRACK,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [sym_link_destination] = sym_link_destination,
  [aux_sym_text_token1] = aux_sym_text_token1,
  [aux_sym_text_token2] = aux_sym_text_token2,
  [sym_inline] = sym_inline,
  [sym__inline_element] = sym__inline_element,
  [sym_emphasis] = sym_emphasis,
  [sym_strong_emphasis] = sym_strong_emphasis,
  [sym__inline_no_star] = sym__inline_no_star,
  [sym__inline_no_underscore] = sym__inline_no_underscore,
  [sym_code_span] = sym_code_span,
  [sym_link] = sym_link,
  [sym_link_text] = sym_link_text,
  [sym__link_text_element] = sym__link_text_element,
  [sym_text] = sym_text,
  [aux_sym_inline_repeat1] = aux_sym_inline_repeat1,
  [aux_sym_emphasis_repeat1] = aux_sym_emphasis_repeat1,
  [aux_sym_emphasis_repeat2] = aux_sym_emphasis_repeat2,
  [aux_sym_link_text_repeat1] = aux_sym_link_text_repeat1,
  [aux_sym_text_repeat1] = aux_sym_text_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_STAR] = {
    .visible = true,
    .named = false,
  },
  [anon_sym__] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_STAR_STAR] = {
    .visible = true,
    .named = false,
  },
  [anon_sym___] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_BQUOTE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_code_span_token1] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [sym_link_destination] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_text_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_text_token2] = {
    .visible = false,
    .named = false,
  },
  [sym_inline] = {
    .visible = true,
    .named = true,
  },
  [sym__inline_element] = {
    .visible = false,
    .named = true,
  },
  [sym_emphasis] = {
    .visible = true,
    .named = true,
  },
  [sym_strong_emphasis] = {
    .visible = true,
    .named = true,
  },
  [sym__inline_no_star] = {
    .visible = false,
    .named = true,
  },
  [sym__inline_no_underscore] = {
    .visible = false,
    .named = true,
  },
  [sym_code_span] = {
    .visible = true,
    .named = true,
  },
  [sym_link] = {
    .visible = true,
    .named = true,
  },
  [sym_link_text] = {
    .visible = true,
    .named = true,
  },
  [sym__link_text_element] = {
    .visible = false,
    .named = true,
  },
  [sym_text] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_inline_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_emphasis_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_emphasis_repeat2] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_link_text_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_text_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_content = 1,
  field_destination = 2,
  field_text = 3,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_content] = "content",
  [field_destination] = "destination",
  [field_text] = "text",
};

static const TSFieldMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 1},
  [2] = {.index = 1, .length = 1},
  [3] = {.index = 2, .length = 1},
  [4] = {.index = 3, .length = 2},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_content, 1},
  [1] =
    {field_destination, 3},
  [2] =
    {field_text, 1},
  [3] =
    {field_destination, 4},
    {field_text, 1},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 4,
  [7] = 5,
  [8] = 8,
  [9] = 9,
  [10] = 5,
  [11] = 8,
  [12] = 12,
  [13] = 13,
  [14] = 4,
  [15] = 3,
  [16] = 4,
  [17] = 5,
  [18] = 4,
  [19] = 5,
  [20] = 20,
  [21] = 9,
  [22] = 20,
  [23] = 9,
  [24] = 20,
  [25] = 9,
  [26] = 20,
  [27] = 9,
  [28] = 8,
  [29] = 12,
  [30] = 20,
  [31] = 12,
  [32] = 8,
  [33] = 12,
  [34] = 8,
  [35] = 12,
  [36] = 13,
  [37] = 13,
  [38] = 13,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 41,
  [44] = 42,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 47,
  [50] = 48,
  [51] = 51,
  [52] = 52,
  [53] = 51,
  [54] = 52,
  [55] = 55,
  [56] = 56,
  [57] = 57,
  [58] = 55,
  [59] = 59,
  [60] = 57,
  [61] = 61,
  [62] = 62,
  [63] = 56,
  [64] = 64,
  [65] = 52,
  [66] = 59,
  [67] = 62,
  [68] = 61,
  [69] = 64,
  [70] = 51,
  [71] = 52,
  [72] = 51,
  [73] = 64,
  [74] = 55,
  [75] = 61,
  [76] = 59,
  [77] = 55,
  [78] = 62,
  [79] = 57,
  [80] = 59,
  [81] = 62,
  [82] = 61,
  [83] = 64,
  [84] = 57,
  [85] = 85,
  [86] = 86,
  [87] = 87,
  [88] = 85,
  [89] = 86,
  [90] = 85,
  [91] = 87,
  [92] = 85,
  [93] = 87,
  [94] = 86,
  [95] = 87,
  [96] = 86,
  [97] = 97,
  [98] = 98,
  [99] = 99,
  [100] = 100,
  [101] = 101,
  [102] = 102,
  [103] = 99,
  [104] = 104,
  [105] = 97,
  [106] = 99,
  [107] = 101,
  [108] = 104,
  [109] = 97,
  [110] = 102,
  [111] = 101,
  [112] = 104,
  [113] = 104,
  [114] = 102,
  [115] = 101,
  [116] = 102,
  [117] = 98,
  [118] = 97,
  [119] = 98,
  [120] = 99,
  [121] = 98,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(7);
      if (lookahead == '(') ADVANCE(17);
      if (lookahead == ')') ADVANCE(18);
      if (lookahead == '*') ADVANCE(8);
      if (lookahead == '[') ADVANCE(15);
      if (lookahead == ']') ADVANCE(16);
      if (lookahead == '_') ADVANCE(9);
      if (lookahead == '`') ADVANCE(12);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      END_STATE();
    case 1:
      if (lookahead == ')') ADVANCE(18);
      if (lookahead == '\n' ||
          lookahead == '\r') SKIP(1);
      if (('\t' <= lookahead && lookahead <= '\f') ||
          lookahead == ' ') ADVANCE(19);
      if (lookahead != 0) ADVANCE(20);
      END_STATE();
    case 2:
      if (lookahead == '*') ADVANCE(8);
      if (lookahead == '[') ADVANCE(15);
      if (lookahead == '_') ADVANCE(24);
      if (lookahead == '`') ADVANCE(12);
      if (lookahead == '\n' ||
          lookahead == '\r') SKIP(2);
      if (('\t' <= lookahead && lookahead <= '\f') ||
          lookahead == ' ') ADVANCE(21);
      if (lookahead != 0 &&
          lookahead != ']') ADVANCE(22);
      END_STATE();
    case 3:
      if (lookahead == '*') ADVANCE(23);
      if (lookahead == '[') ADVANCE(15);
      if (lookahead == '_') ADVANCE(9);
      if (lookahead == '`') ADVANCE(12);
      if (lookahead == '\n' ||
          lookahead == '\r') SKIP(3);
      if (('\t' <= lookahead && lookahead <= '\f') ||
          lookahead == ' ') ADVANCE(21);
      if (lookahead != 0 &&
          lookahead != ']') ADVANCE(22);
      END_STATE();
    case 4:
      if (lookahead == '*') ADVANCE(23);
      if (lookahead == '[') ADVANCE(15);
      if (lookahead == '_') ADVANCE(24);
      if (lookahead == '`') ADVANCE(12);
      if (lookahead == '\n' ||
          lookahead == '\r') SKIP(4);
      if (('\t' <= lookahead && lookahead <= '\f') ||
          lookahead == ' ') ADVANCE(21);
      if (lookahead != 0 &&
          lookahead != ']') ADVANCE(22);
      END_STATE();
    case 5:
      if (lookahead == '`') ADVANCE(12);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(13);
      if (lookahead != 0) ADVANCE(14);
      END_STATE();
    case 6:
      if (eof) ADVANCE(7);
      if (lookahead == '*') ADVANCE(8);
      if (lookahead == '[') ADVANCE(15);
      if (lookahead == ']') ADVANCE(16);
      if (lookahead == '_') ADVANCE(9);
      if (lookahead == '`') ADVANCE(12);
      if (lookahead == '\n' ||
          lookahead == '\r') SKIP(6);
      if (('\t' <= lookahead && lookahead <= '\f') ||
          lookahead == ' ') ADVANCE(21);
      if (lookahead != 0) ADVANCE(22);
      END_STATE();
    case 7:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 8:
      ACCEPT_TOKEN(anon_sym_STAR);
      if (lookahead == '*') ADVANCE(10);
      END_STATE();
    case 9:
      ACCEPT_TOKEN(anon_sym__);
      if (lookahead == '_') ADVANCE(11);
      END_STATE();
    case 10:
      ACCEPT_TOKEN(anon_sym_STAR_STAR);
      END_STATE();
    case 11:
      ACCEPT_TOKEN(anon_sym___);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(anon_sym_BQUOTE);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(aux_sym_code_span_token1);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(13);
      if (lookahead != 0 &&
          lookahead != '`') ADVANCE(14);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(aux_sym_code_span_token1);
      if (lookahead != 0 &&
          lookahead != '`') ADVANCE(14);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(sym_link_destination);
      if (lookahead == '\t' ||
          lookahead == 0x0b ||
          lookahead == '\f' ||
          lookahead == ' ') ADVANCE(19);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ')') ADVANCE(20);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(sym_link_destination);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != ')') ADVANCE(20);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(aux_sym_text_token1);
      if (lookahead == '\t' ||
          lookahead == 0x0b ||
          lookahead == '\f' ||
          lookahead == ' ') ADVANCE(21);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != '*' &&
          lookahead != '[' &&
          lookahead != ']' &&
          lookahead != '_' &&
          lookahead != '`') ADVANCE(22);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(aux_sym_text_token1);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '*' &&
          lookahead != '[' &&
          lookahead != ']' &&
          lookahead != '_' &&
          lookahead != '`') ADVANCE(22);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(aux_sym_text_token2);
      if (lookahead == '*') ADVANCE(10);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(aux_sym_text_token2);
      if (lookahead == '_') ADVANCE(11);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 6},
  [2] = {.lex_state = 6},
  [3] = {.lex_state = 6},
  [4] = {.lex_state = 6},
  [5] = {.lex_state = 6},
  [6] = {.lex_state = 6},
  [7] = {.lex_state = 6},
  [8] = {.lex_state = 6},
  [9] = {.lex_state = 6},
  [10] = {.lex_state = 6},
  [11] = {.lex_state = 6},
  [12] = {.lex_state = 6},
  [13] = {.lex_state = 6},
  [14] = {.lex_state = 6},
  [15] = {.lex_state = 6},
  [16] = {.lex_state = 6},
  [17] = {.lex_state = 6},
  [18] = {.lex_state = 6},
  [19] = {.lex_state = 6},
  [20] = {.lex_state = 6},
  [21] = {.lex_state = 6},
  [22] = {.lex_state = 6},
  [23] = {.lex_state = 6},
  [24] = {.lex_state = 6},
  [25] = {.lex_state = 6},
  [26] = {.lex_state = 6},
  [27] = {.lex_state = 6},
  [28] = {.lex_state = 6},
  [29] = {.lex_state = 6},
  [30] = {.lex_state = 6},
  [31] = {.lex_state = 6},
  [32] = {.lex_state = 6},
  [33] = {.lex_state = 6},
  [34] = {.lex_state = 6},
  [35] = {.lex_state = 6},
  [36] = {.lex_state = 6},
  [37] = {.lex_state = 6},
  [38] = {.lex_state = 6},
  [39] = {.lex_state = 6},
  [40] = {.lex_state = 6},
  [41] = {.lex_state = 3},
  [42] = {.lex_state = 2},
  [43] = {.lex_state = 3},
  [44] = {.lex_state = 2},
  [45] = {.lex_state = 2},
  [46] = {.lex_state = 3},
  [47] = {.lex_state = 4},
  [48] = {.lex_state = 4},
  [49] = {.lex_state = 4},
  [50] = {.lex_state = 4},
  [51] = {.lex_state = 6},
  [52] = {.lex_state = 6},
  [53] = {.lex_state = 6},
  [54] = {.lex_state = 6},
  [55] = {.lex_state = 6},
  [56] = {.lex_state = 6},
  [57] = {.lex_state = 6},
  [58] = {.lex_state = 6},
  [59] = {.lex_state = 6},
  [60] = {.lex_state = 6},
  [61] = {.lex_state = 6},
  [62] = {.lex_state = 6},
  [63] = {.lex_state = 6},
  [64] = {.lex_state = 6},
  [65] = {.lex_state = 3},
  [66] = {.lex_state = 6},
  [67] = {.lex_state = 6},
  [68] = {.lex_state = 6},
  [69] = {.lex_state = 6},
  [70] = {.lex_state = 2},
  [71] = {.lex_state = 2},
  [72] = {.lex_state = 3},
  [73] = {.lex_state = 3},
  [74] = {.lex_state = 3},
  [75] = {.lex_state = 3},
  [76] = {.lex_state = 3},
  [77] = {.lex_state = 2},
  [78] = {.lex_state = 3},
  [79] = {.lex_state = 2},
  [80] = {.lex_state = 2},
  [81] = {.lex_state = 2},
  [82] = {.lex_state = 2},
  [83] = {.lex_state = 2},
  [84] = {.lex_state = 3},
  [85] = {.lex_state = 1},
  [86] = {.lex_state = 1},
  [87] = {.lex_state = 5},
  [88] = {.lex_state = 1},
  [89] = {.lex_state = 1},
  [90] = {.lex_state = 1},
  [91] = {.lex_state = 5},
  [92] = {.lex_state = 1},
  [93] = {.lex_state = 5},
  [94] = {.lex_state = 1},
  [95] = {.lex_state = 5},
  [96] = {.lex_state = 1},
  [97] = {.lex_state = 0},
  [98] = {.lex_state = 0},
  [99] = {.lex_state = 0},
  [100] = {.lex_state = 0},
  [101] = {.lex_state = 0},
  [102] = {.lex_state = 0},
  [103] = {.lex_state = 0},
  [104] = {.lex_state = 0},
  [105] = {.lex_state = 0},
  [106] = {.lex_state = 0},
  [107] = {.lex_state = 0},
  [108] = {.lex_state = 0},
  [109] = {.lex_state = 0},
  [110] = {.lex_state = 0},
  [111] = {.lex_state = 0},
  [112] = {.lex_state = 0},
  [113] = {.lex_state = 0},
  [114] = {.lex_state = 0},
  [115] = {.lex_state = 0},
  [116] = {.lex_state = 0},
  [117] = {.lex_state = 0},
  [118] = {.lex_state = 0},
  [119] = {.lex_state = 0},
  [120] = {.lex_state = 0},
  [121] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_STAR] = ACTIONS(1),
    [anon_sym__] = ACTIONS(1),
    [anon_sym_STAR_STAR] = ACTIONS(1),
    [anon_sym___] = ACTIONS(1),
    [anon_sym_BQUOTE] = ACTIONS(1),
    [anon_sym_LBRACK] = ACTIONS(1),
    [anon_sym_RBRACK] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [aux_sym_text_token2] = ACTIONS(1),
  },
  [1] = {
    [sym_inline] = STATE(100),
    [sym__inline_element] = STATE(2),
    [sym_emphasis] = STATE(2),
    [sym_strong_emphasis] = STATE(2),
    [sym_code_span] = STATE(2),
    [sym_link] = STATE(2),
    [sym_text] = STATE(2),
    [aux_sym_inline_repeat1] = STATE(2),
    [aux_sym_text_repeat1] = STATE(53),
    [anon_sym_STAR] = ACTIONS(3),
    [anon_sym__] = ACTIONS(5),
    [anon_sym_STAR_STAR] = ACTIONS(7),
    [anon_sym___] = ACTIONS(9),
    [anon_sym_BQUOTE] = ACTIONS(11),
    [anon_sym_LBRACK] = ACTIONS(13),
    [aux_sym_text_token1] = ACTIONS(15),
    [aux_sym_text_token2] = ACTIONS(17),
  },
  [2] = {
    [sym__inline_element] = STATE(3),
    [sym_emphasis] = STATE(3),
    [sym_strong_emphasis] = STATE(3),
    [sym_code_span] = STATE(3),
    [sym_link] = STATE(3),
    [sym_text] = STATE(3),
    [aux_sym_inline_repeat1] = STATE(3),
    [aux_sym_text_repeat1] = STATE(53),
    [ts_builtin_sym_end] = ACTIONS(19),
    [anon_sym_STAR] = ACTIONS(3),
    [anon_sym__] = ACTIONS(5),
    [anon_sym_STAR_STAR] = ACTIONS(7),
    [anon_sym___] = ACTIONS(9),
    [anon_sym_BQUOTE] = ACTIONS(11),
    [anon_sym_LBRACK] = ACTIONS(13),
    [aux_sym_text_token1] = ACTIONS(15),
    [aux_sym_text_token2] = ACTIONS(17),
  },
  [3] = {
    [sym__inline_element] = STATE(3),
    [sym_emphasis] = STATE(3),
    [sym_strong_emphasis] = STATE(3),
    [sym_code_span] = STATE(3),
    [sym_link] = STATE(3),
    [sym_text] = STATE(3),
    [aux_sym_inline_repeat1] = STATE(3),
    [aux_sym_text_repeat1] = STATE(53),
    [ts_builtin_sym_end] = ACTIONS(21),
    [anon_sym_STAR] = ACTIONS(23),
    [anon_sym__] = ACTIONS(26),
    [anon_sym_STAR_STAR] = ACTIONS(29),
    [anon_sym___] = ACTIONS(32),
    [anon_sym_BQUOTE] = ACTIONS(35),
    [anon_sym_LBRACK] = ACTIONS(38),
    [aux_sym_text_token1] = ACTIONS(41),
    [aux_sym_text_token2] = ACTIONS(44),
  },
  [4] = {
    [sym__inline_element] = STATE(24),
    [sym_emphasis] = STATE(24),
    [sym_strong_emphasis] = STATE(24),
    [sym_code_span] = STATE(24),
    [sym_link] = STATE(24),
    [sym_text] = STATE(24),
    [aux_sym_inline_repeat1] = STATE(24),
    [aux_sym_text_repeat1] = STATE(51),
    [ts_builtin_sym_end] = ACTIONS(47),
    [anon_sym_STAR] = ACTIONS(49),
    [anon_sym__] = ACTIONS(49),
    [anon_sym_STAR_STAR] = ACTIONS(49),
    [anon_sym___] = ACTIONS(49),
    [anon_sym_BQUOTE] = ACTIONS(49),
    [anon_sym_LBRACK] = ACTIONS(49),
    [aux_sym_text_token1] = ACTIONS(47),
    [aux_sym_text_token2] = ACTIONS(49),
  },
  [5] = {
    [sym__inline_element] = STATE(25),
    [sym_emphasis] = STATE(25),
    [sym_strong_emphasis] = STATE(25),
    [sym_code_span] = STATE(25),
    [sym_link] = STATE(25),
    [sym_text] = STATE(25),
    [aux_sym_inline_repeat1] = STATE(25),
    [aux_sym_text_repeat1] = STATE(51),
    [ts_builtin_sym_end] = ACTIONS(47),
    [anon_sym_STAR] = ACTIONS(49),
    [anon_sym__] = ACTIONS(49),
    [anon_sym_STAR_STAR] = ACTIONS(49),
    [anon_sym___] = ACTIONS(49),
    [anon_sym_BQUOTE] = ACTIONS(49),
    [anon_sym_LBRACK] = ACTIONS(49),
    [aux_sym_text_token1] = ACTIONS(47),
    [aux_sym_text_token2] = ACTIONS(49),
  },
  [6] = {
    [sym__inline_element] = STATE(24),
    [sym_emphasis] = STATE(24),
    [sym_strong_emphasis] = STATE(24),
    [sym_code_span] = STATE(24),
    [sym_link] = STATE(24),
    [sym_text] = STATE(24),
    [aux_sym_inline_repeat1] = STATE(24),
    [aux_sym_text_repeat1] = STATE(51),
    [anon_sym_STAR] = ACTIONS(49),
    [anon_sym__] = ACTIONS(49),
    [anon_sym_STAR_STAR] = ACTIONS(49),
    [anon_sym___] = ACTIONS(49),
    [anon_sym_BQUOTE] = ACTIONS(49),
    [anon_sym_LBRACK] = ACTIONS(51),
    [anon_sym_RBRACK] = ACTIONS(49),
    [aux_sym_text_token1] = ACTIONS(47),
    [aux_sym_text_token2] = ACTIONS(49),
  },
  [7] = {
    [sym__inline_element] = STATE(25),
    [sym_emphasis] = STATE(25),
    [sym_strong_emphasis] = STATE(25),
    [sym_code_span] = STATE(25),
    [sym_link] = STATE(25),
    [sym_text] = STATE(25),
    [aux_sym_inline_repeat1] = STATE(25),
    [aux_sym_text_repeat1] = STATE(51),
    [anon_sym_STAR] = ACTIONS(49),
    [anon_sym__] = ACTIONS(49),
    [anon_sym_STAR_STAR] = ACTIONS(49),
    [anon_sym___] = ACTIONS(49),
    [anon_sym_BQUOTE] = ACTIONS(49),
    [anon_sym_LBRACK] = ACTIONS(51),
    [anon_sym_RBRACK] = ACTIONS(49),
    [aux_sym_text_token1] = ACTIONS(47),
    [aux_sym_text_token2] = ACTIONS(49),
  },
  [8] = {
    [sym__inline_element] = STATE(22),
    [sym_emphasis] = STATE(22),
    [sym_strong_emphasis] = STATE(22),
    [sym_code_span] = STATE(22),
    [sym_link] = STATE(22),
    [sym_text] = STATE(22),
    [aux_sym_inline_repeat1] = STATE(22),
    [aux_sym_text_repeat1] = STATE(51),
    [anon_sym_STAR] = ACTIONS(53),
    [anon_sym__] = ACTIONS(55),
    [anon_sym_STAR_STAR] = ACTIONS(57),
    [anon_sym___] = ACTIONS(59),
    [anon_sym_BQUOTE] = ACTIONS(61),
    [anon_sym_LBRACK] = ACTIONS(51),
    [aux_sym_text_token1] = ACTIONS(63),
    [aux_sym_text_token2] = ACTIONS(65),
  },
  [9] = {
    [sym__inline_element] = STATE(15),
    [sym_emphasis] = STATE(15),
    [sym_strong_emphasis] = STATE(15),
    [sym_code_span] = STATE(15),
    [sym_link] = STATE(15),
    [sym_text] = STATE(15),
    [aux_sym_inline_repeat1] = STATE(15),
    [aux_sym_text_repeat1] = STATE(51),
    [anon_sym_STAR] = ACTIONS(53),
    [anon_sym__] = ACTIONS(55),
    [anon_sym_STAR_STAR] = ACTIONS(57),
    [anon_sym___] = ACTIONS(67),
    [anon_sym_BQUOTE] = ACTIONS(61),
    [anon_sym_LBRACK] = ACTIONS(51),
    [aux_sym_text_token1] = ACTIONS(63),
    [aux_sym_text_token2] = ACTIONS(65),
  },
  [10] = {
    [sym__inline_element] = STATE(25),
    [sym_emphasis] = STATE(25),
    [sym_strong_emphasis] = STATE(25),
    [sym_code_span] = STATE(25),
    [sym_link] = STATE(25),
    [sym_text] = STATE(25),
    [aux_sym_inline_repeat1] = STATE(25),
    [aux_sym_text_repeat1] = STATE(51),
    [anon_sym_STAR] = ACTIONS(53),
    [anon_sym__] = ACTIONS(49),
    [anon_sym_STAR_STAR] = ACTIONS(49),
    [anon_sym___] = ACTIONS(49),
    [anon_sym_BQUOTE] = ACTIONS(49),
    [anon_sym_LBRACK] = ACTIONS(49),
    [aux_sym_text_token1] = ACTIONS(47),
    [aux_sym_text_token2] = ACTIONS(49),
  },
  [11] = {
    [sym__inline_element] = STATE(30),
    [sym_emphasis] = STATE(30),
    [sym_strong_emphasis] = STATE(30),
    [sym_code_span] = STATE(30),
    [sym_link] = STATE(30),
    [sym_text] = STATE(30),
    [aux_sym_inline_repeat1] = STATE(30),
    [aux_sym_text_repeat1] = STATE(51),
    [anon_sym_STAR] = ACTIONS(53),
    [anon_sym__] = ACTIONS(55),
    [anon_sym_STAR_STAR] = ACTIONS(57),
    [anon_sym___] = ACTIONS(59),
    [anon_sym_BQUOTE] = ACTIONS(61),
    [anon_sym_LBRACK] = ACTIONS(51),
    [aux_sym_text_token1] = ACTIONS(63),
    [aux_sym_text_token2] = ACTIONS(65),
  },
  [12] = {
    [sym__inline_element] = STATE(9),
    [sym_emphasis] = STATE(9),
    [sym_strong_emphasis] = STATE(9),
    [sym_code_span] = STATE(9),
    [sym_link] = STATE(9),
    [sym_text] = STATE(9),
    [aux_sym_inline_repeat1] = STATE(9),
    [aux_sym_text_repeat1] = STATE(51),
    [anon_sym_STAR] = ACTIONS(53),
    [anon_sym__] = ACTIONS(55),
    [anon_sym_STAR_STAR] = ACTIONS(57),
    [anon_sym___] = ACTIONS(59),
    [anon_sym_BQUOTE] = ACTIONS(61),
    [anon_sym_LBRACK] = ACTIONS(51),
    [aux_sym_text_token1] = ACTIONS(63),
    [aux_sym_text_token2] = ACTIONS(65),
  },
  [13] = {
    [sym_emphasis] = STATE(39),
    [sym_strong_emphasis] = STATE(39),
    [sym_code_span] = STATE(39),
    [sym_link_text] = STATE(98),
    [sym__link_text_element] = STATE(39),
    [sym_text] = STATE(39),
    [aux_sym_link_text_repeat1] = STATE(39),
    [aux_sym_text_repeat1] = STATE(51),
    [anon_sym_STAR] = ACTIONS(53),
    [anon_sym__] = ACTIONS(55),
    [anon_sym_STAR_STAR] = ACTIONS(69),
    [anon_sym___] = ACTIONS(71),
    [anon_sym_BQUOTE] = ACTIONS(61),
    [anon_sym_RBRACK] = ACTIONS(73),
    [aux_sym_text_token1] = ACTIONS(63),
    [aux_sym_text_token2] = ACTIONS(65),
  },
  [14] = {
    [sym__inline_element] = STATE(24),
    [sym_emphasis] = STATE(24),
    [sym_strong_emphasis] = STATE(24),
    [sym_code_span] = STATE(24),
    [sym_link] = STATE(24),
    [sym_text] = STATE(24),
    [aux_sym_inline_repeat1] = STATE(24),
    [aux_sym_text_repeat1] = STATE(51),
    [anon_sym_STAR] = ACTIONS(49),
    [anon_sym__] = ACTIONS(49),
    [anon_sym_STAR_STAR] = ACTIONS(49),
    [anon_sym___] = ACTIONS(49),
    [anon_sym_BQUOTE] = ACTIONS(49),
    [anon_sym_LBRACK] = ACTIONS(49),
    [aux_sym_text_token1] = ACTIONS(47),
    [aux_sym_text_token2] = ACTIONS(49),
  },
  [15] = {
    [sym__inline_element] = STATE(15),
    [sym_emphasis] = STATE(15),
    [sym_strong_emphasis] = STATE(15),
    [sym_code_span] = STATE(15),
    [sym_link] = STATE(15),
    [sym_text] = STATE(15),
    [aux_sym_inline_repeat1] = STATE(15),
    [aux_sym_text_repeat1] = STATE(51),
    [anon_sym_STAR] = ACTIONS(75),
    [anon_sym__] = ACTIONS(78),
    [anon_sym_STAR_STAR] = ACTIONS(81),
    [anon_sym___] = ACTIONS(84),
    [anon_sym_BQUOTE] = ACTIONS(87),
    [anon_sym_LBRACK] = ACTIONS(90),
    [aux_sym_text_token1] = ACTIONS(93),
    [aux_sym_text_token2] = ACTIONS(96),
  },
  [16] = {
    [sym__inline_element] = STATE(24),
    [sym_emphasis] = STATE(24),
    [sym_strong_emphasis] = STATE(24),
    [sym_code_span] = STATE(24),
    [sym_link] = STATE(24),
    [sym_text] = STATE(24),
    [aux_sym_inline_repeat1] = STATE(24),
    [aux_sym_text_repeat1] = STATE(51),
    [anon_sym_STAR] = ACTIONS(49),
    [anon_sym__] = ACTIONS(55),
    [anon_sym_STAR_STAR] = ACTIONS(49),
    [anon_sym___] = ACTIONS(49),
    [anon_sym_BQUOTE] = ACTIONS(49),
    [anon_sym_LBRACK] = ACTIONS(49),
    [aux_sym_text_token1] = ACTIONS(47),
    [aux_sym_text_token2] = ACTIONS(49),
  },
  [17] = {
    [sym__inline_element] = STATE(25),
    [sym_emphasis] = STATE(25),
    [sym_strong_emphasis] = STATE(25),
    [sym_code_span] = STATE(25),
    [sym_link] = STATE(25),
    [sym_text] = STATE(25),
    [aux_sym_inline_repeat1] = STATE(25),
    [aux_sym_text_repeat1] = STATE(51),
    [anon_sym_STAR] = ACTIONS(49),
    [anon_sym__] = ACTIONS(55),
    [anon_sym_STAR_STAR] = ACTIONS(49),
    [anon_sym___] = ACTIONS(49),
    [anon_sym_BQUOTE] = ACTIONS(49),
    [anon_sym_LBRACK] = ACTIONS(49),
    [aux_sym_text_token1] = ACTIONS(47),
    [aux_sym_text_token2] = ACTIONS(49),
  },
  [18] = {
    [sym__inline_element] = STATE(24),
    [sym_emphasis] = STATE(24),
    [sym_strong_emphasis] = STATE(24),
    [sym_code_span] = STATE(24),
    [sym_link] = STATE(24),
    [sym_text] = STATE(24),
    [aux_sym_inline_repeat1] = STATE(24),
    [aux_sym_text_repeat1] = STATE(51),
    [anon_sym_STAR] = ACTIONS(53),
    [anon_sym__] = ACTIONS(49),
    [anon_sym_STAR_STAR] = ACTIONS(49),
    [anon_sym___] = ACTIONS(49),
    [anon_sym_BQUOTE] = ACTIONS(49),
    [anon_sym_LBRACK] = ACTIONS(49),
    [aux_sym_text_token1] = ACTIONS(47),
    [aux_sym_text_token2] = ACTIONS(49),
  },
  [19] = {
    [sym__inline_element] = STATE(25),
    [sym_emphasis] = STATE(25),
    [sym_strong_emphasis] = STATE(25),
    [sym_code_span] = STATE(25),
    [sym_link] = STATE(25),
    [sym_text] = STATE(25),
    [aux_sym_inline_repeat1] = STATE(25),
    [aux_sym_text_repeat1] = STATE(51),
    [anon_sym_STAR] = ACTIONS(49),
    [anon_sym__] = ACTIONS(49),
    [anon_sym_STAR_STAR] = ACTIONS(49),
    [anon_sym___] = ACTIONS(49),
    [anon_sym_BQUOTE] = ACTIONS(49),
    [anon_sym_LBRACK] = ACTIONS(49),
    [aux_sym_text_token1] = ACTIONS(47),
    [aux_sym_text_token2] = ACTIONS(49),
  },
  [20] = {
    [sym__inline_element] = STATE(15),
    [sym_emphasis] = STATE(15),
    [sym_strong_emphasis] = STATE(15),
    [sym_code_span] = STATE(15),
    [sym_link] = STATE(15),
    [sym_text] = STATE(15),
    [aux_sym_inline_repeat1] = STATE(15),
    [aux_sym_text_repeat1] = STATE(51),
    [anon_sym_STAR] = ACTIONS(53),
    [anon_sym__] = ACTIONS(55),
    [anon_sym_STAR_STAR] = ACTIONS(99),
    [anon_sym___] = ACTIONS(59),
    [anon_sym_BQUOTE] = ACTIONS(61),
    [anon_sym_LBRACK] = ACTIONS(51),
    [aux_sym_text_token1] = ACTIONS(63),
    [aux_sym_text_token2] = ACTIONS(65),
  },
  [21] = {
    [sym__inline_element] = STATE(15),
    [sym_emphasis] = STATE(15),
    [sym_strong_emphasis] = STATE(15),
    [sym_code_span] = STATE(15),
    [sym_link] = STATE(15),
    [sym_text] = STATE(15),
    [aux_sym_inline_repeat1] = STATE(15),
    [aux_sym_text_repeat1] = STATE(51),
    [anon_sym_STAR] = ACTIONS(53),
    [anon_sym__] = ACTIONS(55),
    [anon_sym_STAR_STAR] = ACTIONS(57),
    [anon_sym___] = ACTIONS(101),
    [anon_sym_BQUOTE] = ACTIONS(61),
    [anon_sym_LBRACK] = ACTIONS(51),
    [aux_sym_text_token1] = ACTIONS(63),
    [aux_sym_text_token2] = ACTIONS(65),
  },
  [22] = {
    [sym__inline_element] = STATE(15),
    [sym_emphasis] = STATE(15),
    [sym_strong_emphasis] = STATE(15),
    [sym_code_span] = STATE(15),
    [sym_link] = STATE(15),
    [sym_text] = STATE(15),
    [aux_sym_inline_repeat1] = STATE(15),
    [aux_sym_text_repeat1] = STATE(51),
    [anon_sym_STAR] = ACTIONS(53),
    [anon_sym__] = ACTIONS(55),
    [anon_sym_STAR_STAR] = ACTIONS(103),
    [anon_sym___] = ACTIONS(59),
    [anon_sym_BQUOTE] = ACTIONS(61),
    [anon_sym_LBRACK] = ACTIONS(51),
    [aux_sym_text_token1] = ACTIONS(63),
    [aux_sym_text_token2] = ACTIONS(65),
  },
  [23] = {
    [sym__inline_element] = STATE(15),
    [sym_emphasis] = STATE(15),
    [sym_strong_emphasis] = STATE(15),
    [sym_code_span] = STATE(15),
    [sym_link] = STATE(15),
    [sym_text] = STATE(15),
    [aux_sym_inline_repeat1] = STATE(15),
    [aux_sym_text_repeat1] = STATE(51),
    [anon_sym_STAR] = ACTIONS(53),
    [anon_sym__] = ACTIONS(55),
    [anon_sym_STAR_STAR] = ACTIONS(57),
    [anon_sym___] = ACTIONS(105),
    [anon_sym_BQUOTE] = ACTIONS(61),
    [anon_sym_LBRACK] = ACTIONS(51),
    [aux_sym_text_token1] = ACTIONS(63),
    [aux_sym_text_token2] = ACTIONS(65),
  },
  [24] = {
    [sym__inline_element] = STATE(15),
    [sym_emphasis] = STATE(15),
    [sym_strong_emphasis] = STATE(15),
    [sym_code_span] = STATE(15),
    [sym_link] = STATE(15),
    [sym_text] = STATE(15),
    [aux_sym_inline_repeat1] = STATE(15),
    [aux_sym_text_repeat1] = STATE(51),
    [anon_sym_STAR] = ACTIONS(53),
    [anon_sym__] = ACTIONS(55),
    [anon_sym_STAR_STAR] = ACTIONS(107),
    [anon_sym___] = ACTIONS(59),
    [anon_sym_BQUOTE] = ACTIONS(61),
    [anon_sym_LBRACK] = ACTIONS(51),
    [aux_sym_text_token1] = ACTIONS(63),
    [aux_sym_text_token2] = ACTIONS(65),
  },
  [25] = {
    [sym__inline_element] = STATE(15),
    [sym_emphasis] = STATE(15),
    [sym_strong_emphasis] = STATE(15),
    [sym_code_span] = STATE(15),
    [sym_link] = STATE(15),
    [sym_text] = STATE(15),
    [aux_sym_inline_repeat1] = STATE(15),
    [aux_sym_text_repeat1] = STATE(51),
    [anon_sym_STAR] = ACTIONS(53),
    [anon_sym__] = ACTIONS(55),
    [anon_sym_STAR_STAR] = ACTIONS(57),
    [anon_sym___] = ACTIONS(109),
    [anon_sym_BQUOTE] = ACTIONS(61),
    [anon_sym_LBRACK] = ACTIONS(51),
    [aux_sym_text_token1] = ACTIONS(63),
    [aux_sym_text_token2] = ACTIONS(65),
  },
  [26] = {
    [sym__inline_element] = STATE(15),
    [sym_emphasis] = STATE(15),
    [sym_strong_emphasis] = STATE(15),
    [sym_code_span] = STATE(15),
    [sym_link] = STATE(15),
    [sym_text] = STATE(15),
    [aux_sym_inline_repeat1] = STATE(15),
    [aux_sym_text_repeat1] = STATE(51),
    [anon_sym_STAR] = ACTIONS(53),
    [anon_sym__] = ACTIONS(55),
    [anon_sym_STAR_STAR] = ACTIONS(111),
    [anon_sym___] = ACTIONS(59),
    [anon_sym_BQUOTE] = ACTIONS(61),
    [anon_sym_LBRACK] = ACTIONS(51),
    [aux_sym_text_token1] = ACTIONS(63),
    [aux_sym_text_token2] = ACTIONS(65),
  },
  [27] = {
    [sym__inline_element] = STATE(15),
    [sym_emphasis] = STATE(15),
    [sym_strong_emphasis] = STATE(15),
    [sym_code_span] = STATE(15),
    [sym_link] = STATE(15),
    [sym_text] = STATE(15),
    [aux_sym_inline_repeat1] = STATE(15),
    [aux_sym_text_repeat1] = STATE(51),
    [anon_sym_STAR] = ACTIONS(53),
    [anon_sym__] = ACTIONS(55),
    [anon_sym_STAR_STAR] = ACTIONS(57),
    [anon_sym___] = ACTIONS(113),
    [anon_sym_BQUOTE] = ACTIONS(61),
    [anon_sym_LBRACK] = ACTIONS(51),
    [aux_sym_text_token1] = ACTIONS(63),
    [aux_sym_text_token2] = ACTIONS(65),
  },
  [28] = {
    [sym__inline_element] = STATE(20),
    [sym_emphasis] = STATE(20),
    [sym_strong_emphasis] = STATE(20),
    [sym_code_span] = STATE(20),
    [sym_link] = STATE(20),
    [sym_text] = STATE(20),
    [aux_sym_inline_repeat1] = STATE(20),
    [aux_sym_text_repeat1] = STATE(51),
    [anon_sym_STAR] = ACTIONS(53),
    [anon_sym__] = ACTIONS(55),
    [anon_sym_STAR_STAR] = ACTIONS(57),
    [anon_sym___] = ACTIONS(59),
    [anon_sym_BQUOTE] = ACTIONS(61),
    [anon_sym_LBRACK] = ACTIONS(51),
    [aux_sym_text_token1] = ACTIONS(63),
    [aux_sym_text_token2] = ACTIONS(65),
  },
  [29] = {
    [sym__inline_element] = STATE(21),
    [sym_emphasis] = STATE(21),
    [sym_strong_emphasis] = STATE(21),
    [sym_code_span] = STATE(21),
    [sym_link] = STATE(21),
    [sym_text] = STATE(21),
    [aux_sym_inline_repeat1] = STATE(21),
    [aux_sym_text_repeat1] = STATE(51),
    [anon_sym_STAR] = ACTIONS(53),
    [anon_sym__] = ACTIONS(55),
    [anon_sym_STAR_STAR] = ACTIONS(57),
    [anon_sym___] = ACTIONS(59),
    [anon_sym_BQUOTE] = ACTIONS(61),
    [anon_sym_LBRACK] = ACTIONS(51),
    [aux_sym_text_token1] = ACTIONS(63),
    [aux_sym_text_token2] = ACTIONS(65),
  },
  [30] = {
    [sym__inline_element] = STATE(15),
    [sym_emphasis] = STATE(15),
    [sym_strong_emphasis] = STATE(15),
    [sym_code_span] = STATE(15),
    [sym_link] = STATE(15),
    [sym_text] = STATE(15),
    [aux_sym_inline_repeat1] = STATE(15),
    [aux_sym_text_repeat1] = STATE(51),
    [anon_sym_STAR] = ACTIONS(53),
    [anon_sym__] = ACTIONS(55),
    [anon_sym_STAR_STAR] = ACTIONS(115),
    [anon_sym___] = ACTIONS(59),
    [anon_sym_BQUOTE] = ACTIONS(61),
    [anon_sym_LBRACK] = ACTIONS(51),
    [aux_sym_text_token1] = ACTIONS(63),
    [aux_sym_text_token2] = ACTIONS(65),
  },
  [31] = {
    [sym__inline_element] = STATE(23),
    [sym_emphasis] = STATE(23),
    [sym_strong_emphasis] = STATE(23),
    [sym_code_span] = STATE(23),
    [sym_link] = STATE(23),
    [sym_text] = STATE(23),
    [aux_sym_inline_repeat1] = STATE(23),
    [aux_sym_text_repeat1] = STATE(51),
    [anon_sym_STAR] = ACTIONS(53),
    [anon_sym__] = ACTIONS(55),
    [anon_sym_STAR_STAR] = ACTIONS(57),
    [anon_sym___] = ACTIONS(59),
    [anon_sym_BQUOTE] = ACTIONS(61),
    [anon_sym_LBRACK] = ACTIONS(51),
    [aux_sym_text_token1] = ACTIONS(63),
    [aux_sym_text_token2] = ACTIONS(65),
  },
  [32] = {
    [sym__inline_element] = STATE(24),
    [sym_emphasis] = STATE(24),
    [sym_strong_emphasis] = STATE(24),
    [sym_code_span] = STATE(24),
    [sym_link] = STATE(24),
    [sym_text] = STATE(24),
    [aux_sym_inline_repeat1] = STATE(24),
    [aux_sym_text_repeat1] = STATE(51),
    [anon_sym_STAR] = ACTIONS(53),
    [anon_sym__] = ACTIONS(55),
    [anon_sym_STAR_STAR] = ACTIONS(57),
    [anon_sym___] = ACTIONS(59),
    [anon_sym_BQUOTE] = ACTIONS(61),
    [anon_sym_LBRACK] = ACTIONS(51),
    [aux_sym_text_token1] = ACTIONS(63),
    [aux_sym_text_token2] = ACTIONS(65),
  },
  [33] = {
    [sym__inline_element] = STATE(25),
    [sym_emphasis] = STATE(25),
    [sym_strong_emphasis] = STATE(25),
    [sym_code_span] = STATE(25),
    [sym_link] = STATE(25),
    [sym_text] = STATE(25),
    [aux_sym_inline_repeat1] = STATE(25),
    [aux_sym_text_repeat1] = STATE(51),
    [anon_sym_STAR] = ACTIONS(53),
    [anon_sym__] = ACTIONS(55),
    [anon_sym_STAR_STAR] = ACTIONS(57),
    [anon_sym___] = ACTIONS(59),
    [anon_sym_BQUOTE] = ACTIONS(61),
    [anon_sym_LBRACK] = ACTIONS(51),
    [aux_sym_text_token1] = ACTIONS(63),
    [aux_sym_text_token2] = ACTIONS(65),
  },
  [34] = {
    [sym__inline_element] = STATE(26),
    [sym_emphasis] = STATE(26),
    [sym_strong_emphasis] = STATE(26),
    [sym_code_span] = STATE(26),
    [sym_link] = STATE(26),
    [sym_text] = STATE(26),
    [aux_sym_inline_repeat1] = STATE(26),
    [aux_sym_text_repeat1] = STATE(51),
    [anon_sym_STAR] = ACTIONS(53),
    [anon_sym__] = ACTIONS(55),
    [anon_sym_STAR_STAR] = ACTIONS(57),
    [anon_sym___] = ACTIONS(59),
    [anon_sym_BQUOTE] = ACTIONS(61),
    [anon_sym_LBRACK] = ACTIONS(51),
    [aux_sym_text_token1] = ACTIONS(63),
    [aux_sym_text_token2] = ACTIONS(65),
  },
  [35] = {
    [sym__inline_element] = STATE(27),
    [sym_emphasis] = STATE(27),
    [sym_strong_emphasis] = STATE(27),
    [sym_code_span] = STATE(27),
    [sym_link] = STATE(27),
    [sym_text] = STATE(27),
    [aux_sym_inline_repeat1] = STATE(27),
    [aux_sym_text_repeat1] = STATE(51),
    [anon_sym_STAR] = ACTIONS(53),
    [anon_sym__] = ACTIONS(55),
    [anon_sym_STAR_STAR] = ACTIONS(57),
    [anon_sym___] = ACTIONS(59),
    [anon_sym_BQUOTE] = ACTIONS(61),
    [anon_sym_LBRACK] = ACTIONS(51),
    [aux_sym_text_token1] = ACTIONS(63),
    [aux_sym_text_token2] = ACTIONS(65),
  },
  [36] = {
    [sym_emphasis] = STATE(39),
    [sym_strong_emphasis] = STATE(39),
    [sym_code_span] = STATE(39),
    [sym_link_text] = STATE(117),
    [sym__link_text_element] = STATE(39),
    [sym_text] = STATE(39),
    [aux_sym_link_text_repeat1] = STATE(39),
    [aux_sym_text_repeat1] = STATE(51),
    [anon_sym_STAR] = ACTIONS(53),
    [anon_sym__] = ACTIONS(55),
    [anon_sym_STAR_STAR] = ACTIONS(69),
    [anon_sym___] = ACTIONS(71),
    [anon_sym_BQUOTE] = ACTIONS(61),
    [anon_sym_RBRACK] = ACTIONS(117),
    [aux_sym_text_token1] = ACTIONS(63),
    [aux_sym_text_token2] = ACTIONS(65),
  },
  [37] = {
    [sym_emphasis] = STATE(39),
    [sym_strong_emphasis] = STATE(39),
    [sym_code_span] = STATE(39),
    [sym_link_text] = STATE(119),
    [sym__link_text_element] = STATE(39),
    [sym_text] = STATE(39),
    [aux_sym_link_text_repeat1] = STATE(39),
    [aux_sym_text_repeat1] = STATE(51),
    [anon_sym_STAR] = ACTIONS(53),
    [anon_sym__] = ACTIONS(55),
    [anon_sym_STAR_STAR] = ACTIONS(69),
    [anon_sym___] = ACTIONS(71),
    [anon_sym_BQUOTE] = ACTIONS(61),
    [anon_sym_RBRACK] = ACTIONS(119),
    [aux_sym_text_token1] = ACTIONS(63),
    [aux_sym_text_token2] = ACTIONS(65),
  },
  [38] = {
    [sym_emphasis] = STATE(39),
    [sym_strong_emphasis] = STATE(39),
    [sym_code_span] = STATE(39),
    [sym_link_text] = STATE(121),
    [sym__link_text_element] = STATE(39),
    [sym_text] = STATE(39),
    [aux_sym_link_text_repeat1] = STATE(39),
    [aux_sym_text_repeat1] = STATE(51),
    [anon_sym_STAR] = ACTIONS(53),
    [anon_sym__] = ACTIONS(55),
    [anon_sym_STAR_STAR] = ACTIONS(69),
    [anon_sym___] = ACTIONS(71),
    [anon_sym_BQUOTE] = ACTIONS(61),
    [anon_sym_RBRACK] = ACTIONS(121),
    [aux_sym_text_token1] = ACTIONS(63),
    [aux_sym_text_token2] = ACTIONS(65),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 10,
    ACTIONS(53), 1,
      anon_sym_STAR,
    ACTIONS(55), 1,
      anon_sym__,
    ACTIONS(61), 1,
      anon_sym_BQUOTE,
    ACTIONS(63), 1,
      aux_sym_text_token1,
    ACTIONS(65), 1,
      aux_sym_text_token2,
    ACTIONS(69), 1,
      anon_sym_STAR_STAR,
    ACTIONS(71), 1,
      anon_sym___,
    ACTIONS(123), 1,
      anon_sym_RBRACK,
    STATE(51), 1,
      aux_sym_text_repeat1,
    STATE(40), 6,
      sym_emphasis,
      sym_strong_emphasis,
      sym_code_span,
      sym__link_text_element,
      sym_text,
      aux_sym_link_text_repeat1,
  [36] = 10,
    ACTIONS(125), 1,
      anon_sym_STAR,
    ACTIONS(128), 1,
      anon_sym__,
    ACTIONS(131), 1,
      anon_sym_STAR_STAR,
    ACTIONS(134), 1,
      anon_sym___,
    ACTIONS(137), 1,
      anon_sym_BQUOTE,
    ACTIONS(140), 1,
      anon_sym_RBRACK,
    ACTIONS(142), 1,
      aux_sym_text_token1,
    ACTIONS(145), 1,
      aux_sym_text_token2,
    STATE(51), 1,
      aux_sym_text_repeat1,
    STATE(40), 6,
      sym_emphasis,
      sym_strong_emphasis,
      sym_code_span,
      sym__link_text_element,
      sym_text,
      aux_sym_link_text_repeat1,
  [72] = 9,
    ACTIONS(148), 1,
      anon_sym__,
    ACTIONS(150), 1,
      anon_sym_STAR_STAR,
    ACTIONS(152), 1,
      anon_sym___,
    ACTIONS(154), 1,
      anon_sym_BQUOTE,
    ACTIONS(156), 1,
      anon_sym_LBRACK,
    ACTIONS(158), 1,
      aux_sym_text_token1,
    ACTIONS(160), 1,
      aux_sym_text_token2,
    STATE(72), 1,
      aux_sym_text_repeat1,
    STATE(46), 6,
      sym_strong_emphasis,
      sym__inline_no_underscore,
      sym_code_span,
      sym_link,
      sym_text,
      aux_sym_emphasis_repeat2,
  [105] = 9,
    ACTIONS(162), 1,
      anon_sym_STAR,
    ACTIONS(164), 1,
      anon_sym_STAR_STAR,
    ACTIONS(166), 1,
      anon_sym___,
    ACTIONS(168), 1,
      anon_sym_BQUOTE,
    ACTIONS(170), 1,
      anon_sym_LBRACK,
    ACTIONS(172), 1,
      aux_sym_text_token1,
    ACTIONS(174), 1,
      aux_sym_text_token2,
    STATE(70), 1,
      aux_sym_text_repeat1,
    STATE(45), 6,
      sym_strong_emphasis,
      sym__inline_no_star,
      sym_code_span,
      sym_link,
      sym_text,
      aux_sym_emphasis_repeat1,
  [138] = 9,
    ACTIONS(150), 1,
      anon_sym_STAR_STAR,
    ACTIONS(152), 1,
      anon_sym___,
    ACTIONS(154), 1,
      anon_sym_BQUOTE,
    ACTIONS(156), 1,
      anon_sym_LBRACK,
    ACTIONS(158), 1,
      aux_sym_text_token1,
    ACTIONS(160), 1,
      aux_sym_text_token2,
    ACTIONS(162), 1,
      anon_sym__,
    STATE(72), 1,
      aux_sym_text_repeat1,
    STATE(46), 6,
      sym_strong_emphasis,
      sym__inline_no_underscore,
      sym_code_span,
      sym_link,
      sym_text,
      aux_sym_emphasis_repeat2,
  [171] = 9,
    ACTIONS(148), 1,
      anon_sym_STAR,
    ACTIONS(164), 1,
      anon_sym_STAR_STAR,
    ACTIONS(166), 1,
      anon_sym___,
    ACTIONS(168), 1,
      anon_sym_BQUOTE,
    ACTIONS(170), 1,
      anon_sym_LBRACK,
    ACTIONS(172), 1,
      aux_sym_text_token1,
    ACTIONS(174), 1,
      aux_sym_text_token2,
    STATE(70), 1,
      aux_sym_text_repeat1,
    STATE(45), 6,
      sym_strong_emphasis,
      sym__inline_no_star,
      sym_code_span,
      sym_link,
      sym_text,
      aux_sym_emphasis_repeat1,
  [204] = 9,
    ACTIONS(176), 1,
      anon_sym_STAR,
    ACTIONS(178), 1,
      anon_sym_STAR_STAR,
    ACTIONS(181), 1,
      anon_sym___,
    ACTIONS(184), 1,
      anon_sym_BQUOTE,
    ACTIONS(187), 1,
      anon_sym_LBRACK,
    ACTIONS(190), 1,
      aux_sym_text_token1,
    ACTIONS(193), 1,
      aux_sym_text_token2,
    STATE(70), 1,
      aux_sym_text_repeat1,
    STATE(45), 6,
      sym_strong_emphasis,
      sym__inline_no_star,
      sym_code_span,
      sym_link,
      sym_text,
      aux_sym_emphasis_repeat1,
  [237] = 9,
    ACTIONS(196), 1,
      anon_sym__,
    ACTIONS(198), 1,
      anon_sym_STAR_STAR,
    ACTIONS(201), 1,
      anon_sym___,
    ACTIONS(204), 1,
      anon_sym_BQUOTE,
    ACTIONS(207), 1,
      anon_sym_LBRACK,
    ACTIONS(210), 1,
      aux_sym_text_token1,
    ACTIONS(213), 1,
      aux_sym_text_token2,
    STATE(72), 1,
      aux_sym_text_repeat1,
    STATE(46), 6,
      sym_strong_emphasis,
      sym__inline_no_underscore,
      sym_code_span,
      sym_link,
      sym_text,
      aux_sym_emphasis_repeat2,
  [270] = 8,
    ACTIONS(164), 1,
      anon_sym_STAR_STAR,
    ACTIONS(166), 1,
      anon_sym___,
    ACTIONS(168), 1,
      anon_sym_BQUOTE,
    ACTIONS(170), 1,
      anon_sym_LBRACK,
    ACTIONS(172), 1,
      aux_sym_text_token1,
    ACTIONS(174), 1,
      aux_sym_text_token2,
    STATE(70), 1,
      aux_sym_text_repeat1,
    STATE(42), 6,
      sym_strong_emphasis,
      sym__inline_no_star,
      sym_code_span,
      sym_link,
      sym_text,
      aux_sym_emphasis_repeat1,
  [300] = 8,
    ACTIONS(150), 1,
      anon_sym_STAR_STAR,
    ACTIONS(152), 1,
      anon_sym___,
    ACTIONS(154), 1,
      anon_sym_BQUOTE,
    ACTIONS(156), 1,
      anon_sym_LBRACK,
    ACTIONS(158), 1,
      aux_sym_text_token1,
    ACTIONS(160), 1,
      aux_sym_text_token2,
    STATE(72), 1,
      aux_sym_text_repeat1,
    STATE(41), 6,
      sym_strong_emphasis,
      sym__inline_no_underscore,
      sym_code_span,
      sym_link,
      sym_text,
      aux_sym_emphasis_repeat2,
  [330] = 8,
    ACTIONS(164), 1,
      anon_sym_STAR_STAR,
    ACTIONS(166), 1,
      anon_sym___,
    ACTIONS(168), 1,
      anon_sym_BQUOTE,
    ACTIONS(170), 1,
      anon_sym_LBRACK,
    ACTIONS(172), 1,
      aux_sym_text_token1,
    ACTIONS(174), 1,
      aux_sym_text_token2,
    STATE(70), 1,
      aux_sym_text_repeat1,
    STATE(44), 6,
      sym_strong_emphasis,
      sym__inline_no_star,
      sym_code_span,
      sym_link,
      sym_text,
      aux_sym_emphasis_repeat1,
  [360] = 8,
    ACTIONS(150), 1,
      anon_sym_STAR_STAR,
    ACTIONS(152), 1,
      anon_sym___,
    ACTIONS(154), 1,
      anon_sym_BQUOTE,
    ACTIONS(156), 1,
      anon_sym_LBRACK,
    ACTIONS(158), 1,
      aux_sym_text_token1,
    ACTIONS(160), 1,
      aux_sym_text_token2,
    STATE(72), 1,
      aux_sym_text_repeat1,
    STATE(43), 6,
      sym_strong_emphasis,
      sym__inline_no_underscore,
      sym_code_span,
      sym_link,
      sym_text,
      aux_sym_emphasis_repeat2,
  [390] = 4,
    ACTIONS(218), 1,
      aux_sym_text_token1,
    ACTIONS(220), 1,
      aux_sym_text_token2,
    STATE(52), 1,
      aux_sym_text_repeat1,
    ACTIONS(216), 7,
      anon_sym_STAR,
      anon_sym__,
      anon_sym_STAR_STAR,
      anon_sym___,
      anon_sym_BQUOTE,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
  [409] = 4,
    ACTIONS(224), 1,
      aux_sym_text_token1,
    ACTIONS(227), 1,
      aux_sym_text_token2,
    STATE(52), 1,
      aux_sym_text_repeat1,
    ACTIONS(222), 7,
      anon_sym_STAR,
      anon_sym__,
      anon_sym_STAR_STAR,
      anon_sym___,
      anon_sym_BQUOTE,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
  [428] = 5,
    ACTIONS(230), 1,
      ts_builtin_sym_end,
    ACTIONS(232), 1,
      aux_sym_text_token1,
    ACTIONS(234), 1,
      aux_sym_text_token2,
    STATE(54), 1,
      aux_sym_text_repeat1,
    ACTIONS(216), 6,
      anon_sym_STAR,
      anon_sym__,
      anon_sym_STAR_STAR,
      anon_sym___,
      anon_sym_BQUOTE,
      anon_sym_LBRACK,
  [449] = 5,
    ACTIONS(236), 1,
      ts_builtin_sym_end,
    ACTIONS(238), 1,
      aux_sym_text_token1,
    ACTIONS(241), 1,
      aux_sym_text_token2,
    STATE(54), 1,
      aux_sym_text_repeat1,
    ACTIONS(222), 6,
      anon_sym_STAR,
      anon_sym__,
      anon_sym_STAR_STAR,
      anon_sym___,
      anon_sym_BQUOTE,
      anon_sym_LBRACK,
  [470] = 2,
    ACTIONS(246), 1,
      aux_sym_text_token1,
    ACTIONS(244), 8,
      anon_sym_STAR,
      anon_sym__,
      anon_sym_STAR_STAR,
      anon_sym___,
      anon_sym_BQUOTE,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      aux_sym_text_token2,
  [484] = 2,
    ACTIONS(248), 2,
      ts_builtin_sym_end,
      aux_sym_text_token1,
    ACTIONS(250), 7,
      anon_sym_STAR,
      anon_sym__,
      anon_sym_STAR_STAR,
      anon_sym___,
      anon_sym_BQUOTE,
      anon_sym_LBRACK,
      aux_sym_text_token2,
  [498] = 2,
    ACTIONS(254), 1,
      aux_sym_text_token1,
    ACTIONS(252), 8,
      anon_sym_STAR,
      anon_sym__,
      anon_sym_STAR_STAR,
      anon_sym___,
      anon_sym_BQUOTE,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      aux_sym_text_token2,
  [512] = 2,
    ACTIONS(246), 2,
      ts_builtin_sym_end,
      aux_sym_text_token1,
    ACTIONS(244), 7,
      anon_sym_STAR,
      anon_sym__,
      anon_sym_STAR_STAR,
      anon_sym___,
      anon_sym_BQUOTE,
      anon_sym_LBRACK,
      aux_sym_text_token2,
  [526] = 2,
    ACTIONS(256), 2,
      ts_builtin_sym_end,
      aux_sym_text_token1,
    ACTIONS(258), 7,
      anon_sym_STAR,
      anon_sym__,
      anon_sym_STAR_STAR,
      anon_sym___,
      anon_sym_BQUOTE,
      anon_sym_LBRACK,
      aux_sym_text_token2,
  [540] = 2,
    ACTIONS(254), 2,
      ts_builtin_sym_end,
      aux_sym_text_token1,
    ACTIONS(252), 7,
      anon_sym_STAR,
      anon_sym__,
      anon_sym_STAR_STAR,
      anon_sym___,
      anon_sym_BQUOTE,
      anon_sym_LBRACK,
      aux_sym_text_token2,
  [554] = 2,
    ACTIONS(260), 2,
      ts_builtin_sym_end,
      aux_sym_text_token1,
    ACTIONS(262), 7,
      anon_sym_STAR,
      anon_sym__,
      anon_sym_STAR_STAR,
      anon_sym___,
      anon_sym_BQUOTE,
      anon_sym_LBRACK,
      aux_sym_text_token2,
  [568] = 2,
    ACTIONS(264), 2,
      ts_builtin_sym_end,
      aux_sym_text_token1,
    ACTIONS(266), 7,
      anon_sym_STAR,
      anon_sym__,
      anon_sym_STAR_STAR,
      anon_sym___,
      anon_sym_BQUOTE,
      anon_sym_LBRACK,
      aux_sym_text_token2,
  [582] = 2,
    ACTIONS(248), 1,
      aux_sym_text_token1,
    ACTIONS(250), 8,
      anon_sym_STAR,
      anon_sym__,
      anon_sym_STAR_STAR,
      anon_sym___,
      anon_sym_BQUOTE,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      aux_sym_text_token2,
  [596] = 2,
    ACTIONS(268), 2,
      ts_builtin_sym_end,
      aux_sym_text_token1,
    ACTIONS(270), 7,
      anon_sym_STAR,
      anon_sym__,
      anon_sym_STAR_STAR,
      anon_sym___,
      anon_sym_BQUOTE,
      anon_sym_LBRACK,
      aux_sym_text_token2,
  [610] = 4,
    ACTIONS(272), 1,
      aux_sym_text_token1,
    ACTIONS(275), 1,
      aux_sym_text_token2,
    STATE(65), 1,
      aux_sym_text_repeat1,
    ACTIONS(222), 5,
      anon_sym__,
      anon_sym_STAR_STAR,
      anon_sym___,
      anon_sym_BQUOTE,
      anon_sym_LBRACK,
  [627] = 2,
    ACTIONS(256), 1,
      aux_sym_text_token1,
    ACTIONS(258), 7,
      anon_sym_STAR,
      anon_sym__,
      anon_sym_STAR_STAR,
      anon_sym___,
      anon_sym_BQUOTE,
      anon_sym_LBRACK,
      aux_sym_text_token2,
  [640] = 2,
    ACTIONS(264), 1,
      aux_sym_text_token1,
    ACTIONS(266), 7,
      anon_sym_STAR,
      anon_sym__,
      anon_sym_STAR_STAR,
      anon_sym___,
      anon_sym_BQUOTE,
      anon_sym_LBRACK,
      aux_sym_text_token2,
  [653] = 2,
    ACTIONS(260), 1,
      aux_sym_text_token1,
    ACTIONS(262), 7,
      anon_sym_STAR,
      anon_sym__,
      anon_sym_STAR_STAR,
      anon_sym___,
      anon_sym_BQUOTE,
      anon_sym_LBRACK,
      aux_sym_text_token2,
  [666] = 2,
    ACTIONS(268), 1,
      aux_sym_text_token1,
    ACTIONS(270), 7,
      anon_sym_STAR,
      anon_sym__,
      anon_sym_STAR_STAR,
      anon_sym___,
      anon_sym_BQUOTE,
      anon_sym_LBRACK,
      aux_sym_text_token2,
  [679] = 4,
    ACTIONS(278), 1,
      aux_sym_text_token1,
    ACTIONS(280), 1,
      aux_sym_text_token2,
    STATE(71), 1,
      aux_sym_text_repeat1,
    ACTIONS(216), 5,
      anon_sym_STAR,
      anon_sym_STAR_STAR,
      anon_sym___,
      anon_sym_BQUOTE,
      anon_sym_LBRACK,
  [696] = 4,
    ACTIONS(282), 1,
      aux_sym_text_token1,
    ACTIONS(285), 1,
      aux_sym_text_token2,
    STATE(71), 1,
      aux_sym_text_repeat1,
    ACTIONS(222), 5,
      anon_sym_STAR,
      anon_sym_STAR_STAR,
      anon_sym___,
      anon_sym_BQUOTE,
      anon_sym_LBRACK,
  [713] = 4,
    ACTIONS(288), 1,
      aux_sym_text_token1,
    ACTIONS(290), 1,
      aux_sym_text_token2,
    STATE(65), 1,
      aux_sym_text_repeat1,
    ACTIONS(216), 5,
      anon_sym__,
      anon_sym_STAR_STAR,
      anon_sym___,
      anon_sym_BQUOTE,
      anon_sym_LBRACK,
  [730] = 2,
    ACTIONS(268), 1,
      aux_sym_text_token1,
    ACTIONS(270), 6,
      anon_sym__,
      anon_sym_STAR_STAR,
      anon_sym___,
      anon_sym_BQUOTE,
      anon_sym_LBRACK,
      aux_sym_text_token2,
  [742] = 2,
    ACTIONS(246), 1,
      aux_sym_text_token1,
    ACTIONS(244), 6,
      anon_sym__,
      anon_sym_STAR_STAR,
      anon_sym___,
      anon_sym_BQUOTE,
      anon_sym_LBRACK,
      aux_sym_text_token2,
  [754] = 2,
    ACTIONS(260), 1,
      aux_sym_text_token1,
    ACTIONS(262), 6,
      anon_sym__,
      anon_sym_STAR_STAR,
      anon_sym___,
      anon_sym_BQUOTE,
      anon_sym_LBRACK,
      aux_sym_text_token2,
  [766] = 2,
    ACTIONS(256), 1,
      aux_sym_text_token1,
    ACTIONS(258), 6,
      anon_sym__,
      anon_sym_STAR_STAR,
      anon_sym___,
      anon_sym_BQUOTE,
      anon_sym_LBRACK,
      aux_sym_text_token2,
  [778] = 2,
    ACTIONS(246), 1,
      aux_sym_text_token1,
    ACTIONS(244), 6,
      anon_sym_STAR,
      anon_sym_STAR_STAR,
      anon_sym___,
      anon_sym_BQUOTE,
      anon_sym_LBRACK,
      aux_sym_text_token2,
  [790] = 2,
    ACTIONS(264), 1,
      aux_sym_text_token1,
    ACTIONS(266), 6,
      anon_sym__,
      anon_sym_STAR_STAR,
      anon_sym___,
      anon_sym_BQUOTE,
      anon_sym_LBRACK,
      aux_sym_text_token2,
  [802] = 2,
    ACTIONS(254), 1,
      aux_sym_text_token1,
    ACTIONS(252), 6,
      anon_sym_STAR,
      anon_sym_STAR_STAR,
      anon_sym___,
      anon_sym_BQUOTE,
      anon_sym_LBRACK,
      aux_sym_text_token2,
  [814] = 2,
    ACTIONS(256), 1,
      aux_sym_text_token1,
    ACTIONS(258), 6,
      anon_sym_STAR,
      anon_sym_STAR_STAR,
      anon_sym___,
      anon_sym_BQUOTE,
      anon_sym_LBRACK,
      aux_sym_text_token2,
  [826] = 2,
    ACTIONS(264), 1,
      aux_sym_text_token1,
    ACTIONS(266), 6,
      anon_sym_STAR,
      anon_sym_STAR_STAR,
      anon_sym___,
      anon_sym_BQUOTE,
      anon_sym_LBRACK,
      aux_sym_text_token2,
  [838] = 2,
    ACTIONS(260), 1,
      aux_sym_text_token1,
    ACTIONS(262), 6,
      anon_sym_STAR,
      anon_sym_STAR_STAR,
      anon_sym___,
      anon_sym_BQUOTE,
      anon_sym_LBRACK,
      aux_sym_text_token2,
  [850] = 2,
    ACTIONS(268), 1,
      aux_sym_text_token1,
    ACTIONS(270), 6,
      anon_sym_STAR,
      anon_sym_STAR_STAR,
      anon_sym___,
      anon_sym_BQUOTE,
      anon_sym_LBRACK,
      aux_sym_text_token2,
  [862] = 2,
    ACTIONS(254), 1,
      aux_sym_text_token1,
    ACTIONS(252), 6,
      anon_sym__,
      anon_sym_STAR_STAR,
      anon_sym___,
      anon_sym_BQUOTE,
      anon_sym_LBRACK,
      aux_sym_text_token2,
  [874] = 2,
    ACTIONS(292), 1,
      anon_sym_RPAREN,
    ACTIONS(294), 1,
      sym_link_destination,
  [881] = 2,
    ACTIONS(296), 1,
      anon_sym_RPAREN,
    ACTIONS(298), 1,
      sym_link_destination,
  [888] = 2,
    ACTIONS(300), 1,
      anon_sym_BQUOTE,
    ACTIONS(302), 1,
      aux_sym_code_span_token1,
  [895] = 2,
    ACTIONS(304), 1,
      anon_sym_RPAREN,
    ACTIONS(306), 1,
      sym_link_destination,
  [902] = 2,
    ACTIONS(308), 1,
      anon_sym_RPAREN,
    ACTIONS(310), 1,
      sym_link_destination,
  [909] = 2,
    ACTIONS(312), 1,
      anon_sym_RPAREN,
    ACTIONS(314), 1,
      sym_link_destination,
  [916] = 2,
    ACTIONS(316), 1,
      anon_sym_BQUOTE,
    ACTIONS(318), 1,
      aux_sym_code_span_token1,
  [923] = 2,
    ACTIONS(320), 1,
      anon_sym_RPAREN,
    ACTIONS(322), 1,
      sym_link_destination,
  [930] = 2,
    ACTIONS(324), 1,
      anon_sym_BQUOTE,
    ACTIONS(326), 1,
      aux_sym_code_span_token1,
  [937] = 2,
    ACTIONS(328), 1,
      anon_sym_RPAREN,
    ACTIONS(330), 1,
      sym_link_destination,
  [944] = 2,
    ACTIONS(332), 1,
      anon_sym_BQUOTE,
    ACTIONS(334), 1,
      aux_sym_code_span_token1,
  [951] = 2,
    ACTIONS(336), 1,
      anon_sym_RPAREN,
    ACTIONS(338), 1,
      sym_link_destination,
  [958] = 1,
    ACTIONS(340), 1,
      anon_sym_LPAREN,
  [962] = 1,
    ACTIONS(342), 1,
      anon_sym_RBRACK,
  [966] = 1,
    ACTIONS(344), 1,
      anon_sym_BQUOTE,
  [970] = 1,
    ACTIONS(346), 1,
      ts_builtin_sym_end,
  [974] = 1,
    ACTIONS(348), 1,
      anon_sym_RPAREN,
  [978] = 1,
    ACTIONS(350), 1,
      anon_sym_RPAREN,
  [982] = 1,
    ACTIONS(352), 1,
      anon_sym_BQUOTE,
  [986] = 1,
    ACTIONS(354), 1,
      anon_sym_LPAREN,
  [990] = 1,
    ACTIONS(356), 1,
      anon_sym_LPAREN,
  [994] = 1,
    ACTIONS(358), 1,
      anon_sym_BQUOTE,
  [998] = 1,
    ACTIONS(360), 1,
      anon_sym_RPAREN,
  [1002] = 1,
    ACTIONS(362), 1,
      anon_sym_LPAREN,
  [1006] = 1,
    ACTIONS(364), 1,
      anon_sym_LPAREN,
  [1010] = 1,
    ACTIONS(366), 1,
      anon_sym_RPAREN,
  [1014] = 1,
    ACTIONS(368), 1,
      anon_sym_RPAREN,
  [1018] = 1,
    ACTIONS(370), 1,
      anon_sym_LPAREN,
  [1022] = 1,
    ACTIONS(372), 1,
      anon_sym_LPAREN,
  [1026] = 1,
    ACTIONS(374), 1,
      anon_sym_RPAREN,
  [1030] = 1,
    ACTIONS(376), 1,
      anon_sym_RPAREN,
  [1034] = 1,
    ACTIONS(378), 1,
      anon_sym_RPAREN,
  [1038] = 1,
    ACTIONS(380), 1,
      anon_sym_RBRACK,
  [1042] = 1,
    ACTIONS(382), 1,
      anon_sym_LPAREN,
  [1046] = 1,
    ACTIONS(384), 1,
      anon_sym_RBRACK,
  [1050] = 1,
    ACTIONS(386), 1,
      anon_sym_BQUOTE,
  [1054] = 1,
    ACTIONS(388), 1,
      anon_sym_RBRACK,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(39)] = 0,
  [SMALL_STATE(40)] = 36,
  [SMALL_STATE(41)] = 72,
  [SMALL_STATE(42)] = 105,
  [SMALL_STATE(43)] = 138,
  [SMALL_STATE(44)] = 171,
  [SMALL_STATE(45)] = 204,
  [SMALL_STATE(46)] = 237,
  [SMALL_STATE(47)] = 270,
  [SMALL_STATE(48)] = 300,
  [SMALL_STATE(49)] = 330,
  [SMALL_STATE(50)] = 360,
  [SMALL_STATE(51)] = 390,
  [SMALL_STATE(52)] = 409,
  [SMALL_STATE(53)] = 428,
  [SMALL_STATE(54)] = 449,
  [SMALL_STATE(55)] = 470,
  [SMALL_STATE(56)] = 484,
  [SMALL_STATE(57)] = 498,
  [SMALL_STATE(58)] = 512,
  [SMALL_STATE(59)] = 526,
  [SMALL_STATE(60)] = 540,
  [SMALL_STATE(61)] = 554,
  [SMALL_STATE(62)] = 568,
  [SMALL_STATE(63)] = 582,
  [SMALL_STATE(64)] = 596,
  [SMALL_STATE(65)] = 610,
  [SMALL_STATE(66)] = 627,
  [SMALL_STATE(67)] = 640,
  [SMALL_STATE(68)] = 653,
  [SMALL_STATE(69)] = 666,
  [SMALL_STATE(70)] = 679,
  [SMALL_STATE(71)] = 696,
  [SMALL_STATE(72)] = 713,
  [SMALL_STATE(73)] = 730,
  [SMALL_STATE(74)] = 742,
  [SMALL_STATE(75)] = 754,
  [SMALL_STATE(76)] = 766,
  [SMALL_STATE(77)] = 778,
  [SMALL_STATE(78)] = 790,
  [SMALL_STATE(79)] = 802,
  [SMALL_STATE(80)] = 814,
  [SMALL_STATE(81)] = 826,
  [SMALL_STATE(82)] = 838,
  [SMALL_STATE(83)] = 850,
  [SMALL_STATE(84)] = 862,
  [SMALL_STATE(85)] = 874,
  [SMALL_STATE(86)] = 881,
  [SMALL_STATE(87)] = 888,
  [SMALL_STATE(88)] = 895,
  [SMALL_STATE(89)] = 902,
  [SMALL_STATE(90)] = 909,
  [SMALL_STATE(91)] = 916,
  [SMALL_STATE(92)] = 923,
  [SMALL_STATE(93)] = 930,
  [SMALL_STATE(94)] = 937,
  [SMALL_STATE(95)] = 944,
  [SMALL_STATE(96)] = 951,
  [SMALL_STATE(97)] = 958,
  [SMALL_STATE(98)] = 962,
  [SMALL_STATE(99)] = 966,
  [SMALL_STATE(100)] = 970,
  [SMALL_STATE(101)] = 974,
  [SMALL_STATE(102)] = 978,
  [SMALL_STATE(103)] = 982,
  [SMALL_STATE(104)] = 986,
  [SMALL_STATE(105)] = 990,
  [SMALL_STATE(106)] = 994,
  [SMALL_STATE(107)] = 998,
  [SMALL_STATE(108)] = 1002,
  [SMALL_STATE(109)] = 1006,
  [SMALL_STATE(110)] = 1010,
  [SMALL_STATE(111)] = 1014,
  [SMALL_STATE(112)] = 1018,
  [SMALL_STATE(113)] = 1022,
  [SMALL_STATE(114)] = 1026,
  [SMALL_STATE(115)] = 1030,
  [SMALL_STATE(116)] = 1034,
  [SMALL_STATE(117)] = 1038,
  [SMALL_STATE(118)] = 1042,
  [SMALL_STATE(119)] = 1046,
  [SMALL_STATE(120)] = 1050,
  [SMALL_STATE(121)] = 1054,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = false}}, SHIFT(47),
  [5] = {.entry = {.count = 1, .reusable = false}}, SHIFT(50),
  [7] = {.entry = {.count = 1, .reusable = false}}, SHIFT(11),
  [9] = {.entry = {.count = 1, .reusable = false}}, SHIFT(12),
  [11] = {.entry = {.count = 1, .reusable = false}}, SHIFT(91),
  [13] = {.entry = {.count = 1, .reusable = false}}, SHIFT(13),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(53),
  [17] = {.entry = {.count = 1, .reusable = false}}, SHIFT(53),
  [19] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_inline, 1, 0, 0),
  [21] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_inline_repeat1, 2, 0, 0),
  [23] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_inline_repeat1, 2, 0, 0), SHIFT_REPEAT(47),
  [26] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_inline_repeat1, 2, 0, 0), SHIFT_REPEAT(50),
  [29] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_inline_repeat1, 2, 0, 0), SHIFT_REPEAT(11),
  [32] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_inline_repeat1, 2, 0, 0), SHIFT_REPEAT(12),
  [35] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_inline_repeat1, 2, 0, 0), SHIFT_REPEAT(91),
  [38] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_inline_repeat1, 2, 0, 0), SHIFT_REPEAT(13),
  [41] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_inline_repeat1, 2, 0, 0), SHIFT_REPEAT(53),
  [44] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_inline_repeat1, 2, 0, 0), SHIFT_REPEAT(53),
  [47] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_strong_emphasis, 3, 0, 0),
  [49] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_strong_emphasis, 3, 0, 0),
  [51] = {.entry = {.count = 1, .reusable = false}}, SHIFT(38),
  [53] = {.entry = {.count = 1, .reusable = false}}, SHIFT(49),
  [55] = {.entry = {.count = 1, .reusable = false}}, SHIFT(48),
  [57] = {.entry = {.count = 1, .reusable = false}}, SHIFT(32),
  [59] = {.entry = {.count = 1, .reusable = false}}, SHIFT(33),
  [61] = {.entry = {.count = 1, .reusable = false}}, SHIFT(87),
  [63] = {.entry = {.count = 1, .reusable = true}}, SHIFT(51),
  [65] = {.entry = {.count = 1, .reusable = false}}, SHIFT(51),
  [67] = {.entry = {.count = 1, .reusable = false}}, SHIFT(5),
  [69] = {.entry = {.count = 1, .reusable = false}}, SHIFT(34),
  [71] = {.entry = {.count = 1, .reusable = false}}, SHIFT(35),
  [73] = {.entry = {.count = 1, .reusable = false}}, SHIFT(113),
  [75] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_inline_repeat1, 2, 0, 0), SHIFT_REPEAT(49),
  [78] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_inline_repeat1, 2, 0, 0), SHIFT_REPEAT(48),
  [81] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_inline_repeat1, 2, 0, 0), SHIFT_REPEAT(32),
  [84] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_inline_repeat1, 2, 0, 0), SHIFT_REPEAT(33),
  [87] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_inline_repeat1, 2, 0, 0), SHIFT_REPEAT(87),
  [90] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_inline_repeat1, 2, 0, 0), SHIFT_REPEAT(38),
  [93] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_inline_repeat1, 2, 0, 0), SHIFT_REPEAT(51),
  [96] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_inline_repeat1, 2, 0, 0), SHIFT_REPEAT(51),
  [99] = {.entry = {.count = 1, .reusable = false}}, SHIFT(16),
  [101] = {.entry = {.count = 1, .reusable = false}}, SHIFT(17),
  [103] = {.entry = {.count = 1, .reusable = false}}, SHIFT(18),
  [105] = {.entry = {.count = 1, .reusable = false}}, SHIFT(10),
  [107] = {.entry = {.count = 1, .reusable = false}}, SHIFT(14),
  [109] = {.entry = {.count = 1, .reusable = false}}, SHIFT(19),
  [111] = {.entry = {.count = 1, .reusable = false}}, SHIFT(6),
  [113] = {.entry = {.count = 1, .reusable = false}}, SHIFT(7),
  [115] = {.entry = {.count = 1, .reusable = false}}, SHIFT(4),
  [117] = {.entry = {.count = 1, .reusable = false}}, SHIFT(104),
  [119] = {.entry = {.count = 1, .reusable = false}}, SHIFT(108),
  [121] = {.entry = {.count = 1, .reusable = false}}, SHIFT(112),
  [123] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_link_text, 1, 0, 0),
  [125] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_link_text_repeat1, 2, 0, 0), SHIFT_REPEAT(49),
  [128] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_link_text_repeat1, 2, 0, 0), SHIFT_REPEAT(48),
  [131] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_link_text_repeat1, 2, 0, 0), SHIFT_REPEAT(34),
  [134] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_link_text_repeat1, 2, 0, 0), SHIFT_REPEAT(35),
  [137] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_link_text_repeat1, 2, 0, 0), SHIFT_REPEAT(87),
  [140] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_link_text_repeat1, 2, 0, 0),
  [142] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_link_text_repeat1, 2, 0, 0), SHIFT_REPEAT(51),
  [145] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_link_text_repeat1, 2, 0, 0), SHIFT_REPEAT(51),
  [148] = {.entry = {.count = 1, .reusable = false}}, SHIFT(63),
  [150] = {.entry = {.count = 1, .reusable = false}}, SHIFT(8),
  [152] = {.entry = {.count = 1, .reusable = false}}, SHIFT(31),
  [154] = {.entry = {.count = 1, .reusable = false}}, SHIFT(95),
  [156] = {.entry = {.count = 1, .reusable = false}}, SHIFT(37),
  [158] = {.entry = {.count = 1, .reusable = true}}, SHIFT(72),
  [160] = {.entry = {.count = 1, .reusable = false}}, SHIFT(72),
  [162] = {.entry = {.count = 1, .reusable = false}}, SHIFT(56),
  [164] = {.entry = {.count = 1, .reusable = false}}, SHIFT(28),
  [166] = {.entry = {.count = 1, .reusable = false}}, SHIFT(29),
  [168] = {.entry = {.count = 1, .reusable = false}}, SHIFT(93),
  [170] = {.entry = {.count = 1, .reusable = false}}, SHIFT(36),
  [172] = {.entry = {.count = 1, .reusable = true}}, SHIFT(70),
  [174] = {.entry = {.count = 1, .reusable = false}}, SHIFT(70),
  [176] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_emphasis_repeat1, 2, 0, 0),
  [178] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_emphasis_repeat1, 2, 0, 0), SHIFT_REPEAT(28),
  [181] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_emphasis_repeat1, 2, 0, 0), SHIFT_REPEAT(29),
  [184] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_emphasis_repeat1, 2, 0, 0), SHIFT_REPEAT(93),
  [187] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_emphasis_repeat1, 2, 0, 0), SHIFT_REPEAT(36),
  [190] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_emphasis_repeat1, 2, 0, 0), SHIFT_REPEAT(70),
  [193] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_emphasis_repeat1, 2, 0, 0), SHIFT_REPEAT(70),
  [196] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_emphasis_repeat2, 2, 0, 0),
  [198] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_emphasis_repeat2, 2, 0, 0), SHIFT_REPEAT(8),
  [201] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_emphasis_repeat2, 2, 0, 0), SHIFT_REPEAT(31),
  [204] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_emphasis_repeat2, 2, 0, 0), SHIFT_REPEAT(95),
  [207] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_emphasis_repeat2, 2, 0, 0), SHIFT_REPEAT(37),
  [210] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_emphasis_repeat2, 2, 0, 0), SHIFT_REPEAT(72),
  [213] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_emphasis_repeat2, 2, 0, 0), SHIFT_REPEAT(72),
  [216] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_text, 1, 0, 0),
  [218] = {.entry = {.count = 1, .reusable = true}}, SHIFT(52),
  [220] = {.entry = {.count = 1, .reusable = false}}, SHIFT(52),
  [222] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_text_repeat1, 2, 0, 0),
  [224] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_text_repeat1, 2, 0, 0), SHIFT_REPEAT(52),
  [227] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_text_repeat1, 2, 0, 0), SHIFT_REPEAT(52),
  [230] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_text, 1, 0, 0),
  [232] = {.entry = {.count = 1, .reusable = true}}, SHIFT(54),
  [234] = {.entry = {.count = 1, .reusable = false}}, SHIFT(54),
  [236] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_text_repeat1, 2, 0, 0),
  [238] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_text_repeat1, 2, 0, 0), SHIFT_REPEAT(54),
  [241] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_text_repeat1, 2, 0, 0), SHIFT_REPEAT(54),
  [244] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_code_span, 2, 0, 0),
  [246] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_code_span, 2, 0, 0),
  [248] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_emphasis, 3, 0, 0),
  [250] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_emphasis, 3, 0, 0),
  [252] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_code_span, 3, 0, 1),
  [254] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_code_span, 3, 0, 1),
  [256] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_link, 4, 0, 0),
  [258] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_link, 4, 0, 0),
  [260] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_link, 5, 0, 3),
  [262] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_link, 5, 0, 3),
  [264] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_link, 5, 0, 2),
  [266] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_link, 5, 0, 2),
  [268] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_link, 6, 0, 4),
  [270] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_link, 6, 0, 4),
  [272] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_text_repeat1, 2, 0, 0), SHIFT_REPEAT(65),
  [275] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_text_repeat1, 2, 0, 0), SHIFT_REPEAT(65),
  [278] = {.entry = {.count = 1, .reusable = true}}, SHIFT(71),
  [280] = {.entry = {.count = 1, .reusable = false}}, SHIFT(71),
  [282] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_text_repeat1, 2, 0, 0), SHIFT_REPEAT(71),
  [285] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_text_repeat1, 2, 0, 0), SHIFT_REPEAT(71),
  [288] = {.entry = {.count = 1, .reusable = true}}, SHIFT(65),
  [290] = {.entry = {.count = 1, .reusable = false}}, SHIFT(65),
  [292] = {.entry = {.count = 1, .reusable = false}}, SHIFT(76),
  [294] = {.entry = {.count = 1, .reusable = true}}, SHIFT(114),
  [296] = {.entry = {.count = 1, .reusable = false}}, SHIFT(75),
  [298] = {.entry = {.count = 1, .reusable = true}}, SHIFT(107),
  [300] = {.entry = {.count = 1, .reusable = false}}, SHIFT(55),
  [302] = {.entry = {.count = 1, .reusable = true}}, SHIFT(106),
  [304] = {.entry = {.count = 1, .reusable = false}}, SHIFT(66),
  [306] = {.entry = {.count = 1, .reusable = true}}, SHIFT(110),
  [308] = {.entry = {.count = 1, .reusable = false}}, SHIFT(68),
  [310] = {.entry = {.count = 1, .reusable = true}}, SHIFT(115),
  [312] = {.entry = {.count = 1, .reusable = false}}, SHIFT(80),
  [314] = {.entry = {.count = 1, .reusable = true}}, SHIFT(102),
  [316] = {.entry = {.count = 1, .reusable = false}}, SHIFT(58),
  [318] = {.entry = {.count = 1, .reusable = true}}, SHIFT(103),
  [320] = {.entry = {.count = 1, .reusable = false}}, SHIFT(59),
  [322] = {.entry = {.count = 1, .reusable = true}}, SHIFT(116),
  [324] = {.entry = {.count = 1, .reusable = false}}, SHIFT(77),
  [326] = {.entry = {.count = 1, .reusable = true}}, SHIFT(99),
  [328] = {.entry = {.count = 1, .reusable = false}}, SHIFT(82),
  [330] = {.entry = {.count = 1, .reusable = true}}, SHIFT(111),
  [332] = {.entry = {.count = 1, .reusable = false}}, SHIFT(74),
  [334] = {.entry = {.count = 1, .reusable = true}}, SHIFT(120),
  [336] = {.entry = {.count = 1, .reusable = false}}, SHIFT(61),
  [338] = {.entry = {.count = 1, .reusable = true}}, SHIFT(101),
  [340] = {.entry = {.count = 1, .reusable = true}}, SHIFT(89),
  [342] = {.entry = {.count = 1, .reusable = true}}, SHIFT(118),
  [344] = {.entry = {.count = 1, .reusable = true}}, SHIFT(79),
  [346] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [348] = {.entry = {.count = 1, .reusable = true}}, SHIFT(64),
  [350] = {.entry = {.count = 1, .reusable = true}}, SHIFT(81),
  [352] = {.entry = {.count = 1, .reusable = true}}, SHIFT(60),
  [354] = {.entry = {.count = 1, .reusable = true}}, SHIFT(90),
  [356] = {.entry = {.count = 1, .reusable = true}}, SHIFT(94),
  [358] = {.entry = {.count = 1, .reusable = true}}, SHIFT(57),
  [360] = {.entry = {.count = 1, .reusable = true}}, SHIFT(73),
  [362] = {.entry = {.count = 1, .reusable = true}}, SHIFT(85),
  [364] = {.entry = {.count = 1, .reusable = true}}, SHIFT(86),
  [366] = {.entry = {.count = 1, .reusable = true}}, SHIFT(67),
  [368] = {.entry = {.count = 1, .reusable = true}}, SHIFT(83),
  [370] = {.entry = {.count = 1, .reusable = true}}, SHIFT(88),
  [372] = {.entry = {.count = 1, .reusable = true}}, SHIFT(92),
  [374] = {.entry = {.count = 1, .reusable = true}}, SHIFT(78),
  [376] = {.entry = {.count = 1, .reusable = true}}, SHIFT(69),
  [378] = {.entry = {.count = 1, .reusable = true}}, SHIFT(62),
  [380] = {.entry = {.count = 1, .reusable = true}}, SHIFT(105),
  [382] = {.entry = {.count = 1, .reusable = true}}, SHIFT(96),
  [384] = {.entry = {.count = 1, .reusable = true}}, SHIFT(109),
  [386] = {.entry = {.count = 1, .reusable = true}}, SHIFT(84),
  [388] = {.entry = {.count = 1, .reusable = true}}, SHIFT(97),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_pandoc_markdown_inline(void) {
  static const TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
