#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 66
#define LARGE_STATE_COUNT 39
#define SYMBOL_COUNT 21
#define ALIAS_COUNT 0
#define TOKEN_COUNT 9
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 1
#define MAX_ALIAS_SEQUENCE_LENGTH 3
#define PRODUCTION_ID_COUNT 2

enum ts_symbol_identifiers {
  anon_sym_STAR = 1,
  anon_sym__ = 2,
  anon_sym_STAR_STAR = 3,
  anon_sym___ = 4,
  anon_sym_BQUOTE = 5,
  aux_sym_code_span_token1 = 6,
  aux_sym_text_token1 = 7,
  aux_sym_text_token2 = 8,
  sym_inline = 9,
  sym__inline_element = 10,
  sym_emphasis = 11,
  sym_strong_emphasis = 12,
  sym__inline_no_star = 13,
  sym__inline_no_underscore = 14,
  sym_code_span = 15,
  sym_text = 16,
  aux_sym_inline_repeat1 = 17,
  aux_sym_emphasis_repeat1 = 18,
  aux_sym_emphasis_repeat2 = 19,
  aux_sym_text_repeat1 = 20,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_STAR] = "*",
  [anon_sym__] = "_",
  [anon_sym_STAR_STAR] = "**",
  [anon_sym___] = "__",
  [anon_sym_BQUOTE] = "`",
  [aux_sym_code_span_token1] = "code_span_content",
  [aux_sym_text_token1] = "text_token1",
  [aux_sym_text_token2] = "text_token2",
  [sym_inline] = "inline",
  [sym__inline_element] = "_inline_element",
  [sym_emphasis] = "emphasis",
  [sym_strong_emphasis] = "strong_emphasis",
  [sym__inline_no_star] = "_inline_no_star",
  [sym__inline_no_underscore] = "_inline_no_underscore",
  [sym_code_span] = "code_span",
  [sym_text] = "text",
  [aux_sym_inline_repeat1] = "inline_repeat1",
  [aux_sym_emphasis_repeat1] = "emphasis_repeat1",
  [aux_sym_emphasis_repeat2] = "emphasis_repeat2",
  [aux_sym_text_repeat1] = "text_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_STAR] = anon_sym_STAR,
  [anon_sym__] = anon_sym__,
  [anon_sym_STAR_STAR] = anon_sym_STAR_STAR,
  [anon_sym___] = anon_sym___,
  [anon_sym_BQUOTE] = anon_sym_BQUOTE,
  [aux_sym_code_span_token1] = aux_sym_code_span_token1,
  [aux_sym_text_token1] = aux_sym_text_token1,
  [aux_sym_text_token2] = aux_sym_text_token2,
  [sym_inline] = sym_inline,
  [sym__inline_element] = sym__inline_element,
  [sym_emphasis] = sym_emphasis,
  [sym_strong_emphasis] = sym_strong_emphasis,
  [sym__inline_no_star] = sym__inline_no_star,
  [sym__inline_no_underscore] = sym__inline_no_underscore,
  [sym_code_span] = sym_code_span,
  [sym_text] = sym_text,
  [aux_sym_inline_repeat1] = aux_sym_inline_repeat1,
  [aux_sym_emphasis_repeat1] = aux_sym_emphasis_repeat1,
  [aux_sym_emphasis_repeat2] = aux_sym_emphasis_repeat2,
  [aux_sym_text_repeat1] = aux_sym_text_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_STAR] = {
    .visible = true,
    .named = false,
  },
  [anon_sym__] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_STAR_STAR] = {
    .visible = true,
    .named = false,
  },
  [anon_sym___] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_BQUOTE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_code_span_token1] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_text_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_text_token2] = {
    .visible = false,
    .named = false,
  },
  [sym_inline] = {
    .visible = true,
    .named = true,
  },
  [sym__inline_element] = {
    .visible = false,
    .named = true,
  },
  [sym_emphasis] = {
    .visible = true,
    .named = true,
  },
  [sym_strong_emphasis] = {
    .visible = true,
    .named = true,
  },
  [sym__inline_no_star] = {
    .visible = false,
    .named = true,
  },
  [sym__inline_no_underscore] = {
    .visible = false,
    .named = true,
  },
  [sym_code_span] = {
    .visible = true,
    .named = true,
  },
  [sym_text] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_inline_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_emphasis_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_emphasis_repeat2] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_text_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_content = 1,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_content] = "content",
};

static const TSFieldMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 1},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_content, 1},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 7,
  [11] = 3,
  [12] = 4,
  [13] = 5,
  [14] = 5,
  [15] = 4,
  [16] = 5,
  [17] = 8,
  [18] = 9,
  [19] = 8,
  [20] = 9,
  [21] = 8,
  [22] = 9,
  [23] = 6,
  [24] = 7,
  [25] = 6,
  [26] = 7,
  [27] = 6,
  [28] = 4,
  [29] = 29,
  [30] = 29,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 31,
  [35] = 35,
  [36] = 36,
  [37] = 35,
  [38] = 36,
  [39] = 39,
  [40] = 40,
  [41] = 40,
  [42] = 42,
  [43] = 39,
  [44] = 44,
  [45] = 45,
  [46] = 40,
  [47] = 45,
  [48] = 44,
  [49] = 40,
  [50] = 39,
  [51] = 39,
  [52] = 42,
  [53] = 45,
  [54] = 44,
  [55] = 45,
  [56] = 44,
  [57] = 57,
  [58] = 57,
  [59] = 57,
  [60] = 57,
  [61] = 61,
  [62] = 61,
  [63] = 61,
  [64] = 64,
  [65] = 61,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(6);
      if (lookahead == '*') ADVANCE(7);
      if (lookahead == '_') ADVANCE(8);
      if (lookahead == '`') ADVANCE(11);
      if (lookahead == '\n' ||
          lookahead == '\r') SKIP(0);
      if (('\t' <= lookahead && lookahead <= '\f') ||
          lookahead == ' ') ADVANCE(14);
      if (lookahead != 0 &&
          lookahead != '[') ADVANCE(15);
      END_STATE();
    case 1:
      if (lookahead == '*') ADVANCE(7);
      if (lookahead == '_') ADVANCE(17);
      if (lookahead == '`') ADVANCE(11);
      if (lookahead == '\n' ||
          lookahead == '\r') SKIP(1);
      if (('\t' <= lookahead && lookahead <= '\f') ||
          lookahead == ' ') ADVANCE(14);
      if (lookahead != 0 &&
          lookahead != '[') ADVANCE(15);
      END_STATE();
    case 2:
      if (lookahead == '*') ADVANCE(16);
      if (lookahead == '_') ADVANCE(8);
      if (lookahead == '`') ADVANCE(11);
      if (lookahead == '\n' ||
          lookahead == '\r') SKIP(2);
      if (('\t' <= lookahead && lookahead <= '\f') ||
          lookahead == ' ') ADVANCE(14);
      if (lookahead != 0 &&
          lookahead != '[') ADVANCE(15);
      END_STATE();
    case 3:
      if (lookahead == '*') ADVANCE(16);
      if (lookahead == '_') ADVANCE(17);
      if (lookahead == '`') ADVANCE(11);
      if (lookahead == '\n' ||
          lookahead == '\r') SKIP(3);
      if (('\t' <= lookahead && lookahead <= '\f') ||
          lookahead == ' ') ADVANCE(14);
      if (lookahead != 0 &&
          lookahead != '[') ADVANCE(15);
      END_STATE();
    case 4:
      if (lookahead == '`') ADVANCE(11);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(12);
      if (lookahead != 0) ADVANCE(13);
      END_STATE();
    case 5:
      if (lookahead == '`') ADVANCE(11);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(5);
      END_STATE();
    case 6:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 7:
      ACCEPT_TOKEN(anon_sym_STAR);
      if (lookahead == '*') ADVANCE(9);
      END_STATE();
    case 8:
      ACCEPT_TOKEN(anon_sym__);
      if (lookahead == '_') ADVANCE(10);
      END_STATE();
    case 9:
      ACCEPT_TOKEN(anon_sym_STAR_STAR);
      END_STATE();
    case 10:
      ACCEPT_TOKEN(anon_sym___);
      END_STATE();
    case 11:
      ACCEPT_TOKEN(anon_sym_BQUOTE);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(aux_sym_code_span_token1);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(12);
      if (lookahead != 0 &&
          lookahead != '`') ADVANCE(13);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(aux_sym_code_span_token1);
      if (lookahead != 0 &&
          lookahead != '`') ADVANCE(13);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(aux_sym_text_token1);
      if (lookahead == '\t' ||
          lookahead == 0x0b ||
          lookahead == '\f' ||
          lookahead == ' ') ADVANCE(14);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != '*' &&
          lookahead != '[' &&
          lookahead != '_' &&
          lookahead != '`') ADVANCE(15);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(aux_sym_text_token1);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '*' &&
          lookahead != '[' &&
          lookahead != '_' &&
          lookahead != '`') ADVANCE(15);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(aux_sym_text_token2);
      if (lookahead == '*') ADVANCE(9);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(aux_sym_text_token2);
      if (lookahead == '_') ADVANCE(10);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 0},
  [3] = {.lex_state = 0},
  [4] = {.lex_state = 0},
  [5] = {.lex_state = 0},
  [6] = {.lex_state = 0},
  [7] = {.lex_state = 0},
  [8] = {.lex_state = 0},
  [9] = {.lex_state = 0},
  [10] = {.lex_state = 0},
  [11] = {.lex_state = 0},
  [12] = {.lex_state = 0},
  [13] = {.lex_state = 0},
  [14] = {.lex_state = 0},
  [15] = {.lex_state = 0},
  [16] = {.lex_state = 0},
  [17] = {.lex_state = 0},
  [18] = {.lex_state = 0},
  [19] = {.lex_state = 0},
  [20] = {.lex_state = 0},
  [21] = {.lex_state = 0},
  [22] = {.lex_state = 0},
  [23] = {.lex_state = 0},
  [24] = {.lex_state = 0},
  [25] = {.lex_state = 0},
  [26] = {.lex_state = 0},
  [27] = {.lex_state = 0},
  [28] = {.lex_state = 0},
  [29] = {.lex_state = 1},
  [30] = {.lex_state = 1},
  [31] = {.lex_state = 2},
  [32] = {.lex_state = 1},
  [33] = {.lex_state = 2},
  [34] = {.lex_state = 2},
  [35] = {.lex_state = 3},
  [36] = {.lex_state = 3},
  [37] = {.lex_state = 3},
  [38] = {.lex_state = 3},
  [39] = {.lex_state = 0},
  [40] = {.lex_state = 0},
  [41] = {.lex_state = 0},
  [42] = {.lex_state = 0},
  [43] = {.lex_state = 0},
  [44] = {.lex_state = 0},
  [45] = {.lex_state = 0},
  [46] = {.lex_state = 2},
  [47] = {.lex_state = 0},
  [48] = {.lex_state = 0},
  [49] = {.lex_state = 1},
  [50] = {.lex_state = 2},
  [51] = {.lex_state = 1},
  [52] = {.lex_state = 0},
  [53] = {.lex_state = 1},
  [54] = {.lex_state = 2},
  [55] = {.lex_state = 2},
  [56] = {.lex_state = 1},
  [57] = {.lex_state = 4},
  [58] = {.lex_state = 4},
  [59] = {.lex_state = 4},
  [60] = {.lex_state = 4},
  [61] = {.lex_state = 5},
  [62] = {.lex_state = 5},
  [63] = {.lex_state = 5},
  [64] = {.lex_state = 0},
  [65] = {.lex_state = 5},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_STAR] = ACTIONS(1),
    [anon_sym__] = ACTIONS(1),
    [anon_sym_STAR_STAR] = ACTIONS(1),
    [anon_sym___] = ACTIONS(1),
    [anon_sym_BQUOTE] = ACTIONS(1),
    [aux_sym_text_token1] = ACTIONS(1),
    [aux_sym_text_token2] = ACTIONS(1),
  },
  [1] = {
    [sym_inline] = STATE(64),
    [sym__inline_element] = STATE(2),
    [sym_emphasis] = STATE(2),
    [sym_strong_emphasis] = STATE(2),
    [sym_code_span] = STATE(2),
    [sym_text] = STATE(2),
    [aux_sym_inline_repeat1] = STATE(2),
    [aux_sym_text_repeat1] = STATE(40),
    [anon_sym_STAR] = ACTIONS(3),
    [anon_sym__] = ACTIONS(5),
    [anon_sym_STAR_STAR] = ACTIONS(7),
    [anon_sym___] = ACTIONS(9),
    [anon_sym_BQUOTE] = ACTIONS(11),
    [aux_sym_text_token1] = ACTIONS(13),
    [aux_sym_text_token2] = ACTIONS(15),
  },
  [2] = {
    [sym__inline_element] = STATE(3),
    [sym_emphasis] = STATE(3),
    [sym_strong_emphasis] = STATE(3),
    [sym_code_span] = STATE(3),
    [sym_text] = STATE(3),
    [aux_sym_inline_repeat1] = STATE(3),
    [aux_sym_text_repeat1] = STATE(40),
    [ts_builtin_sym_end] = ACTIONS(17),
    [anon_sym_STAR] = ACTIONS(3),
    [anon_sym__] = ACTIONS(5),
    [anon_sym_STAR_STAR] = ACTIONS(7),
    [anon_sym___] = ACTIONS(9),
    [anon_sym_BQUOTE] = ACTIONS(11),
    [aux_sym_text_token1] = ACTIONS(13),
    [aux_sym_text_token2] = ACTIONS(15),
  },
  [3] = {
    [sym__inline_element] = STATE(3),
    [sym_emphasis] = STATE(3),
    [sym_strong_emphasis] = STATE(3),
    [sym_code_span] = STATE(3),
    [sym_text] = STATE(3),
    [aux_sym_inline_repeat1] = STATE(3),
    [aux_sym_text_repeat1] = STATE(40),
    [ts_builtin_sym_end] = ACTIONS(19),
    [anon_sym_STAR] = ACTIONS(21),
    [anon_sym__] = ACTIONS(24),
    [anon_sym_STAR_STAR] = ACTIONS(27),
    [anon_sym___] = ACTIONS(30),
    [anon_sym_BQUOTE] = ACTIONS(33),
    [aux_sym_text_token1] = ACTIONS(36),
    [aux_sym_text_token2] = ACTIONS(39),
  },
  [4] = {
    [sym__inline_element] = STATE(21),
    [sym_emphasis] = STATE(21),
    [sym_strong_emphasis] = STATE(21),
    [sym_code_span] = STATE(21),
    [sym_text] = STATE(21),
    [aux_sym_inline_repeat1] = STATE(21),
    [aux_sym_text_repeat1] = STATE(41),
    [ts_builtin_sym_end] = ACTIONS(42),
    [anon_sym_STAR] = ACTIONS(44),
    [anon_sym__] = ACTIONS(44),
    [anon_sym_STAR_STAR] = ACTIONS(44),
    [anon_sym___] = ACTIONS(44),
    [anon_sym_BQUOTE] = ACTIONS(44),
    [aux_sym_text_token1] = ACTIONS(42),
    [aux_sym_text_token2] = ACTIONS(44),
  },
  [5] = {
    [sym__inline_element] = STATE(22),
    [sym_emphasis] = STATE(22),
    [sym_strong_emphasis] = STATE(22),
    [sym_code_span] = STATE(22),
    [sym_text] = STATE(22),
    [aux_sym_inline_repeat1] = STATE(22),
    [aux_sym_text_repeat1] = STATE(41),
    [ts_builtin_sym_end] = ACTIONS(42),
    [anon_sym_STAR] = ACTIONS(44),
    [anon_sym__] = ACTIONS(44),
    [anon_sym_STAR_STAR] = ACTIONS(44),
    [anon_sym___] = ACTIONS(44),
    [anon_sym_BQUOTE] = ACTIONS(44),
    [aux_sym_text_token1] = ACTIONS(42),
    [aux_sym_text_token2] = ACTIONS(44),
  },
  [6] = {
    [sym__inline_element] = STATE(8),
    [sym_emphasis] = STATE(8),
    [sym_strong_emphasis] = STATE(8),
    [sym_code_span] = STATE(8),
    [sym_text] = STATE(8),
    [aux_sym_inline_repeat1] = STATE(8),
    [aux_sym_text_repeat1] = STATE(41),
    [anon_sym_STAR] = ACTIONS(46),
    [anon_sym__] = ACTIONS(48),
    [anon_sym_STAR_STAR] = ACTIONS(50),
    [anon_sym___] = ACTIONS(52),
    [anon_sym_BQUOTE] = ACTIONS(54),
    [aux_sym_text_token1] = ACTIONS(56),
    [aux_sym_text_token2] = ACTIONS(58),
  },
  [7] = {
    [sym__inline_element] = STATE(22),
    [sym_emphasis] = STATE(22),
    [sym_strong_emphasis] = STATE(22),
    [sym_code_span] = STATE(22),
    [sym_text] = STATE(22),
    [aux_sym_inline_repeat1] = STATE(22),
    [aux_sym_text_repeat1] = STATE(41),
    [anon_sym_STAR] = ACTIONS(46),
    [anon_sym__] = ACTIONS(48),
    [anon_sym_STAR_STAR] = ACTIONS(50),
    [anon_sym___] = ACTIONS(52),
    [anon_sym_BQUOTE] = ACTIONS(54),
    [aux_sym_text_token1] = ACTIONS(56),
    [aux_sym_text_token2] = ACTIONS(58),
  },
  [8] = {
    [sym__inline_element] = STATE(11),
    [sym_emphasis] = STATE(11),
    [sym_strong_emphasis] = STATE(11),
    [sym_code_span] = STATE(11),
    [sym_text] = STATE(11),
    [aux_sym_inline_repeat1] = STATE(11),
    [aux_sym_text_repeat1] = STATE(41),
    [anon_sym_STAR] = ACTIONS(46),
    [anon_sym__] = ACTIONS(48),
    [anon_sym_STAR_STAR] = ACTIONS(60),
    [anon_sym___] = ACTIONS(52),
    [anon_sym_BQUOTE] = ACTIONS(54),
    [aux_sym_text_token1] = ACTIONS(56),
    [aux_sym_text_token2] = ACTIONS(58),
  },
  [9] = {
    [sym__inline_element] = STATE(11),
    [sym_emphasis] = STATE(11),
    [sym_strong_emphasis] = STATE(11),
    [sym_code_span] = STATE(11),
    [sym_text] = STATE(11),
    [aux_sym_inline_repeat1] = STATE(11),
    [aux_sym_text_repeat1] = STATE(41),
    [anon_sym_STAR] = ACTIONS(46),
    [anon_sym__] = ACTIONS(48),
    [anon_sym_STAR_STAR] = ACTIONS(50),
    [anon_sym___] = ACTIONS(62),
    [anon_sym_BQUOTE] = ACTIONS(54),
    [aux_sym_text_token1] = ACTIONS(56),
    [aux_sym_text_token2] = ACTIONS(58),
  },
  [10] = {
    [sym__inline_element] = STATE(9),
    [sym_emphasis] = STATE(9),
    [sym_strong_emphasis] = STATE(9),
    [sym_code_span] = STATE(9),
    [sym_text] = STATE(9),
    [aux_sym_inline_repeat1] = STATE(9),
    [aux_sym_text_repeat1] = STATE(41),
    [anon_sym_STAR] = ACTIONS(46),
    [anon_sym__] = ACTIONS(48),
    [anon_sym_STAR_STAR] = ACTIONS(50),
    [anon_sym___] = ACTIONS(52),
    [anon_sym_BQUOTE] = ACTIONS(54),
    [aux_sym_text_token1] = ACTIONS(56),
    [aux_sym_text_token2] = ACTIONS(58),
  },
  [11] = {
    [sym__inline_element] = STATE(11),
    [sym_emphasis] = STATE(11),
    [sym_strong_emphasis] = STATE(11),
    [sym_code_span] = STATE(11),
    [sym_text] = STATE(11),
    [aux_sym_inline_repeat1] = STATE(11),
    [aux_sym_text_repeat1] = STATE(41),
    [anon_sym_STAR] = ACTIONS(64),
    [anon_sym__] = ACTIONS(67),
    [anon_sym_STAR_STAR] = ACTIONS(70),
    [anon_sym___] = ACTIONS(73),
    [anon_sym_BQUOTE] = ACTIONS(76),
    [aux_sym_text_token1] = ACTIONS(79),
    [aux_sym_text_token2] = ACTIONS(82),
  },
  [12] = {
    [sym__inline_element] = STATE(21),
    [sym_emphasis] = STATE(21),
    [sym_strong_emphasis] = STATE(21),
    [sym_code_span] = STATE(21),
    [sym_text] = STATE(21),
    [aux_sym_inline_repeat1] = STATE(21),
    [aux_sym_text_repeat1] = STATE(41),
    [anon_sym_STAR] = ACTIONS(44),
    [anon_sym__] = ACTIONS(48),
    [anon_sym_STAR_STAR] = ACTIONS(44),
    [anon_sym___] = ACTIONS(44),
    [anon_sym_BQUOTE] = ACTIONS(44),
    [aux_sym_text_token1] = ACTIONS(42),
    [aux_sym_text_token2] = ACTIONS(44),
  },
  [13] = {
    [sym__inline_element] = STATE(22),
    [sym_emphasis] = STATE(22),
    [sym_strong_emphasis] = STATE(22),
    [sym_code_span] = STATE(22),
    [sym_text] = STATE(22),
    [aux_sym_inline_repeat1] = STATE(22),
    [aux_sym_text_repeat1] = STATE(41),
    [anon_sym_STAR] = ACTIONS(44),
    [anon_sym__] = ACTIONS(48),
    [anon_sym_STAR_STAR] = ACTIONS(44),
    [anon_sym___] = ACTIONS(44),
    [anon_sym_BQUOTE] = ACTIONS(44),
    [aux_sym_text_token1] = ACTIONS(42),
    [aux_sym_text_token2] = ACTIONS(44),
  },
  [14] = {
    [sym__inline_element] = STATE(22),
    [sym_emphasis] = STATE(22),
    [sym_strong_emphasis] = STATE(22),
    [sym_code_span] = STATE(22),
    [sym_text] = STATE(22),
    [aux_sym_inline_repeat1] = STATE(22),
    [aux_sym_text_repeat1] = STATE(41),
    [anon_sym_STAR] = ACTIONS(46),
    [anon_sym__] = ACTIONS(44),
    [anon_sym_STAR_STAR] = ACTIONS(44),
    [anon_sym___] = ACTIONS(44),
    [anon_sym_BQUOTE] = ACTIONS(44),
    [aux_sym_text_token1] = ACTIONS(42),
    [aux_sym_text_token2] = ACTIONS(44),
  },
  [15] = {
    [sym__inline_element] = STATE(21),
    [sym_emphasis] = STATE(21),
    [sym_strong_emphasis] = STATE(21),
    [sym_code_span] = STATE(21),
    [sym_text] = STATE(21),
    [aux_sym_inline_repeat1] = STATE(21),
    [aux_sym_text_repeat1] = STATE(41),
    [anon_sym_STAR] = ACTIONS(44),
    [anon_sym__] = ACTIONS(44),
    [anon_sym_STAR_STAR] = ACTIONS(44),
    [anon_sym___] = ACTIONS(44),
    [anon_sym_BQUOTE] = ACTIONS(44),
    [aux_sym_text_token1] = ACTIONS(42),
    [aux_sym_text_token2] = ACTIONS(44),
  },
  [16] = {
    [sym__inline_element] = STATE(22),
    [sym_emphasis] = STATE(22),
    [sym_strong_emphasis] = STATE(22),
    [sym_code_span] = STATE(22),
    [sym_text] = STATE(22),
    [aux_sym_inline_repeat1] = STATE(22),
    [aux_sym_text_repeat1] = STATE(41),
    [anon_sym_STAR] = ACTIONS(44),
    [anon_sym__] = ACTIONS(44),
    [anon_sym_STAR_STAR] = ACTIONS(44),
    [anon_sym___] = ACTIONS(44),
    [anon_sym_BQUOTE] = ACTIONS(44),
    [aux_sym_text_token1] = ACTIONS(42),
    [aux_sym_text_token2] = ACTIONS(44),
  },
  [17] = {
    [sym__inline_element] = STATE(11),
    [sym_emphasis] = STATE(11),
    [sym_strong_emphasis] = STATE(11),
    [sym_code_span] = STATE(11),
    [sym_text] = STATE(11),
    [aux_sym_inline_repeat1] = STATE(11),
    [aux_sym_text_repeat1] = STATE(41),
    [anon_sym_STAR] = ACTIONS(46),
    [anon_sym__] = ACTIONS(48),
    [anon_sym_STAR_STAR] = ACTIONS(85),
    [anon_sym___] = ACTIONS(52),
    [anon_sym_BQUOTE] = ACTIONS(54),
    [aux_sym_text_token1] = ACTIONS(56),
    [aux_sym_text_token2] = ACTIONS(58),
  },
  [18] = {
    [sym__inline_element] = STATE(11),
    [sym_emphasis] = STATE(11),
    [sym_strong_emphasis] = STATE(11),
    [sym_code_span] = STATE(11),
    [sym_text] = STATE(11),
    [aux_sym_inline_repeat1] = STATE(11),
    [aux_sym_text_repeat1] = STATE(41),
    [anon_sym_STAR] = ACTIONS(46),
    [anon_sym__] = ACTIONS(48),
    [anon_sym_STAR_STAR] = ACTIONS(50),
    [anon_sym___] = ACTIONS(87),
    [anon_sym_BQUOTE] = ACTIONS(54),
    [aux_sym_text_token1] = ACTIONS(56),
    [aux_sym_text_token2] = ACTIONS(58),
  },
  [19] = {
    [sym__inline_element] = STATE(11),
    [sym_emphasis] = STATE(11),
    [sym_strong_emphasis] = STATE(11),
    [sym_code_span] = STATE(11),
    [sym_text] = STATE(11),
    [aux_sym_inline_repeat1] = STATE(11),
    [aux_sym_text_repeat1] = STATE(41),
    [anon_sym_STAR] = ACTIONS(46),
    [anon_sym__] = ACTIONS(48),
    [anon_sym_STAR_STAR] = ACTIONS(89),
    [anon_sym___] = ACTIONS(52),
    [anon_sym_BQUOTE] = ACTIONS(54),
    [aux_sym_text_token1] = ACTIONS(56),
    [aux_sym_text_token2] = ACTIONS(58),
  },
  [20] = {
    [sym__inline_element] = STATE(11),
    [sym_emphasis] = STATE(11),
    [sym_strong_emphasis] = STATE(11),
    [sym_code_span] = STATE(11),
    [sym_text] = STATE(11),
    [aux_sym_inline_repeat1] = STATE(11),
    [aux_sym_text_repeat1] = STATE(41),
    [anon_sym_STAR] = ACTIONS(46),
    [anon_sym__] = ACTIONS(48),
    [anon_sym_STAR_STAR] = ACTIONS(50),
    [anon_sym___] = ACTIONS(91),
    [anon_sym_BQUOTE] = ACTIONS(54),
    [aux_sym_text_token1] = ACTIONS(56),
    [aux_sym_text_token2] = ACTIONS(58),
  },
  [21] = {
    [sym__inline_element] = STATE(11),
    [sym_emphasis] = STATE(11),
    [sym_strong_emphasis] = STATE(11),
    [sym_code_span] = STATE(11),
    [sym_text] = STATE(11),
    [aux_sym_inline_repeat1] = STATE(11),
    [aux_sym_text_repeat1] = STATE(41),
    [anon_sym_STAR] = ACTIONS(46),
    [anon_sym__] = ACTIONS(48),
    [anon_sym_STAR_STAR] = ACTIONS(93),
    [anon_sym___] = ACTIONS(52),
    [anon_sym_BQUOTE] = ACTIONS(54),
    [aux_sym_text_token1] = ACTIONS(56),
    [aux_sym_text_token2] = ACTIONS(58),
  },
  [22] = {
    [sym__inline_element] = STATE(11),
    [sym_emphasis] = STATE(11),
    [sym_strong_emphasis] = STATE(11),
    [sym_code_span] = STATE(11),
    [sym_text] = STATE(11),
    [aux_sym_inline_repeat1] = STATE(11),
    [aux_sym_text_repeat1] = STATE(41),
    [anon_sym_STAR] = ACTIONS(46),
    [anon_sym__] = ACTIONS(48),
    [anon_sym_STAR_STAR] = ACTIONS(50),
    [anon_sym___] = ACTIONS(95),
    [anon_sym_BQUOTE] = ACTIONS(54),
    [aux_sym_text_token1] = ACTIONS(56),
    [aux_sym_text_token2] = ACTIONS(58),
  },
  [23] = {
    [sym__inline_element] = STATE(17),
    [sym_emphasis] = STATE(17),
    [sym_strong_emphasis] = STATE(17),
    [sym_code_span] = STATE(17),
    [sym_text] = STATE(17),
    [aux_sym_inline_repeat1] = STATE(17),
    [aux_sym_text_repeat1] = STATE(41),
    [anon_sym_STAR] = ACTIONS(46),
    [anon_sym__] = ACTIONS(48),
    [anon_sym_STAR_STAR] = ACTIONS(50),
    [anon_sym___] = ACTIONS(52),
    [anon_sym_BQUOTE] = ACTIONS(54),
    [aux_sym_text_token1] = ACTIONS(56),
    [aux_sym_text_token2] = ACTIONS(58),
  },
  [24] = {
    [sym__inline_element] = STATE(18),
    [sym_emphasis] = STATE(18),
    [sym_strong_emphasis] = STATE(18),
    [sym_code_span] = STATE(18),
    [sym_text] = STATE(18),
    [aux_sym_inline_repeat1] = STATE(18),
    [aux_sym_text_repeat1] = STATE(41),
    [anon_sym_STAR] = ACTIONS(46),
    [anon_sym__] = ACTIONS(48),
    [anon_sym_STAR_STAR] = ACTIONS(50),
    [anon_sym___] = ACTIONS(52),
    [anon_sym_BQUOTE] = ACTIONS(54),
    [aux_sym_text_token1] = ACTIONS(56),
    [aux_sym_text_token2] = ACTIONS(58),
  },
  [25] = {
    [sym__inline_element] = STATE(19),
    [sym_emphasis] = STATE(19),
    [sym_strong_emphasis] = STATE(19),
    [sym_code_span] = STATE(19),
    [sym_text] = STATE(19),
    [aux_sym_inline_repeat1] = STATE(19),
    [aux_sym_text_repeat1] = STATE(41),
    [anon_sym_STAR] = ACTIONS(46),
    [anon_sym__] = ACTIONS(48),
    [anon_sym_STAR_STAR] = ACTIONS(50),
    [anon_sym___] = ACTIONS(52),
    [anon_sym_BQUOTE] = ACTIONS(54),
    [aux_sym_text_token1] = ACTIONS(56),
    [aux_sym_text_token2] = ACTIONS(58),
  },
  [26] = {
    [sym__inline_element] = STATE(20),
    [sym_emphasis] = STATE(20),
    [sym_strong_emphasis] = STATE(20),
    [sym_code_span] = STATE(20),
    [sym_text] = STATE(20),
    [aux_sym_inline_repeat1] = STATE(20),
    [aux_sym_text_repeat1] = STATE(41),
    [anon_sym_STAR] = ACTIONS(46),
    [anon_sym__] = ACTIONS(48),
    [anon_sym_STAR_STAR] = ACTIONS(50),
    [anon_sym___] = ACTIONS(52),
    [anon_sym_BQUOTE] = ACTIONS(54),
    [aux_sym_text_token1] = ACTIONS(56),
    [aux_sym_text_token2] = ACTIONS(58),
  },
  [27] = {
    [sym__inline_element] = STATE(21),
    [sym_emphasis] = STATE(21),
    [sym_strong_emphasis] = STATE(21),
    [sym_code_span] = STATE(21),
    [sym_text] = STATE(21),
    [aux_sym_inline_repeat1] = STATE(21),
    [aux_sym_text_repeat1] = STATE(41),
    [anon_sym_STAR] = ACTIONS(46),
    [anon_sym__] = ACTIONS(48),
    [anon_sym_STAR_STAR] = ACTIONS(50),
    [anon_sym___] = ACTIONS(52),
    [anon_sym_BQUOTE] = ACTIONS(54),
    [aux_sym_text_token1] = ACTIONS(56),
    [aux_sym_text_token2] = ACTIONS(58),
  },
  [28] = {
    [sym__inline_element] = STATE(21),
    [sym_emphasis] = STATE(21),
    [sym_strong_emphasis] = STATE(21),
    [sym_code_span] = STATE(21),
    [sym_text] = STATE(21),
    [aux_sym_inline_repeat1] = STATE(21),
    [aux_sym_text_repeat1] = STATE(41),
    [anon_sym_STAR] = ACTIONS(46),
    [anon_sym__] = ACTIONS(44),
    [anon_sym_STAR_STAR] = ACTIONS(44),
    [anon_sym___] = ACTIONS(44),
    [anon_sym_BQUOTE] = ACTIONS(44),
    [aux_sym_text_token1] = ACTIONS(42),
    [aux_sym_text_token2] = ACTIONS(44),
  },
  [29] = {
    [sym_strong_emphasis] = STATE(32),
    [sym__inline_no_star] = STATE(32),
    [sym_code_span] = STATE(32),
    [sym_text] = STATE(32),
    [aux_sym_emphasis_repeat1] = STATE(32),
    [aux_sym_text_repeat1] = STATE(49),
    [anon_sym_STAR] = ACTIONS(97),
    [anon_sym_STAR_STAR] = ACTIONS(99),
    [anon_sym___] = ACTIONS(101),
    [anon_sym_BQUOTE] = ACTIONS(103),
    [aux_sym_text_token1] = ACTIONS(105),
    [aux_sym_text_token2] = ACTIONS(107),
  },
  [30] = {
    [sym_strong_emphasis] = STATE(32),
    [sym__inline_no_star] = STATE(32),
    [sym_code_span] = STATE(32),
    [sym_text] = STATE(32),
    [aux_sym_emphasis_repeat1] = STATE(32),
    [aux_sym_text_repeat1] = STATE(49),
    [anon_sym_STAR] = ACTIONS(109),
    [anon_sym_STAR_STAR] = ACTIONS(99),
    [anon_sym___] = ACTIONS(101),
    [anon_sym_BQUOTE] = ACTIONS(103),
    [aux_sym_text_token1] = ACTIONS(105),
    [aux_sym_text_token2] = ACTIONS(107),
  },
  [31] = {
    [sym_strong_emphasis] = STATE(33),
    [sym__inline_no_underscore] = STATE(33),
    [sym_code_span] = STATE(33),
    [sym_text] = STATE(33),
    [aux_sym_emphasis_repeat2] = STATE(33),
    [aux_sym_text_repeat1] = STATE(46),
    [anon_sym__] = ACTIONS(109),
    [anon_sym_STAR_STAR] = ACTIONS(111),
    [anon_sym___] = ACTIONS(113),
    [anon_sym_BQUOTE] = ACTIONS(115),
    [aux_sym_text_token1] = ACTIONS(117),
    [aux_sym_text_token2] = ACTIONS(119),
  },
  [32] = {
    [sym_strong_emphasis] = STATE(32),
    [sym__inline_no_star] = STATE(32),
    [sym_code_span] = STATE(32),
    [sym_text] = STATE(32),
    [aux_sym_emphasis_repeat1] = STATE(32),
    [aux_sym_text_repeat1] = STATE(49),
    [anon_sym_STAR] = ACTIONS(121),
    [anon_sym_STAR_STAR] = ACTIONS(123),
    [anon_sym___] = ACTIONS(126),
    [anon_sym_BQUOTE] = ACTIONS(129),
    [aux_sym_text_token1] = ACTIONS(132),
    [aux_sym_text_token2] = ACTIONS(135),
  },
  [33] = {
    [sym_strong_emphasis] = STATE(33),
    [sym__inline_no_underscore] = STATE(33),
    [sym_code_span] = STATE(33),
    [sym_text] = STATE(33),
    [aux_sym_emphasis_repeat2] = STATE(33),
    [aux_sym_text_repeat1] = STATE(46),
    [anon_sym__] = ACTIONS(138),
    [anon_sym_STAR_STAR] = ACTIONS(140),
    [anon_sym___] = ACTIONS(143),
    [anon_sym_BQUOTE] = ACTIONS(146),
    [aux_sym_text_token1] = ACTIONS(149),
    [aux_sym_text_token2] = ACTIONS(152),
  },
  [34] = {
    [sym_strong_emphasis] = STATE(33),
    [sym__inline_no_underscore] = STATE(33),
    [sym_code_span] = STATE(33),
    [sym_text] = STATE(33),
    [aux_sym_emphasis_repeat2] = STATE(33),
    [aux_sym_text_repeat1] = STATE(46),
    [anon_sym__] = ACTIONS(97),
    [anon_sym_STAR_STAR] = ACTIONS(111),
    [anon_sym___] = ACTIONS(113),
    [anon_sym_BQUOTE] = ACTIONS(115),
    [aux_sym_text_token1] = ACTIONS(117),
    [aux_sym_text_token2] = ACTIONS(119),
  },
  [35] = {
    [sym_strong_emphasis] = STATE(34),
    [sym__inline_no_underscore] = STATE(34),
    [sym_code_span] = STATE(34),
    [sym_text] = STATE(34),
    [aux_sym_emphasis_repeat2] = STATE(34),
    [aux_sym_text_repeat1] = STATE(46),
    [anon_sym_STAR_STAR] = ACTIONS(111),
    [anon_sym___] = ACTIONS(113),
    [anon_sym_BQUOTE] = ACTIONS(115),
    [aux_sym_text_token1] = ACTIONS(117),
    [aux_sym_text_token2] = ACTIONS(119),
  },
  [36] = {
    [sym_strong_emphasis] = STATE(29),
    [sym__inline_no_star] = STATE(29),
    [sym_code_span] = STATE(29),
    [sym_text] = STATE(29),
    [aux_sym_emphasis_repeat1] = STATE(29),
    [aux_sym_text_repeat1] = STATE(49),
    [anon_sym_STAR_STAR] = ACTIONS(99),
    [anon_sym___] = ACTIONS(101),
    [anon_sym_BQUOTE] = ACTIONS(103),
    [aux_sym_text_token1] = ACTIONS(105),
    [aux_sym_text_token2] = ACTIONS(107),
  },
  [37] = {
    [sym_strong_emphasis] = STATE(31),
    [sym__inline_no_underscore] = STATE(31),
    [sym_code_span] = STATE(31),
    [sym_text] = STATE(31),
    [aux_sym_emphasis_repeat2] = STATE(31),
    [aux_sym_text_repeat1] = STATE(46),
    [anon_sym_STAR_STAR] = ACTIONS(111),
    [anon_sym___] = ACTIONS(113),
    [anon_sym_BQUOTE] = ACTIONS(115),
    [aux_sym_text_token1] = ACTIONS(117),
    [aux_sym_text_token2] = ACTIONS(119),
  },
  [38] = {
    [sym_strong_emphasis] = STATE(30),
    [sym__inline_no_star] = STATE(30),
    [sym_code_span] = STATE(30),
    [sym_text] = STATE(30),
    [aux_sym_emphasis_repeat1] = STATE(30),
    [aux_sym_text_repeat1] = STATE(49),
    [anon_sym_STAR_STAR] = ACTIONS(99),
    [anon_sym___] = ACTIONS(101),
    [anon_sym_BQUOTE] = ACTIONS(103),
    [aux_sym_text_token1] = ACTIONS(105),
    [aux_sym_text_token2] = ACTIONS(107),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 5,
    ACTIONS(155), 1,
      ts_builtin_sym_end,
    ACTIONS(159), 1,
      aux_sym_text_token1,
    ACTIONS(162), 1,
      aux_sym_text_token2,
    STATE(39), 1,
      aux_sym_text_repeat1,
    ACTIONS(157), 5,
      anon_sym_STAR,
      anon_sym__,
      anon_sym_STAR_STAR,
      anon_sym___,
      anon_sym_BQUOTE,
  [20] = 5,
    ACTIONS(165), 1,
      ts_builtin_sym_end,
    ACTIONS(169), 1,
      aux_sym_text_token1,
    ACTIONS(171), 1,
      aux_sym_text_token2,
    STATE(39), 1,
      aux_sym_text_repeat1,
    ACTIONS(167), 5,
      anon_sym_STAR,
      anon_sym__,
      anon_sym_STAR_STAR,
      anon_sym___,
      anon_sym_BQUOTE,
  [40] = 4,
    ACTIONS(173), 1,
      aux_sym_text_token1,
    ACTIONS(175), 1,
      aux_sym_text_token2,
    STATE(43), 1,
      aux_sym_text_repeat1,
    ACTIONS(167), 5,
      anon_sym_STAR,
      anon_sym__,
      anon_sym_STAR_STAR,
      anon_sym___,
      anon_sym_BQUOTE,
  [57] = 2,
    ACTIONS(177), 2,
      ts_builtin_sym_end,
      aux_sym_text_token1,
    ACTIONS(179), 6,
      anon_sym_STAR,
      anon_sym__,
      anon_sym_STAR_STAR,
      anon_sym___,
      anon_sym_BQUOTE,
      aux_sym_text_token2,
  [70] = 4,
    ACTIONS(181), 1,
      aux_sym_text_token1,
    ACTIONS(184), 1,
      aux_sym_text_token2,
    STATE(43), 1,
      aux_sym_text_repeat1,
    ACTIONS(157), 5,
      anon_sym_STAR,
      anon_sym__,
      anon_sym_STAR_STAR,
      anon_sym___,
      anon_sym_BQUOTE,
  [87] = 2,
    ACTIONS(187), 2,
      ts_builtin_sym_end,
      aux_sym_text_token1,
    ACTIONS(189), 6,
      anon_sym_STAR,
      anon_sym__,
      anon_sym_STAR_STAR,
      anon_sym___,
      anon_sym_BQUOTE,
      aux_sym_text_token2,
  [100] = 2,
    ACTIONS(191), 2,
      ts_builtin_sym_end,
      aux_sym_text_token1,
    ACTIONS(193), 6,
      anon_sym_STAR,
      anon_sym__,
      anon_sym_STAR_STAR,
      anon_sym___,
      anon_sym_BQUOTE,
      aux_sym_text_token2,
  [113] = 4,
    ACTIONS(195), 1,
      aux_sym_text_token1,
    ACTIONS(197), 1,
      aux_sym_text_token2,
    STATE(50), 1,
      aux_sym_text_repeat1,
    ACTIONS(167), 4,
      anon_sym__,
      anon_sym_STAR_STAR,
      anon_sym___,
      anon_sym_BQUOTE,
  [129] = 2,
    ACTIONS(191), 1,
      aux_sym_text_token1,
    ACTIONS(193), 6,
      anon_sym_STAR,
      anon_sym__,
      anon_sym_STAR_STAR,
      anon_sym___,
      anon_sym_BQUOTE,
      aux_sym_text_token2,
  [141] = 2,
    ACTIONS(187), 1,
      aux_sym_text_token1,
    ACTIONS(189), 6,
      anon_sym_STAR,
      anon_sym__,
      anon_sym_STAR_STAR,
      anon_sym___,
      anon_sym_BQUOTE,
      aux_sym_text_token2,
  [153] = 4,
    ACTIONS(199), 1,
      aux_sym_text_token1,
    ACTIONS(201), 1,
      aux_sym_text_token2,
    STATE(51), 1,
      aux_sym_text_repeat1,
    ACTIONS(167), 4,
      anon_sym_STAR,
      anon_sym_STAR_STAR,
      anon_sym___,
      anon_sym_BQUOTE,
  [169] = 4,
    ACTIONS(203), 1,
      aux_sym_text_token1,
    ACTIONS(206), 1,
      aux_sym_text_token2,
    STATE(50), 1,
      aux_sym_text_repeat1,
    ACTIONS(157), 4,
      anon_sym__,
      anon_sym_STAR_STAR,
      anon_sym___,
      anon_sym_BQUOTE,
  [185] = 4,
    ACTIONS(209), 1,
      aux_sym_text_token1,
    ACTIONS(212), 1,
      aux_sym_text_token2,
    STATE(51), 1,
      aux_sym_text_repeat1,
    ACTIONS(157), 4,
      anon_sym_STAR,
      anon_sym_STAR_STAR,
      anon_sym___,
      anon_sym_BQUOTE,
  [201] = 2,
    ACTIONS(177), 1,
      aux_sym_text_token1,
    ACTIONS(179), 6,
      anon_sym_STAR,
      anon_sym__,
      anon_sym_STAR_STAR,
      anon_sym___,
      anon_sym_BQUOTE,
      aux_sym_text_token2,
  [213] = 2,
    ACTIONS(191), 1,
      aux_sym_text_token1,
    ACTIONS(193), 5,
      anon_sym_STAR,
      anon_sym_STAR_STAR,
      anon_sym___,
      anon_sym_BQUOTE,
      aux_sym_text_token2,
  [224] = 2,
    ACTIONS(187), 1,
      aux_sym_text_token1,
    ACTIONS(189), 5,
      anon_sym__,
      anon_sym_STAR_STAR,
      anon_sym___,
      anon_sym_BQUOTE,
      aux_sym_text_token2,
  [235] = 2,
    ACTIONS(191), 1,
      aux_sym_text_token1,
    ACTIONS(193), 5,
      anon_sym__,
      anon_sym_STAR_STAR,
      anon_sym___,
      anon_sym_BQUOTE,
      aux_sym_text_token2,
  [246] = 2,
    ACTIONS(187), 1,
      aux_sym_text_token1,
    ACTIONS(189), 5,
      anon_sym_STAR,
      anon_sym_STAR_STAR,
      anon_sym___,
      anon_sym_BQUOTE,
      aux_sym_text_token2,
  [257] = 2,
    ACTIONS(215), 1,
      anon_sym_BQUOTE,
    ACTIONS(217), 1,
      aux_sym_code_span_token1,
  [264] = 2,
    ACTIONS(219), 1,
      anon_sym_BQUOTE,
    ACTIONS(221), 1,
      aux_sym_code_span_token1,
  [271] = 2,
    ACTIONS(223), 1,
      anon_sym_BQUOTE,
    ACTIONS(225), 1,
      aux_sym_code_span_token1,
  [278] = 2,
    ACTIONS(227), 1,
      anon_sym_BQUOTE,
    ACTIONS(229), 1,
      aux_sym_code_span_token1,
  [285] = 1,
    ACTIONS(231), 1,
      anon_sym_BQUOTE,
  [289] = 1,
    ACTIONS(233), 1,
      anon_sym_BQUOTE,
  [293] = 1,
    ACTIONS(235), 1,
      anon_sym_BQUOTE,
  [297] = 1,
    ACTIONS(237), 1,
      ts_builtin_sym_end,
  [301] = 1,
    ACTIONS(239), 1,
      anon_sym_BQUOTE,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(39)] = 0,
  [SMALL_STATE(40)] = 20,
  [SMALL_STATE(41)] = 40,
  [SMALL_STATE(42)] = 57,
  [SMALL_STATE(43)] = 70,
  [SMALL_STATE(44)] = 87,
  [SMALL_STATE(45)] = 100,
  [SMALL_STATE(46)] = 113,
  [SMALL_STATE(47)] = 129,
  [SMALL_STATE(48)] = 141,
  [SMALL_STATE(49)] = 153,
  [SMALL_STATE(50)] = 169,
  [SMALL_STATE(51)] = 185,
  [SMALL_STATE(52)] = 201,
  [SMALL_STATE(53)] = 213,
  [SMALL_STATE(54)] = 224,
  [SMALL_STATE(55)] = 235,
  [SMALL_STATE(56)] = 246,
  [SMALL_STATE(57)] = 257,
  [SMALL_STATE(58)] = 264,
  [SMALL_STATE(59)] = 271,
  [SMALL_STATE(60)] = 278,
  [SMALL_STATE(61)] = 285,
  [SMALL_STATE(62)] = 289,
  [SMALL_STATE(63)] = 293,
  [SMALL_STATE(64)] = 297,
  [SMALL_STATE(65)] = 301,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = false}}, SHIFT(36),
  [5] = {.entry = {.count = 1, .reusable = false}}, SHIFT(35),
  [7] = {.entry = {.count = 1, .reusable = false}}, SHIFT(6),
  [9] = {.entry = {.count = 1, .reusable = false}}, SHIFT(10),
  [11] = {.entry = {.count = 1, .reusable = false}}, SHIFT(60),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [15] = {.entry = {.count = 1, .reusable = false}}, SHIFT(40),
  [17] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_inline, 1, 0, 0),
  [19] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_inline_repeat1, 2, 0, 0),
  [21] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_inline_repeat1, 2, 0, 0), SHIFT_REPEAT(36),
  [24] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_inline_repeat1, 2, 0, 0), SHIFT_REPEAT(35),
  [27] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_inline_repeat1, 2, 0, 0), SHIFT_REPEAT(6),
  [30] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_inline_repeat1, 2, 0, 0), SHIFT_REPEAT(10),
  [33] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_inline_repeat1, 2, 0, 0), SHIFT_REPEAT(60),
  [36] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_inline_repeat1, 2, 0, 0), SHIFT_REPEAT(40),
  [39] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_inline_repeat1, 2, 0, 0), SHIFT_REPEAT(40),
  [42] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_strong_emphasis, 3, 0, 0),
  [44] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_strong_emphasis, 3, 0, 0),
  [46] = {.entry = {.count = 1, .reusable = false}}, SHIFT(38),
  [48] = {.entry = {.count = 1, .reusable = false}}, SHIFT(37),
  [50] = {.entry = {.count = 1, .reusable = false}}, SHIFT(27),
  [52] = {.entry = {.count = 1, .reusable = false}}, SHIFT(7),
  [54] = {.entry = {.count = 1, .reusable = false}}, SHIFT(59),
  [56] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [58] = {.entry = {.count = 1, .reusable = false}}, SHIFT(41),
  [60] = {.entry = {.count = 1, .reusable = false}}, SHIFT(4),
  [62] = {.entry = {.count = 1, .reusable = false}}, SHIFT(5),
  [64] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_inline_repeat1, 2, 0, 0), SHIFT_REPEAT(38),
  [67] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_inline_repeat1, 2, 0, 0), SHIFT_REPEAT(37),
  [70] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_inline_repeat1, 2, 0, 0), SHIFT_REPEAT(27),
  [73] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_inline_repeat1, 2, 0, 0), SHIFT_REPEAT(7),
  [76] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_inline_repeat1, 2, 0, 0), SHIFT_REPEAT(59),
  [79] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_inline_repeat1, 2, 0, 0), SHIFT_REPEAT(41),
  [82] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_inline_repeat1, 2, 0, 0), SHIFT_REPEAT(41),
  [85] = {.entry = {.count = 1, .reusable = false}}, SHIFT(12),
  [87] = {.entry = {.count = 1, .reusable = false}}, SHIFT(13),
  [89] = {.entry = {.count = 1, .reusable = false}}, SHIFT(28),
  [91] = {.entry = {.count = 1, .reusable = false}}, SHIFT(14),
  [93] = {.entry = {.count = 1, .reusable = false}}, SHIFT(15),
  [95] = {.entry = {.count = 1, .reusable = false}}, SHIFT(16),
  [97] = {.entry = {.count = 1, .reusable = false}}, SHIFT(42),
  [99] = {.entry = {.count = 1, .reusable = false}}, SHIFT(23),
  [101] = {.entry = {.count = 1, .reusable = false}}, SHIFT(24),
  [103] = {.entry = {.count = 1, .reusable = false}}, SHIFT(57),
  [105] = {.entry = {.count = 1, .reusable = true}}, SHIFT(49),
  [107] = {.entry = {.count = 1, .reusable = false}}, SHIFT(49),
  [109] = {.entry = {.count = 1, .reusable = false}}, SHIFT(52),
  [111] = {.entry = {.count = 1, .reusable = false}}, SHIFT(25),
  [113] = {.entry = {.count = 1, .reusable = false}}, SHIFT(26),
  [115] = {.entry = {.count = 1, .reusable = false}}, SHIFT(58),
  [117] = {.entry = {.count = 1, .reusable = true}}, SHIFT(46),
  [119] = {.entry = {.count = 1, .reusable = false}}, SHIFT(46),
  [121] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_emphasis_repeat1, 2, 0, 0),
  [123] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_emphasis_repeat1, 2, 0, 0), SHIFT_REPEAT(23),
  [126] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_emphasis_repeat1, 2, 0, 0), SHIFT_REPEAT(24),
  [129] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_emphasis_repeat1, 2, 0, 0), SHIFT_REPEAT(57),
  [132] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_emphasis_repeat1, 2, 0, 0), SHIFT_REPEAT(49),
  [135] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_emphasis_repeat1, 2, 0, 0), SHIFT_REPEAT(49),
  [138] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_emphasis_repeat2, 2, 0, 0),
  [140] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_emphasis_repeat2, 2, 0, 0), SHIFT_REPEAT(25),
  [143] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_emphasis_repeat2, 2, 0, 0), SHIFT_REPEAT(26),
  [146] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_emphasis_repeat2, 2, 0, 0), SHIFT_REPEAT(58),
  [149] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_emphasis_repeat2, 2, 0, 0), SHIFT_REPEAT(46),
  [152] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_emphasis_repeat2, 2, 0, 0), SHIFT_REPEAT(46),
  [155] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_text_repeat1, 2, 0, 0),
  [157] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_text_repeat1, 2, 0, 0),
  [159] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_text_repeat1, 2, 0, 0), SHIFT_REPEAT(39),
  [162] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_text_repeat1, 2, 0, 0), SHIFT_REPEAT(39),
  [165] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_text, 1, 0, 0),
  [167] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_text, 1, 0, 0),
  [169] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [171] = {.entry = {.count = 1, .reusable = false}}, SHIFT(39),
  [173] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
  [175] = {.entry = {.count = 1, .reusable = false}}, SHIFT(43),
  [177] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_emphasis, 3, 0, 0),
  [179] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_emphasis, 3, 0, 0),
  [181] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_text_repeat1, 2, 0, 0), SHIFT_REPEAT(43),
  [184] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_text_repeat1, 2, 0, 0), SHIFT_REPEAT(43),
  [187] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_code_span, 2, 0, 0),
  [189] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_code_span, 2, 0, 0),
  [191] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_code_span, 3, 0, 1),
  [193] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_code_span, 3, 0, 1),
  [195] = {.entry = {.count = 1, .reusable = true}}, SHIFT(50),
  [197] = {.entry = {.count = 1, .reusable = false}}, SHIFT(50),
  [199] = {.entry = {.count = 1, .reusable = true}}, SHIFT(51),
  [201] = {.entry = {.count = 1, .reusable = false}}, SHIFT(51),
  [203] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_text_repeat1, 2, 0, 0), SHIFT_REPEAT(50),
  [206] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_text_repeat1, 2, 0, 0), SHIFT_REPEAT(50),
  [209] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_text_repeat1, 2, 0, 0), SHIFT_REPEAT(51),
  [212] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_text_repeat1, 2, 0, 0), SHIFT_REPEAT(51),
  [215] = {.entry = {.count = 1, .reusable = false}}, SHIFT(56),
  [217] = {.entry = {.count = 1, .reusable = true}}, SHIFT(61),
  [219] = {.entry = {.count = 1, .reusable = false}}, SHIFT(54),
  [221] = {.entry = {.count = 1, .reusable = true}}, SHIFT(62),
  [223] = {.entry = {.count = 1, .reusable = false}}, SHIFT(48),
  [225] = {.entry = {.count = 1, .reusable = true}}, SHIFT(63),
  [227] = {.entry = {.count = 1, .reusable = false}}, SHIFT(44),
  [229] = {.entry = {.count = 1, .reusable = true}}, SHIFT(65),
  [231] = {.entry = {.count = 1, .reusable = true}}, SHIFT(53),
  [233] = {.entry = {.count = 1, .reusable = true}}, SHIFT(55),
  [235] = {.entry = {.count = 1, .reusable = true}}, SHIFT(47),
  [237] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [239] = {.entry = {.count = 1, .reusable = true}}, SHIFT(45),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_pandoc_markdown_inline(void) {
  static const TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
