#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 113
#define LARGE_STATE_COUNT 4
#define SYMBOL_COUNT 50
#define ALIAS_COUNT 1
#define TOKEN_COUNT 22
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 5
#define MAX_ALIAS_SEQUENCE_LENGTH 6
#define PRODUCTION_ID_COUNT 10

enum ts_symbol_identifiers {
  aux_sym_atx_heading_token1 = 1,
  aux_sym_atx_heading_token2 = 2,
  aux_sym_setext_heading_token1 = 3,
  aux_sym_setext_heading_token2 = 4,
  aux_sym_block_quote_line_token1 = 5,
  anon_sym_STAR = 6,
  anon_sym__ = 7,
  anon_sym_STAR_STAR = 8,
  anon_sym___ = 9,
  anon_sym_BQUOTE = 10,
  aux_sym_code_span_token1 = 11,
  aux_sym_text_token1 = 12,
  aux_sym_text_token2 = 13,
  aux_sym_fenced_code_block_token1 = 14,
  aux_sym_fenced_code_block_token2 = 15,
  sym_language = 16,
  aux_sym_list_item_token1 = 17,
  aux_sym_list_item_token2 = 18,
  aux_sym_thematic_break_token1 = 19,
  aux_sym_thematic_break_token2 = 20,
  aux_sym_thematic_break_token3 = 21,
  sym_document = 22,
  sym__block = 23,
  sym_atx_heading = 24,
  sym_setext_heading = 25,
  sym_block_quote = 26,
  sym_block_quote_line = 27,
  sym_paragraph = 28,
  sym_inline = 29,
  sym__inline_element = 30,
  sym_emphasis = 31,
  sym_strong_emphasis = 32,
  sym__inline_no_star = 33,
  sym__inline_no_underscore = 34,
  sym_code_span = 35,
  sym_text = 36,
  sym_fenced_code_block = 37,
  sym_list = 38,
  sym_list_item = 39,
  sym_thematic_break = 40,
  sym_blank_line = 41,
  aux_sym_document_repeat1 = 42,
  aux_sym_block_quote_repeat1 = 43,
  aux_sym_inline_repeat1 = 44,
  aux_sym_emphasis_repeat1 = 45,
  aux_sym_emphasis_repeat2 = 46,
  aux_sym_text_repeat1 = 47,
  aux_sym_fenced_code_block_repeat1 = 48,
  aux_sym_list_repeat1 = 49,
  alias_sym_code_fence_content = 50,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [aux_sym_atx_heading_token1] = "atx_heading_marker",
  [aux_sym_atx_heading_token2] = "atx_heading_token2",
  [aux_sym_setext_heading_token1] = "setext_heading_marker",
  [aux_sym_setext_heading_token2] = "setext_heading_marker",
  [aux_sym_block_quote_line_token1] = "block_quote_marker",
  [anon_sym_STAR] = "*",
  [anon_sym__] = "_",
  [anon_sym_STAR_STAR] = "**",
  [anon_sym___] = "__",
  [anon_sym_BQUOTE] = "`",
  [aux_sym_code_span_token1] = "code_span_content",
  [aux_sym_text_token1] = "text_token1",
  [aux_sym_text_token2] = "text_token2",
  [aux_sym_fenced_code_block_token1] = "fenced_code_block_delimiter",
  [aux_sym_fenced_code_block_token2] = "fenced_code_block_token2",
  [sym_language] = "language",
  [aux_sym_list_item_token1] = "list_marker",
  [aux_sym_list_item_token2] = "list_marker",
  [aux_sym_thematic_break_token1] = "thematic_break_token1",
  [aux_sym_thematic_break_token2] = "thematic_break_token2",
  [aux_sym_thematic_break_token3] = "thematic_break_token3",
  [sym_document] = "document",
  [sym__block] = "_block",
  [sym_atx_heading] = "atx_heading",
  [sym_setext_heading] = "setext_heading",
  [sym_block_quote] = "block_quote",
  [sym_block_quote_line] = "block_quote_line",
  [sym_paragraph] = "paragraph",
  [sym_inline] = "inline",
  [sym__inline_element] = "_inline_element",
  [sym_emphasis] = "emphasis",
  [sym_strong_emphasis] = "strong_emphasis",
  [sym__inline_no_star] = "_inline_no_star",
  [sym__inline_no_underscore] = "_inline_no_underscore",
  [sym_code_span] = "code_span",
  [sym_text] = "text",
  [sym_fenced_code_block] = "fenced_code_block",
  [sym_list] = "list",
  [sym_list_item] = "list_item",
  [sym_thematic_break] = "thematic_break",
  [sym_blank_line] = "blank_line",
  [aux_sym_document_repeat1] = "document_repeat1",
  [aux_sym_block_quote_repeat1] = "block_quote_repeat1",
  [aux_sym_inline_repeat1] = "inline_repeat1",
  [aux_sym_emphasis_repeat1] = "emphasis_repeat1",
  [aux_sym_emphasis_repeat2] = "emphasis_repeat2",
  [aux_sym_text_repeat1] = "text_repeat1",
  [aux_sym_fenced_code_block_repeat1] = "fenced_code_block_repeat1",
  [aux_sym_list_repeat1] = "list_repeat1",
  [alias_sym_code_fence_content] = "code_fence_content",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [aux_sym_atx_heading_token1] = aux_sym_atx_heading_token1,
  [aux_sym_atx_heading_token2] = aux_sym_atx_heading_token2,
  [aux_sym_setext_heading_token1] = aux_sym_setext_heading_token1,
  [aux_sym_setext_heading_token2] = aux_sym_setext_heading_token1,
  [aux_sym_block_quote_line_token1] = aux_sym_block_quote_line_token1,
  [anon_sym_STAR] = anon_sym_STAR,
  [anon_sym__] = anon_sym__,
  [anon_sym_STAR_STAR] = anon_sym_STAR_STAR,
  [anon_sym___] = anon_sym___,
  [anon_sym_BQUOTE] = anon_sym_BQUOTE,
  [aux_sym_code_span_token1] = aux_sym_code_span_token1,
  [aux_sym_text_token1] = aux_sym_text_token1,
  [aux_sym_text_token2] = aux_sym_text_token2,
  [aux_sym_fenced_code_block_token1] = aux_sym_fenced_code_block_token1,
  [aux_sym_fenced_code_block_token2] = aux_sym_fenced_code_block_token2,
  [sym_language] = sym_language,
  [aux_sym_list_item_token1] = aux_sym_list_item_token1,
  [aux_sym_list_item_token2] = aux_sym_list_item_token1,
  [aux_sym_thematic_break_token1] = aux_sym_thematic_break_token1,
  [aux_sym_thematic_break_token2] = aux_sym_thematic_break_token2,
  [aux_sym_thematic_break_token3] = aux_sym_thematic_break_token3,
  [sym_document] = sym_document,
  [sym__block] = sym__block,
  [sym_atx_heading] = sym_atx_heading,
  [sym_setext_heading] = sym_setext_heading,
  [sym_block_quote] = sym_block_quote,
  [sym_block_quote_line] = sym_block_quote_line,
  [sym_paragraph] = sym_paragraph,
  [sym_inline] = sym_inline,
  [sym__inline_element] = sym__inline_element,
  [sym_emphasis] = sym_emphasis,
  [sym_strong_emphasis] = sym_strong_emphasis,
  [sym__inline_no_star] = sym__inline_no_star,
  [sym__inline_no_underscore] = sym__inline_no_underscore,
  [sym_code_span] = sym_code_span,
  [sym_text] = sym_text,
  [sym_fenced_code_block] = sym_fenced_code_block,
  [sym_list] = sym_list,
  [sym_list_item] = sym_list_item,
  [sym_thematic_break] = sym_thematic_break,
  [sym_blank_line] = sym_blank_line,
  [aux_sym_document_repeat1] = aux_sym_document_repeat1,
  [aux_sym_block_quote_repeat1] = aux_sym_block_quote_repeat1,
  [aux_sym_inline_repeat1] = aux_sym_inline_repeat1,
  [aux_sym_emphasis_repeat1] = aux_sym_emphasis_repeat1,
  [aux_sym_emphasis_repeat2] = aux_sym_emphasis_repeat2,
  [aux_sym_text_repeat1] = aux_sym_text_repeat1,
  [aux_sym_fenced_code_block_repeat1] = aux_sym_fenced_code_block_repeat1,
  [aux_sym_list_repeat1] = aux_sym_list_repeat1,
  [alias_sym_code_fence_content] = alias_sym_code_fence_content,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [aux_sym_atx_heading_token1] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_atx_heading_token2] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_setext_heading_token1] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_setext_heading_token2] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_block_quote_line_token1] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_STAR] = {
    .visible = true,
    .named = false,
  },
  [anon_sym__] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_STAR_STAR] = {
    .visible = true,
    .named = false,
  },
  [anon_sym___] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_BQUOTE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_code_span_token1] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_text_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_text_token2] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_fenced_code_block_token1] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_fenced_code_block_token2] = {
    .visible = false,
    .named = false,
  },
  [sym_language] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_list_item_token1] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_list_item_token2] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_thematic_break_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_thematic_break_token2] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_thematic_break_token3] = {
    .visible = false,
    .named = false,
  },
  [sym_document] = {
    .visible = true,
    .named = true,
  },
  [sym__block] = {
    .visible = false,
    .named = true,
  },
  [sym_atx_heading] = {
    .visible = true,
    .named = true,
  },
  [sym_setext_heading] = {
    .visible = true,
    .named = true,
  },
  [sym_block_quote] = {
    .visible = true,
    .named = true,
  },
  [sym_block_quote_line] = {
    .visible = true,
    .named = true,
  },
  [sym_paragraph] = {
    .visible = true,
    .named = true,
  },
  [sym_inline] = {
    .visible = true,
    .named = true,
  },
  [sym__inline_element] = {
    .visible = false,
    .named = true,
  },
  [sym_emphasis] = {
    .visible = true,
    .named = true,
  },
  [sym_strong_emphasis] = {
    .visible = true,
    .named = true,
  },
  [sym__inline_no_star] = {
    .visible = false,
    .named = true,
  },
  [sym__inline_no_underscore] = {
    .visible = false,
    .named = true,
  },
  [sym_code_span] = {
    .visible = true,
    .named = true,
  },
  [sym_text] = {
    .visible = true,
    .named = true,
  },
  [sym_fenced_code_block] = {
    .visible = true,
    .named = true,
  },
  [sym_list] = {
    .visible = true,
    .named = true,
  },
  [sym_list_item] = {
    .visible = true,
    .named = true,
  },
  [sym_thematic_break] = {
    .visible = true,
    .named = true,
  },
  [sym_blank_line] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_document_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_block_quote_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_inline_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_emphasis_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_emphasis_repeat2] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_text_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_fenced_code_block_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_list_repeat1] = {
    .visible = false,
    .named = false,
  },
  [alias_sym_code_fence_content] = {
    .visible = true,
    .named = true,
  },
};

enum ts_field_identifiers {
  field_content = 1,
  field_delimiter = 2,
  field_language = 3,
  field_marker = 4,
  field_underline = 5,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_content] = "content",
  [field_delimiter] = "delimiter",
  [field_language] = "language",
  [field_marker] = "marker",
  [field_underline] = "underline",
};

static const TSFieldMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 1},
  [2] = {.index = 1, .length = 1},
  [3] = {.index = 2, .length = 2},
  [4] = {.index = 4, .length = 1},
  [5] = {.index = 5, .length = 2},
  [6] = {.index = 7, .length = 2},
  [7] = {.index = 9, .length = 3},
  [8] = {.index = 12, .length = 3},
  [9] = {.index = 15, .length = 4},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_marker, 0},
  [1] =
    {field_content, 0},
  [2] =
    {field_content, 1},
    {field_marker, 0},
  [4] =
    {field_content, 1},
  [5] =
    {field_delimiter, 0},
    {field_delimiter, 2},
  [7] =
    {field_content, 0},
    {field_underline, 2},
  [9] =
    {field_content, 2},
    {field_delimiter, 0},
    {field_delimiter, 3},
  [12] =
    {field_delimiter, 0},
    {field_delimiter, 3},
    {field_language, 1},
  [15] =
    {field_content, 3},
    {field_delimiter, 0},
    {field_delimiter, 4},
    {field_language, 1},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
  [7] = {
    [2] = alias_sym_code_fence_content,
  },
  [9] = {
    [3] = alias_sym_code_fence_content,
  },
};

static const uint16_t ts_non_terminal_alias_map[] = {
  aux_sym_fenced_code_block_repeat1, 2,
    aux_sym_fenced_code_block_repeat1,
    alias_sym_code_fence_content,
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 33,
  [36] = 32,
  [37] = 37,
  [38] = 30,
  [39] = 31,
  [40] = 30,
  [41] = 31,
  [42] = 30,
  [43] = 31,
  [44] = 32,
  [45] = 37,
  [46] = 37,
  [47] = 32,
  [48] = 37,
  [49] = 34,
  [50] = 33,
  [51] = 34,
  [52] = 33,
  [53] = 34,
  [54] = 29,
  [55] = 55,
  [56] = 56,
  [57] = 55,
  [58] = 58,
  [59] = 59,
  [60] = 56,
  [61] = 61,
  [62] = 62,
  [63] = 62,
  [64] = 61,
  [65] = 65,
  [66] = 66,
  [67] = 67,
  [68] = 65,
  [69] = 69,
  [70] = 66,
  [71] = 71,
  [72] = 67,
  [73] = 65,
  [74] = 66,
  [75] = 69,
  [76] = 71,
  [77] = 65,
  [78] = 66,
  [79] = 71,
  [80] = 67,
  [81] = 71,
  [82] = 67,
  [83] = 83,
  [84] = 84,
  [85] = 85,
  [86] = 86,
  [87] = 87,
  [88] = 88,
  [89] = 11,
  [90] = 90,
  [91] = 91,
  [92] = 91,
  [93] = 91,
  [94] = 94,
  [95] = 91,
  [96] = 96,
  [97] = 97,
  [98] = 98,
  [99] = 99,
  [100] = 96,
  [101] = 101,
  [102] = 102,
  [103] = 96,
  [104] = 104,
  [105] = 105,
  [106] = 106,
  [107] = 107,
  [108] = 108,
  [109] = 109,
  [110] = 96,
  [111] = 111,
  [112] = 112,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(19);
      ADVANCE_MAP(
        '\n', 26,
        '\r', 1,
        '#', 24,
        '*', 36,
        '+', 52,
        '-', 33,
        '=', 31,
        '>', 35,
        '_', 38,
        '`', 45,
        '\t', 48,
        0x0b, 48,
        '\f', 48,
        ' ', 48,
      );
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(51);
      if (lookahead != 0) ADVANCE(54);
      END_STATE();
    case 1:
      ADVANCE_MAP(
        '\n', 26,
        '\r', 1,
        '#', 24,
        '*', 36,
        '+', 52,
        '-', 33,
        '=', 31,
        '>', 35,
        '_', 38,
        '`', 45,
        '\t', 48,
        0x0b, 48,
        '\f', 48,
        ' ', 48,
      );
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(51);
      if (lookahead != 0) ADVANCE(54);
      END_STATE();
    case 2:
      ADVANCE_MAP(
        '\n', 27,
        '\r', 2,
        '*', 37,
        '>', 55,
        '_', 39,
        '`', 44,
        '\t', 49,
        0x0b, 49,
        '\f', 49,
        ' ', 49,
      );
      if (lookahead != 0 &&
          lookahead != '#' &&
          lookahead != '-') ADVANCE(54);
      END_STATE();
    case 3:
      if (lookahead == '\n') ADVANCE(28);
      if (lookahead == '\r') ADVANCE(3);
      if (('\t' <= lookahead && lookahead <= '\f') ||
          lookahead == ' ') SKIP(3);
      END_STATE();
    case 4:
      ADVANCE_MAP(
        '\n', 29,
        '\r', 4,
        '#', 24,
        '*', 36,
        '+', 52,
        '-', 10,
        '>', 35,
        '_', 38,
        '`', 45,
        '\t', 50,
        0x0b, 50,
        '\f', 50,
        ' ', 50,
      );
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(51);
      if (lookahead != 0) ADVANCE(54);
      END_STATE();
    case 5:
      if (lookahead == '\n') ADVANCE(30);
      if (lookahead == '\r') ADVANCE(5);
      if (('\t' <= lookahead && lookahead <= '\f') ||
          lookahead == ' ') ADVANCE(64);
      if (lookahead != 0) ADVANCE(65);
      END_STATE();
    case 6:
      if (lookahead == '*') ADVANCE(37);
      if (lookahead == '>') ADVANCE(55);
      if (lookahead == '_') ADVANCE(57);
      if (lookahead == '`') ADVANCE(44);
      if (lookahead == '\n' ||
          lookahead == '\r') SKIP(6);
      if (('\t' <= lookahead && lookahead <= '\f') ||
          lookahead == ' ') ADVANCE(53);
      if (lookahead != 0 &&
          lookahead != '#' &&
          lookahead != '-') ADVANCE(54);
      END_STATE();
    case 7:
      if (lookahead == '*') ADVANCE(37);
      if (lookahead == '>') ADVANCE(55);
      if (lookahead == '_') ADVANCE(39);
      if (lookahead == '`') ADVANCE(44);
      if (lookahead == '\n' ||
          lookahead == '\r') SKIP(7);
      if (('\t' <= lookahead && lookahead <= '\f') ||
          lookahead == ' ') ADVANCE(53);
      if (lookahead != 0 &&
          lookahead != '#' &&
          lookahead != '-') ADVANCE(54);
      END_STATE();
    case 8:
      if (lookahead == '*') ADVANCE(56);
      if (lookahead == '>') ADVANCE(55);
      if (lookahead == '_') ADVANCE(57);
      if (lookahead == '`') ADVANCE(44);
      if (lookahead == '\n' ||
          lookahead == '\r') SKIP(8);
      if (('\t' <= lookahead && lookahead <= '\f') ||
          lookahead == ' ') ADVANCE(53);
      if (lookahead != 0 &&
          lookahead != '#' &&
          lookahead != '-') ADVANCE(54);
      END_STATE();
    case 9:
      if (lookahead == '*') ADVANCE(56);
      if (lookahead == '>') ADVANCE(55);
      if (lookahead == '_') ADVANCE(39);
      if (lookahead == '`') ADVANCE(44);
      if (lookahead == '\n' ||
          lookahead == '\r') SKIP(9);
      if (('\t' <= lookahead && lookahead <= '\f') ||
          lookahead == ' ') ADVANCE(53);
      if (lookahead != 0 &&
          lookahead != '#' &&
          lookahead != '-') ADVANCE(54);
      END_STATE();
    case 10:
      if (lookahead == '-') ADVANCE(11);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(66);
      END_STATE();
    case 11:
      if (lookahead == '-') ADVANCE(68);
      END_STATE();
    case 12:
      if (lookahead == '.') ADVANCE(17);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(12);
      END_STATE();
    case 13:
      if (lookahead == '`') ADVANCE(58);
      END_STATE();
    case 14:
      if (lookahead == '`') ADVANCE(44);
      if (lookahead == '\n' ||
          lookahead == '\r') SKIP(14);
      if (('\t' <= lookahead && lookahead <= '\f') ||
          lookahead == ' ') ADVANCE(46);
      if (lookahead != 0) ADVANCE(47);
      END_STATE();
    case 15:
      if (lookahead == '`') ADVANCE(44);
      if (lookahead == '*' ||
          lookahead == '+' ||
          lookahead == '-') ADVANCE(16);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(15);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(12);
      END_STATE();
    case 16:
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(66);
      END_STATE();
    case 17:
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(67);
      END_STATE();
    case 18:
      if (eof) ADVANCE(19);
      ADVANCE_MAP(
        '\n', 29,
        '\r', 4,
        '#', 24,
        '*', 36,
        '+', 52,
        '-', 10,
        '>', 35,
        '_', 38,
        '`', 45,
        '\t', 50,
        0x0b, 50,
        '\f', 50,
        ' ', 50,
      );
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(51);
      if (lookahead != 0) ADVANCE(54);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(aux_sym_atx_heading_token1);
      if (lookahead == '#') ADVANCE(25);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(25);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(aux_sym_atx_heading_token1);
      if (lookahead == '#') ADVANCE(20);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(25);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(aux_sym_atx_heading_token1);
      if (lookahead == '#') ADVANCE(21);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(25);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(aux_sym_atx_heading_token1);
      if (lookahead == '#') ADVANCE(22);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(25);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(aux_sym_atx_heading_token1);
      if (lookahead == '#') ADVANCE(23);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(25);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(aux_sym_atx_heading_token1);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(25);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(aux_sym_atx_heading_token2);
      if (lookahead == '\n') ADVANCE(26);
      if (lookahead == '\r') ADVANCE(1);
      if (lookahead == '#') ADVANCE(24);
      if (lookahead == '>') ADVANCE(35);
      if (('\t' <= lookahead && lookahead <= '\f') ||
          lookahead == ' ') ADVANCE(48);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(aux_sym_atx_heading_token2);
      if (lookahead == '\n') ADVANCE(27);
      if (lookahead == '\r') ADVANCE(2);
      if (('\t' <= lookahead && lookahead <= '\f') ||
          lookahead == ' ') ADVANCE(49);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(aux_sym_atx_heading_token2);
      if (lookahead == '\n') ADVANCE(28);
      if (lookahead == '\r') ADVANCE(3);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(aux_sym_atx_heading_token2);
      if (lookahead == '\n') ADVANCE(29);
      if (lookahead == '\r') ADVANCE(4);
      if (lookahead == '#') ADVANCE(24);
      if (lookahead == '>') ADVANCE(35);
      if (('\t' <= lookahead && lookahead <= '\f') ||
          lookahead == ' ') ADVANCE(50);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(aux_sym_atx_heading_token2);
      if (lookahead == '\n') ADVANCE(30);
      if (lookahead == '\r') ADVANCE(5);
      if (('\t' <= lookahead && lookahead <= '\f') ||
          lookahead == ' ') ADVANCE(64);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(aux_sym_setext_heading_token1);
      if (lookahead == '=') ADVANCE(31);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '#' &&
          lookahead != '*' &&
          lookahead != '-' &&
          lookahead != '=' &&
          lookahead != '>' &&
          lookahead != '_' &&
          lookahead != '`') ADVANCE(54);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(aux_sym_setext_heading_token2);
      if (lookahead == '-') ADVANCE(32);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(aux_sym_setext_heading_token2);
      if (lookahead == '-') ADVANCE(32);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(66);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(aux_sym_block_quote_line_token1);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(aux_sym_block_quote_line_token1);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(34);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(anon_sym_STAR);
      if (lookahead == '*') ADVANCE(41);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(66);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(anon_sym_STAR);
      if (lookahead == '*') ADVANCE(40);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(anon_sym__);
      if (lookahead == '_') ADVANCE(43);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(anon_sym__);
      if (lookahead == '_') ADVANCE(42);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(anon_sym_STAR_STAR);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(anon_sym_STAR_STAR);
      if (lookahead == '*') ADVANCE(69);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(anon_sym___);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(anon_sym___);
      if (lookahead == '_') ADVANCE(70);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(anon_sym_BQUOTE);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(anon_sym_BQUOTE);
      if (lookahead == '`') ADVANCE(13);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(aux_sym_code_span_token1);
      if (lookahead == '\t' ||
          lookahead == 0x0b ||
          lookahead == '\f' ||
          lookahead == ' ') ADVANCE(46);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != '`') ADVANCE(47);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(aux_sym_code_span_token1);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '`') ADVANCE(47);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(aux_sym_text_token1);
      ADVANCE_MAP(
        '\n', 26,
        '\r', 1,
        '#', 24,
        '+', 52,
        '=', 31,
        '>', 35,
        '\t', 48,
        0x0b, 48,
        '\f', 48,
        ' ', 48,
      );
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(51);
      if (lookahead != 0 &&
          lookahead != '*' &&
          lookahead != '+' &&
          lookahead != '-' &&
          lookahead != '_' &&
          lookahead != '`') ADVANCE(54);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(aux_sym_text_token1);
      if (lookahead == '\n') ADVANCE(27);
      if (lookahead == '\r') ADVANCE(2);
      if (('\t' <= lookahead && lookahead <= '\f') ||
          lookahead == ' ') ADVANCE(49);
      if (lookahead != 0 &&
          lookahead != '#' &&
          lookahead != '*' &&
          lookahead != '-' &&
          lookahead != '>' &&
          lookahead != '_' &&
          lookahead != '`') ADVANCE(54);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(aux_sym_text_token1);
      ADVANCE_MAP(
        '\n', 29,
        '\r', 4,
        '#', 24,
        '+', 52,
        '>', 35,
        '\t', 50,
        0x0b, 50,
        '\f', 50,
        ' ', 50,
      );
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(51);
      if (lookahead != 0 &&
          lookahead != '*' &&
          lookahead != '+' &&
          lookahead != '-' &&
          lookahead != '_' &&
          lookahead != '`') ADVANCE(54);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(aux_sym_text_token1);
      if (lookahead == '.') ADVANCE(52);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(51);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '#' &&
          lookahead != '*' &&
          lookahead != '-' &&
          lookahead != '.' &&
          lookahead != '>' &&
          lookahead != '_' &&
          lookahead != '`') ADVANCE(54);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(aux_sym_text_token1);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(52);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '#' &&
          lookahead != '*' &&
          lookahead != '-' &&
          lookahead != '>' &&
          lookahead != '_' &&
          lookahead != '`') ADVANCE(54);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(aux_sym_text_token1);
      if (lookahead == '\t' ||
          lookahead == 0x0b ||
          lookahead == '\f' ||
          lookahead == ' ') ADVANCE(53);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != '#' &&
          lookahead != '*' &&
          lookahead != '-' &&
          lookahead != '>' &&
          lookahead != '_' &&
          lookahead != '`') ADVANCE(54);
      END_STATE();
    case 54:
      ACCEPT_TOKEN(aux_sym_text_token1);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '#' &&
          lookahead != '*' &&
          lookahead != '-' &&
          lookahead != '>' &&
          lookahead != '_' &&
          lookahead != '`') ADVANCE(54);
      END_STATE();
    case 55:
      ACCEPT_TOKEN(aux_sym_text_token2);
      END_STATE();
    case 56:
      ACCEPT_TOKEN(aux_sym_text_token2);
      if (lookahead == '*') ADVANCE(40);
      END_STATE();
    case 57:
      ACCEPT_TOKEN(aux_sym_text_token2);
      if (lookahead == '_') ADVANCE(42);
      END_STATE();
    case 58:
      ACCEPT_TOKEN(aux_sym_fenced_code_block_token1);
      if (lookahead == '`') ADVANCE(58);
      END_STATE();
    case 59:
      ACCEPT_TOKEN(aux_sym_fenced_code_block_token1);
      if (lookahead == '`') ADVANCE(59);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(63);
      END_STATE();
    case 60:
      ACCEPT_TOKEN(aux_sym_fenced_code_block_token2);
      if (lookahead == '`') ADVANCE(62);
      if (lookahead == '\t' ||
          lookahead == 0x0b ||
          lookahead == '\f' ||
          lookahead == ' ') ADVANCE(60);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead)) ADVANCE(63);
      END_STATE();
    case 61:
      ACCEPT_TOKEN(aux_sym_fenced_code_block_token2);
      if (lookahead == '`') ADVANCE(59);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(63);
      END_STATE();
    case 62:
      ACCEPT_TOKEN(aux_sym_fenced_code_block_token2);
      if (lookahead == '`') ADVANCE(61);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(63);
      END_STATE();
    case 63:
      ACCEPT_TOKEN(aux_sym_fenced_code_block_token2);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(63);
      END_STATE();
    case 64:
      ACCEPT_TOKEN(sym_language);
      if (lookahead == '\n') ADVANCE(30);
      if (lookahead == '\r') ADVANCE(5);
      if (('\t' <= lookahead && lookahead <= '\f') ||
          lookahead == ' ') ADVANCE(64);
      if (lookahead != 0) ADVANCE(65);
      END_STATE();
    case 65:
      ACCEPT_TOKEN(sym_language);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(65);
      END_STATE();
    case 66:
      ACCEPT_TOKEN(aux_sym_list_item_token1);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(66);
      END_STATE();
    case 67:
      ACCEPT_TOKEN(aux_sym_list_item_token2);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(67);
      END_STATE();
    case 68:
      ACCEPT_TOKEN(aux_sym_thematic_break_token1);
      if (lookahead == '-') ADVANCE(68);
      END_STATE();
    case 69:
      ACCEPT_TOKEN(aux_sym_thematic_break_token2);
      if (lookahead == '*') ADVANCE(69);
      END_STATE();
    case 70:
      ACCEPT_TOKEN(aux_sym_thematic_break_token3);
      if (lookahead == '_') ADVANCE(70);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 18},
  [2] = {.lex_state = 18},
  [3] = {.lex_state = 18},
  [4] = {.lex_state = 18},
  [5] = {.lex_state = 18},
  [6] = {.lex_state = 18},
  [7] = {.lex_state = 18},
  [8] = {.lex_state = 18},
  [9] = {.lex_state = 0},
  [10] = {.lex_state = 18},
  [11] = {.lex_state = 18},
  [12] = {.lex_state = 18},
  [13] = {.lex_state = 18},
  [14] = {.lex_state = 18},
  [15] = {.lex_state = 18},
  [16] = {.lex_state = 18},
  [17] = {.lex_state = 18},
  [18] = {.lex_state = 18},
  [19] = {.lex_state = 18},
  [20] = {.lex_state = 18},
  [21] = {.lex_state = 18},
  [22] = {.lex_state = 18},
  [23] = {.lex_state = 18},
  [24] = {.lex_state = 18},
  [25] = {.lex_state = 2},
  [26] = {.lex_state = 2},
  [27] = {.lex_state = 2},
  [28] = {.lex_state = 2},
  [29] = {.lex_state = 2},
  [30] = {.lex_state = 2},
  [31] = {.lex_state = 2},
  [32] = {.lex_state = 7},
  [33] = {.lex_state = 7},
  [34] = {.lex_state = 7},
  [35] = {.lex_state = 7},
  [36] = {.lex_state = 7},
  [37] = {.lex_state = 7},
  [38] = {.lex_state = 7},
  [39] = {.lex_state = 7},
  [40] = {.lex_state = 7},
  [41] = {.lex_state = 7},
  [42] = {.lex_state = 7},
  [43] = {.lex_state = 7},
  [44] = {.lex_state = 7},
  [45] = {.lex_state = 7},
  [46] = {.lex_state = 7},
  [47] = {.lex_state = 7},
  [48] = {.lex_state = 7},
  [49] = {.lex_state = 7},
  [50] = {.lex_state = 7},
  [51] = {.lex_state = 7},
  [52] = {.lex_state = 7},
  [53] = {.lex_state = 7},
  [54] = {.lex_state = 7},
  [55] = {.lex_state = 9},
  [56] = {.lex_state = 6},
  [57] = {.lex_state = 9},
  [58] = {.lex_state = 6},
  [59] = {.lex_state = 9},
  [60] = {.lex_state = 6},
  [61] = {.lex_state = 8},
  [62] = {.lex_state = 8},
  [63] = {.lex_state = 8},
  [64] = {.lex_state = 8},
  [65] = {.lex_state = 2},
  [66] = {.lex_state = 2},
  [67] = {.lex_state = 2},
  [68] = {.lex_state = 7},
  [69] = {.lex_state = 2},
  [70] = {.lex_state = 7},
  [71] = {.lex_state = 2},
  [72] = {.lex_state = 7},
  [73] = {.lex_state = 6},
  [74] = {.lex_state = 6},
  [75] = {.lex_state = 7},
  [76] = {.lex_state = 7},
  [77] = {.lex_state = 9},
  [78] = {.lex_state = 9},
  [79] = {.lex_state = 9},
  [80] = {.lex_state = 6},
  [81] = {.lex_state = 6},
  [82] = {.lex_state = 9},
  [83] = {.lex_state = 60},
  [84] = {.lex_state = 60},
  [85] = {.lex_state = 60},
  [86] = {.lex_state = 15},
  [87] = {.lex_state = 60},
  [88] = {.lex_state = 60},
  [89] = {.lex_state = 15},
  [90] = {.lex_state = 5},
  [91] = {.lex_state = 14},
  [92] = {.lex_state = 14},
  [93] = {.lex_state = 14},
  [94] = {.lex_state = 60},
  [95] = {.lex_state = 14},
  [96] = {.lex_state = 15},
  [97] = {.lex_state = 3},
  [98] = {.lex_state = 3},
  [99] = {.lex_state = 3},
  [100] = {.lex_state = 15},
  [101] = {.lex_state = 3},
  [102] = {.lex_state = 3},
  [103] = {.lex_state = 15},
  [104] = {.lex_state = 0},
  [105] = {.lex_state = 3},
  [106] = {.lex_state = 3},
  [107] = {.lex_state = 3},
  [108] = {.lex_state = 3},
  [109] = {.lex_state = 3},
  [110] = {.lex_state = 15},
  [111] = {.lex_state = 3},
  [112] = {.lex_state = 3},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [aux_sym_atx_heading_token1] = ACTIONS(1),
    [aux_sym_atx_heading_token2] = ACTIONS(1),
    [aux_sym_setext_heading_token1] = ACTIONS(1),
    [aux_sym_setext_heading_token2] = ACTIONS(1),
    [aux_sym_block_quote_line_token1] = ACTIONS(1),
    [anon_sym_STAR] = ACTIONS(1),
    [anon_sym__] = ACTIONS(1),
    [anon_sym_STAR_STAR] = ACTIONS(1),
    [anon_sym___] = ACTIONS(1),
    [anon_sym_BQUOTE] = ACTIONS(1),
    [aux_sym_text_token1] = ACTIONS(1),
    [aux_sym_text_token2] = ACTIONS(1),
    [aux_sym_fenced_code_block_token1] = ACTIONS(1),
    [aux_sym_list_item_token1] = ACTIONS(1),
    [aux_sym_list_item_token2] = ACTIONS(1),
    [aux_sym_thematic_break_token1] = ACTIONS(1),
    [aux_sym_thematic_break_token2] = ACTIONS(1),
    [aux_sym_thematic_break_token3] = ACTIONS(1),
  },
  [1] = {
    [sym_document] = STATE(104),
    [sym__block] = STATE(2),
    [sym_atx_heading] = STATE(2),
    [sym_setext_heading] = STATE(2),
    [sym_block_quote] = STATE(2),
    [sym_block_quote_line] = STATE(7),
    [sym_paragraph] = STATE(2),
    [sym_inline] = STATE(101),
    [sym__inline_element] = STATE(28),
    [sym_emphasis] = STATE(28),
    [sym_strong_emphasis] = STATE(28),
    [sym_code_span] = STATE(28),
    [sym_text] = STATE(28),
    [sym_fenced_code_block] = STATE(2),
    [sym_list] = STATE(2),
    [sym_list_item] = STATE(4),
    [sym_thematic_break] = STATE(2),
    [sym_blank_line] = STATE(2),
    [aux_sym_document_repeat1] = STATE(2),
    [aux_sym_inline_repeat1] = STATE(28),
    [aux_sym_text_repeat1] = STATE(65),
    [ts_builtin_sym_end] = ACTIONS(3),
    [aux_sym_atx_heading_token1] = ACTIONS(5),
    [aux_sym_atx_heading_token2] = ACTIONS(7),
    [aux_sym_block_quote_line_token1] = ACTIONS(9),
    [anon_sym_STAR] = ACTIONS(11),
    [anon_sym__] = ACTIONS(13),
    [anon_sym_STAR_STAR] = ACTIONS(15),
    [anon_sym___] = ACTIONS(17),
    [anon_sym_BQUOTE] = ACTIONS(19),
    [aux_sym_text_token1] = ACTIONS(21),
    [aux_sym_text_token2] = ACTIONS(21),
    [aux_sym_fenced_code_block_token1] = ACTIONS(23),
    [aux_sym_list_item_token1] = ACTIONS(25),
    [aux_sym_list_item_token2] = ACTIONS(25),
    [aux_sym_thematic_break_token1] = ACTIONS(27),
    [aux_sym_thematic_break_token2] = ACTIONS(27),
    [aux_sym_thematic_break_token3] = ACTIONS(27),
  },
  [2] = {
    [sym__block] = STATE(3),
    [sym_atx_heading] = STATE(3),
    [sym_setext_heading] = STATE(3),
    [sym_block_quote] = STATE(3),
    [sym_block_quote_line] = STATE(7),
    [sym_paragraph] = STATE(3),
    [sym_inline] = STATE(101),
    [sym__inline_element] = STATE(28),
    [sym_emphasis] = STATE(28),
    [sym_strong_emphasis] = STATE(28),
    [sym_code_span] = STATE(28),
    [sym_text] = STATE(28),
    [sym_fenced_code_block] = STATE(3),
    [sym_list] = STATE(3),
    [sym_list_item] = STATE(4),
    [sym_thematic_break] = STATE(3),
    [sym_blank_line] = STATE(3),
    [aux_sym_document_repeat1] = STATE(3),
    [aux_sym_inline_repeat1] = STATE(28),
    [aux_sym_text_repeat1] = STATE(65),
    [ts_builtin_sym_end] = ACTIONS(29),
    [aux_sym_atx_heading_token1] = ACTIONS(5),
    [aux_sym_atx_heading_token2] = ACTIONS(7),
    [aux_sym_block_quote_line_token1] = ACTIONS(9),
    [anon_sym_STAR] = ACTIONS(11),
    [anon_sym__] = ACTIONS(13),
    [anon_sym_STAR_STAR] = ACTIONS(15),
    [anon_sym___] = ACTIONS(17),
    [anon_sym_BQUOTE] = ACTIONS(19),
    [aux_sym_text_token1] = ACTIONS(21),
    [aux_sym_text_token2] = ACTIONS(21),
    [aux_sym_fenced_code_block_token1] = ACTIONS(23),
    [aux_sym_list_item_token1] = ACTIONS(25),
    [aux_sym_list_item_token2] = ACTIONS(25),
    [aux_sym_thematic_break_token1] = ACTIONS(27),
    [aux_sym_thematic_break_token2] = ACTIONS(27),
    [aux_sym_thematic_break_token3] = ACTIONS(27),
  },
  [3] = {
    [sym__block] = STATE(3),
    [sym_atx_heading] = STATE(3),
    [sym_setext_heading] = STATE(3),
    [sym_block_quote] = STATE(3),
    [sym_block_quote_line] = STATE(7),
    [sym_paragraph] = STATE(3),
    [sym_inline] = STATE(101),
    [sym__inline_element] = STATE(28),
    [sym_emphasis] = STATE(28),
    [sym_strong_emphasis] = STATE(28),
    [sym_code_span] = STATE(28),
    [sym_text] = STATE(28),
    [sym_fenced_code_block] = STATE(3),
    [sym_list] = STATE(3),
    [sym_list_item] = STATE(4),
    [sym_thematic_break] = STATE(3),
    [sym_blank_line] = STATE(3),
    [aux_sym_document_repeat1] = STATE(3),
    [aux_sym_inline_repeat1] = STATE(28),
    [aux_sym_text_repeat1] = STATE(65),
    [ts_builtin_sym_end] = ACTIONS(31),
    [aux_sym_atx_heading_token1] = ACTIONS(33),
    [aux_sym_atx_heading_token2] = ACTIONS(36),
    [aux_sym_block_quote_line_token1] = ACTIONS(39),
    [anon_sym_STAR] = ACTIONS(42),
    [anon_sym__] = ACTIONS(45),
    [anon_sym_STAR_STAR] = ACTIONS(48),
    [anon_sym___] = ACTIONS(51),
    [anon_sym_BQUOTE] = ACTIONS(54),
    [aux_sym_text_token1] = ACTIONS(57),
    [aux_sym_text_token2] = ACTIONS(57),
    [aux_sym_fenced_code_block_token1] = ACTIONS(60),
    [aux_sym_list_item_token1] = ACTIONS(63),
    [aux_sym_list_item_token2] = ACTIONS(63),
    [aux_sym_thematic_break_token1] = ACTIONS(66),
    [aux_sym_thematic_break_token2] = ACTIONS(66),
    [aux_sym_thematic_break_token3] = ACTIONS(66),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 6,
    ACTIONS(69), 1,
      ts_builtin_sym_end,
    ACTIONS(73), 1,
      aux_sym_atx_heading_token2,
    STATE(86), 1,
      sym_blank_line,
    ACTIONS(25), 2,
      aux_sym_list_item_token1,
      aux_sym_list_item_token2,
    STATE(5), 2,
      sym_list_item,
      aux_sym_list_repeat1,
    ACTIONS(71), 13,
      aux_sym_atx_heading_token1,
      aux_sym_block_quote_line_token1,
      anon_sym_STAR,
      anon_sym__,
      anon_sym_STAR_STAR,
      anon_sym___,
      anon_sym_BQUOTE,
      aux_sym_text_token1,
      aux_sym_text_token2,
      aux_sym_fenced_code_block_token1,
      aux_sym_thematic_break_token1,
      aux_sym_thematic_break_token2,
      aux_sym_thematic_break_token3,
  [33] = 6,
    ACTIONS(73), 1,
      aux_sym_atx_heading_token2,
    ACTIONS(75), 1,
      ts_builtin_sym_end,
    STATE(86), 1,
      sym_blank_line,
    ACTIONS(25), 2,
      aux_sym_list_item_token1,
      aux_sym_list_item_token2,
    STATE(6), 2,
      sym_list_item,
      aux_sym_list_repeat1,
    ACTIONS(77), 13,
      aux_sym_atx_heading_token1,
      aux_sym_block_quote_line_token1,
      anon_sym_STAR,
      anon_sym__,
      anon_sym_STAR_STAR,
      anon_sym___,
      anon_sym_BQUOTE,
      aux_sym_text_token1,
      aux_sym_text_token2,
      aux_sym_fenced_code_block_token1,
      aux_sym_thematic_break_token1,
      aux_sym_thematic_break_token2,
      aux_sym_thematic_break_token3,
  [66] = 6,
    ACTIONS(79), 1,
      ts_builtin_sym_end,
    ACTIONS(83), 1,
      aux_sym_atx_heading_token2,
    STATE(86), 1,
      sym_blank_line,
    ACTIONS(86), 2,
      aux_sym_list_item_token1,
      aux_sym_list_item_token2,
    STATE(6), 2,
      sym_list_item,
      aux_sym_list_repeat1,
    ACTIONS(81), 13,
      aux_sym_atx_heading_token1,
      aux_sym_block_quote_line_token1,
      anon_sym_STAR,
      anon_sym__,
      anon_sym_STAR_STAR,
      anon_sym___,
      anon_sym_BQUOTE,
      aux_sym_text_token1,
      aux_sym_text_token2,
      aux_sym_fenced_code_block_token1,
      aux_sym_thematic_break_token1,
      aux_sym_thematic_break_token2,
      aux_sym_thematic_break_token3,
  [99] = 4,
    ACTIONS(9), 1,
      aux_sym_block_quote_line_token1,
    ACTIONS(89), 1,
      ts_builtin_sym_end,
    STATE(8), 2,
      sym_block_quote_line,
      aux_sym_block_quote_repeat1,
    ACTIONS(91), 15,
      aux_sym_atx_heading_token1,
      aux_sym_atx_heading_token2,
      anon_sym_STAR,
      anon_sym__,
      anon_sym_STAR_STAR,
      anon_sym___,
      anon_sym_BQUOTE,
      aux_sym_text_token1,
      aux_sym_text_token2,
      aux_sym_fenced_code_block_token1,
      aux_sym_list_item_token1,
      aux_sym_list_item_token2,
      aux_sym_thematic_break_token1,
      aux_sym_thematic_break_token2,
      aux_sym_thematic_break_token3,
  [127] = 4,
    ACTIONS(9), 1,
      aux_sym_block_quote_line_token1,
    ACTIONS(93), 1,
      ts_builtin_sym_end,
    STATE(10), 2,
      sym_block_quote_line,
      aux_sym_block_quote_repeat1,
    ACTIONS(95), 15,
      aux_sym_atx_heading_token1,
      aux_sym_atx_heading_token2,
      anon_sym_STAR,
      anon_sym__,
      anon_sym_STAR_STAR,
      anon_sym___,
      anon_sym_BQUOTE,
      aux_sym_text_token1,
      aux_sym_text_token2,
      aux_sym_fenced_code_block_token1,
      aux_sym_list_item_token1,
      aux_sym_list_item_token2,
      aux_sym_thematic_break_token1,
      aux_sym_thematic_break_token2,
      aux_sym_thematic_break_token3,
  [155] = 3,
    ACTIONS(97), 1,
      ts_builtin_sym_end,
    ACTIONS(101), 2,
      aux_sym_setext_heading_token1,
      aux_sym_setext_heading_token2,
    ACTIONS(99), 16,
      aux_sym_atx_heading_token1,
      aux_sym_atx_heading_token2,
      aux_sym_block_quote_line_token1,
      anon_sym_STAR,
      anon_sym__,
      anon_sym_STAR_STAR,
      anon_sym___,
      anon_sym_BQUOTE,
      aux_sym_text_token1,
      aux_sym_text_token2,
      aux_sym_fenced_code_block_token1,
      aux_sym_list_item_token1,
      aux_sym_list_item_token2,
      aux_sym_thematic_break_token1,
      aux_sym_thematic_break_token2,
      aux_sym_thematic_break_token3,
  [181] = 4,
    ACTIONS(103), 1,
      ts_builtin_sym_end,
    ACTIONS(107), 1,
      aux_sym_block_quote_line_token1,
    STATE(10), 2,
      sym_block_quote_line,
      aux_sym_block_quote_repeat1,
    ACTIONS(105), 15,
      aux_sym_atx_heading_token1,
      aux_sym_atx_heading_token2,
      anon_sym_STAR,
      anon_sym__,
      anon_sym_STAR_STAR,
      anon_sym___,
      anon_sym_BQUOTE,
      aux_sym_text_token1,
      aux_sym_text_token2,
      aux_sym_fenced_code_block_token1,
      aux_sym_list_item_token1,
      aux_sym_list_item_token2,
      aux_sym_thematic_break_token1,
      aux_sym_thematic_break_token2,
      aux_sym_thematic_break_token3,
  [209] = 2,
    ACTIONS(110), 1,
      ts_builtin_sym_end,
    ACTIONS(112), 16,
      aux_sym_atx_heading_token1,
      aux_sym_atx_heading_token2,
      aux_sym_block_quote_line_token1,
      anon_sym_STAR,
      anon_sym__,
      anon_sym_STAR_STAR,
      anon_sym___,
      anon_sym_BQUOTE,
      aux_sym_text_token1,
      aux_sym_text_token2,
      aux_sym_fenced_code_block_token1,
      aux_sym_list_item_token1,
      aux_sym_list_item_token2,
      aux_sym_thematic_break_token1,
      aux_sym_thematic_break_token2,
      aux_sym_thematic_break_token3,
  [231] = 2,
    ACTIONS(114), 1,
      ts_builtin_sym_end,
    ACTIONS(116), 16,
      aux_sym_atx_heading_token1,
      aux_sym_atx_heading_token2,
      aux_sym_block_quote_line_token1,
      anon_sym_STAR,
      anon_sym__,
      anon_sym_STAR_STAR,
      anon_sym___,
      anon_sym_BQUOTE,
      aux_sym_text_token1,
      aux_sym_text_token2,
      aux_sym_fenced_code_block_token1,
      aux_sym_list_item_token1,
      aux_sym_list_item_token2,
      aux_sym_thematic_break_token1,
      aux_sym_thematic_break_token2,
      aux_sym_thematic_break_token3,
  [253] = 2,
    ACTIONS(118), 1,
      ts_builtin_sym_end,
    ACTIONS(120), 16,
      aux_sym_atx_heading_token1,
      aux_sym_atx_heading_token2,
      aux_sym_block_quote_line_token1,
      anon_sym_STAR,
      anon_sym__,
      anon_sym_STAR_STAR,
      anon_sym___,
      anon_sym_BQUOTE,
      aux_sym_text_token1,
      aux_sym_text_token2,
      aux_sym_fenced_code_block_token1,
      aux_sym_list_item_token1,
      aux_sym_list_item_token2,
      aux_sym_thematic_break_token1,
      aux_sym_thematic_break_token2,
      aux_sym_thematic_break_token3,
  [275] = 2,
    ACTIONS(122), 1,
      ts_builtin_sym_end,
    ACTIONS(124), 16,
      aux_sym_atx_heading_token1,
      aux_sym_atx_heading_token2,
      aux_sym_block_quote_line_token1,
      anon_sym_STAR,
      anon_sym__,
      anon_sym_STAR_STAR,
      anon_sym___,
      anon_sym_BQUOTE,
      aux_sym_text_token1,
      aux_sym_text_token2,
      aux_sym_fenced_code_block_token1,
      aux_sym_list_item_token1,
      aux_sym_list_item_token2,
      aux_sym_thematic_break_token1,
      aux_sym_thematic_break_token2,
      aux_sym_thematic_break_token3,
  [297] = 2,
    ACTIONS(126), 1,
      ts_builtin_sym_end,
    ACTIONS(128), 16,
      aux_sym_atx_heading_token1,
      aux_sym_atx_heading_token2,
      aux_sym_block_quote_line_token1,
      anon_sym_STAR,
      anon_sym__,
      anon_sym_STAR_STAR,
      anon_sym___,
      anon_sym_BQUOTE,
      aux_sym_text_token1,
      aux_sym_text_token2,
      aux_sym_fenced_code_block_token1,
      aux_sym_list_item_token1,
      aux_sym_list_item_token2,
      aux_sym_thematic_break_token1,
      aux_sym_thematic_break_token2,
      aux_sym_thematic_break_token3,
  [319] = 2,
    ACTIONS(130), 1,
      ts_builtin_sym_end,
    ACTIONS(132), 16,
      aux_sym_atx_heading_token1,
      aux_sym_atx_heading_token2,
      aux_sym_block_quote_line_token1,
      anon_sym_STAR,
      anon_sym__,
      anon_sym_STAR_STAR,
      anon_sym___,
      anon_sym_BQUOTE,
      aux_sym_text_token1,
      aux_sym_text_token2,
      aux_sym_fenced_code_block_token1,
      aux_sym_list_item_token1,
      aux_sym_list_item_token2,
      aux_sym_thematic_break_token1,
      aux_sym_thematic_break_token2,
      aux_sym_thematic_break_token3,
  [341] = 2,
    ACTIONS(134), 1,
      ts_builtin_sym_end,
    ACTIONS(136), 16,
      aux_sym_atx_heading_token1,
      aux_sym_atx_heading_token2,
      aux_sym_block_quote_line_token1,
      anon_sym_STAR,
      anon_sym__,
      anon_sym_STAR_STAR,
      anon_sym___,
      anon_sym_BQUOTE,
      aux_sym_text_token1,
      aux_sym_text_token2,
      aux_sym_fenced_code_block_token1,
      aux_sym_list_item_token1,
      aux_sym_list_item_token2,
      aux_sym_thematic_break_token1,
      aux_sym_thematic_break_token2,
      aux_sym_thematic_break_token3,
  [363] = 2,
    ACTIONS(138), 1,
      ts_builtin_sym_end,
    ACTIONS(140), 16,
      aux_sym_atx_heading_token1,
      aux_sym_atx_heading_token2,
      aux_sym_block_quote_line_token1,
      anon_sym_STAR,
      anon_sym__,
      anon_sym_STAR_STAR,
      anon_sym___,
      anon_sym_BQUOTE,
      aux_sym_text_token1,
      aux_sym_text_token2,
      aux_sym_fenced_code_block_token1,
      aux_sym_list_item_token1,
      aux_sym_list_item_token2,
      aux_sym_thematic_break_token1,
      aux_sym_thematic_break_token2,
      aux_sym_thematic_break_token3,
  [385] = 2,
    ACTIONS(142), 1,
      ts_builtin_sym_end,
    ACTIONS(144), 16,
      aux_sym_atx_heading_token1,
      aux_sym_atx_heading_token2,
      aux_sym_block_quote_line_token1,
      anon_sym_STAR,
      anon_sym__,
      anon_sym_STAR_STAR,
      anon_sym___,
      anon_sym_BQUOTE,
      aux_sym_text_token1,
      aux_sym_text_token2,
      aux_sym_fenced_code_block_token1,
      aux_sym_list_item_token1,
      aux_sym_list_item_token2,
      aux_sym_thematic_break_token1,
      aux_sym_thematic_break_token2,
      aux_sym_thematic_break_token3,
  [407] = 2,
    ACTIONS(146), 1,
      ts_builtin_sym_end,
    ACTIONS(148), 16,
      aux_sym_atx_heading_token1,
      aux_sym_atx_heading_token2,
      aux_sym_block_quote_line_token1,
      anon_sym_STAR,
      anon_sym__,
      anon_sym_STAR_STAR,
      anon_sym___,
      anon_sym_BQUOTE,
      aux_sym_text_token1,
      aux_sym_text_token2,
      aux_sym_fenced_code_block_token1,
      aux_sym_list_item_token1,
      aux_sym_list_item_token2,
      aux_sym_thematic_break_token1,
      aux_sym_thematic_break_token2,
      aux_sym_thematic_break_token3,
  [429] = 2,
    ACTIONS(79), 1,
      ts_builtin_sym_end,
    ACTIONS(81), 16,
      aux_sym_atx_heading_token1,
      aux_sym_atx_heading_token2,
      aux_sym_block_quote_line_token1,
      anon_sym_STAR,
      anon_sym__,
      anon_sym_STAR_STAR,
      anon_sym___,
      anon_sym_BQUOTE,
      aux_sym_text_token1,
      aux_sym_text_token2,
      aux_sym_fenced_code_block_token1,
      aux_sym_list_item_token1,
      aux_sym_list_item_token2,
      aux_sym_thematic_break_token1,
      aux_sym_thematic_break_token2,
      aux_sym_thematic_break_token3,
  [451] = 2,
    ACTIONS(150), 1,
      ts_builtin_sym_end,
    ACTIONS(152), 16,
      aux_sym_atx_heading_token1,
      aux_sym_atx_heading_token2,
      aux_sym_block_quote_line_token1,
      anon_sym_STAR,
      anon_sym__,
      anon_sym_STAR_STAR,
      anon_sym___,
      anon_sym_BQUOTE,
      aux_sym_text_token1,
      aux_sym_text_token2,
      aux_sym_fenced_code_block_token1,
      aux_sym_list_item_token1,
      aux_sym_list_item_token2,
      aux_sym_thematic_break_token1,
      aux_sym_thematic_break_token2,
      aux_sym_thematic_break_token3,
  [473] = 2,
    ACTIONS(154), 1,
      ts_builtin_sym_end,
    ACTIONS(156), 16,
      aux_sym_atx_heading_token1,
      aux_sym_atx_heading_token2,
      aux_sym_block_quote_line_token1,
      anon_sym_STAR,
      anon_sym__,
      anon_sym_STAR_STAR,
      anon_sym___,
      anon_sym_BQUOTE,
      aux_sym_text_token1,
      aux_sym_text_token2,
      aux_sym_fenced_code_block_token1,
      aux_sym_list_item_token1,
      aux_sym_list_item_token2,
      aux_sym_thematic_break_token1,
      aux_sym_thematic_break_token2,
      aux_sym_thematic_break_token3,
  [495] = 2,
    ACTIONS(158), 1,
      ts_builtin_sym_end,
    ACTIONS(160), 16,
      aux_sym_atx_heading_token1,
      aux_sym_atx_heading_token2,
      aux_sym_block_quote_line_token1,
      anon_sym_STAR,
      anon_sym__,
      anon_sym_STAR_STAR,
      anon_sym___,
      anon_sym_BQUOTE,
      aux_sym_text_token1,
      aux_sym_text_token2,
      aux_sym_fenced_code_block_token1,
      aux_sym_list_item_token1,
      aux_sym_list_item_token2,
      aux_sym_thematic_break_token1,
      aux_sym_thematic_break_token2,
      aux_sym_thematic_break_token3,
  [517] = 10,
    ACTIONS(11), 1,
      anon_sym_STAR,
    ACTIONS(13), 1,
      anon_sym__,
    ACTIONS(15), 1,
      anon_sym_STAR_STAR,
    ACTIONS(17), 1,
      anon_sym___,
    ACTIONS(19), 1,
      anon_sym_BQUOTE,
    ACTIONS(162), 1,
      aux_sym_atx_heading_token2,
    STATE(65), 1,
      aux_sym_text_repeat1,
    STATE(111), 1,
      sym_inline,
    ACTIONS(21), 2,
      aux_sym_text_token1,
      aux_sym_text_token2,
    STATE(28), 6,
      sym__inline_element,
      sym_emphasis,
      sym_strong_emphasis,
      sym_code_span,
      sym_text,
      aux_sym_inline_repeat1,
  [554] = 10,
    ACTIONS(11), 1,
      anon_sym_STAR,
    ACTIONS(13), 1,
      anon_sym__,
    ACTIONS(15), 1,
      anon_sym_STAR_STAR,
    ACTIONS(17), 1,
      anon_sym___,
    ACTIONS(19), 1,
      anon_sym_BQUOTE,
    ACTIONS(164), 1,
      aux_sym_atx_heading_token2,
    STATE(65), 1,
      aux_sym_text_repeat1,
    STATE(106), 1,
      sym_inline,
    ACTIONS(21), 2,
      aux_sym_text_token1,
      aux_sym_text_token2,
    STATE(28), 6,
      sym__inline_element,
      sym_emphasis,
      sym_strong_emphasis,
      sym_code_span,
      sym_text,
      aux_sym_inline_repeat1,
  [591] = 10,
    ACTIONS(11), 1,
      anon_sym_STAR,
    ACTIONS(13), 1,
      anon_sym__,
    ACTIONS(15), 1,
      anon_sym_STAR_STAR,
    ACTIONS(17), 1,
      anon_sym___,
    ACTIONS(19), 1,
      anon_sym_BQUOTE,
    ACTIONS(166), 1,
      aux_sym_atx_heading_token2,
    STATE(65), 1,
      aux_sym_text_repeat1,
    STATE(99), 1,
      sym_inline,
    ACTIONS(21), 2,
      aux_sym_text_token1,
      aux_sym_text_token2,
    STATE(28), 6,
      sym__inline_element,
      sym_emphasis,
      sym_strong_emphasis,
      sym_code_span,
      sym_text,
      aux_sym_inline_repeat1,
  [628] = 9,
    ACTIONS(11), 1,
      anon_sym_STAR,
    ACTIONS(13), 1,
      anon_sym__,
    ACTIONS(15), 1,
      anon_sym_STAR_STAR,
    ACTIONS(17), 1,
      anon_sym___,
    ACTIONS(19), 1,
      anon_sym_BQUOTE,
    ACTIONS(168), 1,
      aux_sym_atx_heading_token2,
    STATE(65), 1,
      aux_sym_text_repeat1,
    ACTIONS(21), 2,
      aux_sym_text_token1,
      aux_sym_text_token2,
    STATE(29), 6,
      sym__inline_element,
      sym_emphasis,
      sym_strong_emphasis,
      sym_code_span,
      sym_text,
      aux_sym_inline_repeat1,
  [662] = 9,
    ACTIONS(170), 1,
      aux_sym_atx_heading_token2,
    ACTIONS(172), 1,
      anon_sym_STAR,
    ACTIONS(175), 1,
      anon_sym__,
    ACTIONS(178), 1,
      anon_sym_STAR_STAR,
    ACTIONS(181), 1,
      anon_sym___,
    ACTIONS(184), 1,
      anon_sym_BQUOTE,
    STATE(65), 1,
      aux_sym_text_repeat1,
    ACTIONS(187), 2,
      aux_sym_text_token1,
      aux_sym_text_token2,
    STATE(29), 6,
      sym__inline_element,
      sym_emphasis,
      sym_strong_emphasis,
      sym_code_span,
      sym_text,
      aux_sym_inline_repeat1,
  [696] = 3,
    STATE(68), 1,
      aux_sym_text_repeat1,
    STATE(47), 6,
      sym__inline_element,
      sym_emphasis,
      sym_strong_emphasis,
      sym_code_span,
      sym_text,
      aux_sym_inline_repeat1,
    ACTIONS(190), 8,
      aux_sym_atx_heading_token2,
      anon_sym_STAR,
      anon_sym__,
      anon_sym_STAR_STAR,
      anon_sym___,
      anon_sym_BQUOTE,
      aux_sym_text_token1,
      aux_sym_text_token2,
  [718] = 3,
    STATE(68), 1,
      aux_sym_text_repeat1,
    STATE(48), 6,
      sym__inline_element,
      sym_emphasis,
      sym_strong_emphasis,
      sym_code_span,
      sym_text,
      aux_sym_inline_repeat1,
    ACTIONS(190), 8,
      aux_sym_atx_heading_token2,
      anon_sym_STAR,
      anon_sym__,
      anon_sym_STAR_STAR,
      anon_sym___,
      anon_sym_BQUOTE,
      aux_sym_text_token1,
      aux_sym_text_token2,
  [740] = 9,
    ACTIONS(192), 1,
      anon_sym_STAR,
    ACTIONS(194), 1,
      anon_sym__,
    ACTIONS(196), 1,
      anon_sym_STAR_STAR,
    ACTIONS(198), 1,
      anon_sym___,
    ACTIONS(200), 1,
      anon_sym_BQUOTE,
    ACTIONS(202), 1,
      aux_sym_text_token1,
    ACTIONS(204), 1,
      aux_sym_text_token2,
    STATE(68), 1,
      aux_sym_text_repeat1,
    STATE(54), 6,
      sym__inline_element,
      sym_emphasis,
      sym_strong_emphasis,
      sym_code_span,
      sym_text,
      aux_sym_inline_repeat1,
  [773] = 9,
    ACTIONS(192), 1,
      anon_sym_STAR,
    ACTIONS(194), 1,
      anon_sym__,
    ACTIONS(198), 1,
      anon_sym___,
    ACTIONS(200), 1,
      anon_sym_BQUOTE,
    ACTIONS(202), 1,
      aux_sym_text_token1,
    ACTIONS(204), 1,
      aux_sym_text_token2,
    ACTIONS(206), 1,
      anon_sym_STAR_STAR,
    STATE(68), 1,
      aux_sym_text_repeat1,
    STATE(48), 6,
      sym__inline_element,
      sym_emphasis,
      sym_strong_emphasis,
      sym_code_span,
      sym_text,
      aux_sym_inline_repeat1,
  [806] = 9,
    ACTIONS(192), 1,
      anon_sym_STAR,
    ACTIONS(194), 1,
      anon_sym__,
    ACTIONS(198), 1,
      anon_sym___,
    ACTIONS(200), 1,
      anon_sym_BQUOTE,
    ACTIONS(202), 1,
      aux_sym_text_token1,
    ACTIONS(204), 1,
      aux_sym_text_token2,
    ACTIONS(206), 1,
      anon_sym_STAR_STAR,
    STATE(68), 1,
      aux_sym_text_repeat1,
    STATE(36), 6,
      sym__inline_element,
      sym_emphasis,
      sym_strong_emphasis,
      sym_code_span,
      sym_text,
      aux_sym_inline_repeat1,
  [839] = 9,
    ACTIONS(192), 1,
      anon_sym_STAR,
    ACTIONS(194), 1,
      anon_sym__,
    ACTIONS(198), 1,
      anon_sym___,
    ACTIONS(200), 1,
      anon_sym_BQUOTE,
    ACTIONS(202), 1,
      aux_sym_text_token1,
    ACTIONS(204), 1,
      aux_sym_text_token2,
    ACTIONS(206), 1,
      anon_sym_STAR_STAR,
    STATE(68), 1,
      aux_sym_text_repeat1,
    STATE(37), 6,
      sym__inline_element,
      sym_emphasis,
      sym_strong_emphasis,
      sym_code_span,
      sym_text,
      aux_sym_inline_repeat1,
  [872] = 9,
    ACTIONS(192), 1,
      anon_sym_STAR,
    ACTIONS(194), 1,
      anon_sym__,
    ACTIONS(198), 1,
      anon_sym___,
    ACTIONS(200), 1,
      anon_sym_BQUOTE,
    ACTIONS(202), 1,
      aux_sym_text_token1,
    ACTIONS(204), 1,
      aux_sym_text_token2,
    ACTIONS(208), 1,
      anon_sym_STAR_STAR,
    STATE(68), 1,
      aux_sym_text_repeat1,
    STATE(54), 6,
      sym__inline_element,
      sym_emphasis,
      sym_strong_emphasis,
      sym_code_span,
      sym_text,
      aux_sym_inline_repeat1,
  [905] = 9,
    ACTIONS(192), 1,
      anon_sym_STAR,
    ACTIONS(194), 1,
      anon_sym__,
    ACTIONS(200), 1,
      anon_sym_BQUOTE,
    ACTIONS(202), 1,
      aux_sym_text_token1,
    ACTIONS(204), 1,
      aux_sym_text_token2,
    ACTIONS(206), 1,
      anon_sym_STAR_STAR,
    ACTIONS(210), 1,
      anon_sym___,
    STATE(68), 1,
      aux_sym_text_repeat1,
    STATE(54), 6,
      sym__inline_element,
      sym_emphasis,
      sym_strong_emphasis,
      sym_code_span,
      sym_text,
      aux_sym_inline_repeat1,
  [938] = 5,
    ACTIONS(194), 1,
      anon_sym__,
    ACTIONS(212), 1,
      aux_sym_text_token1,
    STATE(68), 1,
      aux_sym_text_repeat1,
    ACTIONS(190), 5,
      anon_sym_STAR,
      anon_sym_STAR_STAR,
      anon_sym___,
      anon_sym_BQUOTE,
      aux_sym_text_token2,
    STATE(47), 6,
      sym__inline_element,
      sym_emphasis,
      sym_strong_emphasis,
      sym_code_span,
      sym_text,
      aux_sym_inline_repeat1,
  [963] = 5,
    ACTIONS(194), 1,
      anon_sym__,
    ACTIONS(212), 1,
      aux_sym_text_token1,
    STATE(68), 1,
      aux_sym_text_repeat1,
    ACTIONS(190), 5,
      anon_sym_STAR,
      anon_sym_STAR_STAR,
      anon_sym___,
      anon_sym_BQUOTE,
      aux_sym_text_token2,
    STATE(48), 6,
      sym__inline_element,
      sym_emphasis,
      sym_strong_emphasis,
      sym_code_span,
      sym_text,
      aux_sym_inline_repeat1,
  [988] = 5,
    ACTIONS(192), 1,
      anon_sym_STAR,
    ACTIONS(212), 1,
      aux_sym_text_token1,
    STATE(68), 1,
      aux_sym_text_repeat1,
    ACTIONS(190), 5,
      anon_sym__,
      anon_sym_STAR_STAR,
      anon_sym___,
      anon_sym_BQUOTE,
      aux_sym_text_token2,
    STATE(47), 6,
      sym__inline_element,
      sym_emphasis,
      sym_strong_emphasis,
      sym_code_span,
      sym_text,
      aux_sym_inline_repeat1,
  [1013] = 5,
    ACTIONS(192), 1,
      anon_sym_STAR,
    ACTIONS(212), 1,
      aux_sym_text_token1,
    STATE(68), 1,
      aux_sym_text_repeat1,
    ACTIONS(190), 5,
      anon_sym__,
      anon_sym_STAR_STAR,
      anon_sym___,
      anon_sym_BQUOTE,
      aux_sym_text_token2,
    STATE(48), 6,
      sym__inline_element,
      sym_emphasis,
      sym_strong_emphasis,
      sym_code_span,
      sym_text,
      aux_sym_inline_repeat1,
  [1038] = 4,
    ACTIONS(212), 1,
      aux_sym_text_token1,
    STATE(68), 1,
      aux_sym_text_repeat1,
    ACTIONS(190), 6,
      anon_sym_STAR,
      anon_sym__,
      anon_sym_STAR_STAR,
      anon_sym___,
      anon_sym_BQUOTE,
      aux_sym_text_token2,
    STATE(47), 6,
      sym__inline_element,
      sym_emphasis,
      sym_strong_emphasis,
      sym_code_span,
      sym_text,
      aux_sym_inline_repeat1,
  [1061] = 4,
    ACTIONS(212), 1,
      aux_sym_text_token1,
    STATE(68), 1,
      aux_sym_text_repeat1,
    ACTIONS(190), 6,
      anon_sym_STAR,
      anon_sym__,
      anon_sym_STAR_STAR,
      anon_sym___,
      anon_sym_BQUOTE,
      aux_sym_text_token2,
    STATE(48), 6,
      sym__inline_element,
      sym_emphasis,
      sym_strong_emphasis,
      sym_code_span,
      sym_text,
      aux_sym_inline_repeat1,
  [1084] = 9,
    ACTIONS(192), 1,
      anon_sym_STAR,
    ACTIONS(194), 1,
      anon_sym__,
    ACTIONS(198), 1,
      anon_sym___,
    ACTIONS(200), 1,
      anon_sym_BQUOTE,
    ACTIONS(202), 1,
      aux_sym_text_token1,
    ACTIONS(204), 1,
      aux_sym_text_token2,
    ACTIONS(214), 1,
      anon_sym_STAR_STAR,
    STATE(68), 1,
      aux_sym_text_repeat1,
    STATE(54), 6,
      sym__inline_element,
      sym_emphasis,
      sym_strong_emphasis,
      sym_code_span,
      sym_text,
      aux_sym_inline_repeat1,
  [1117] = 9,
    ACTIONS(192), 1,
      anon_sym_STAR,
    ACTIONS(194), 1,
      anon_sym__,
    ACTIONS(200), 1,
      anon_sym_BQUOTE,
    ACTIONS(202), 1,
      aux_sym_text_token1,
    ACTIONS(204), 1,
      aux_sym_text_token2,
    ACTIONS(206), 1,
      anon_sym_STAR_STAR,
    ACTIONS(216), 1,
      anon_sym___,
    STATE(68), 1,
      aux_sym_text_repeat1,
    STATE(54), 6,
      sym__inline_element,
      sym_emphasis,
      sym_strong_emphasis,
      sym_code_span,
      sym_text,
      aux_sym_inline_repeat1,
  [1150] = 9,
    ACTIONS(192), 1,
      anon_sym_STAR,
    ACTIONS(194), 1,
      anon_sym__,
    ACTIONS(200), 1,
      anon_sym_BQUOTE,
    ACTIONS(202), 1,
      aux_sym_text_token1,
    ACTIONS(204), 1,
      aux_sym_text_token2,
    ACTIONS(206), 1,
      anon_sym_STAR_STAR,
    ACTIONS(218), 1,
      anon_sym___,
    STATE(68), 1,
      aux_sym_text_repeat1,
    STATE(54), 6,
      sym__inline_element,
      sym_emphasis,
      sym_strong_emphasis,
      sym_code_span,
      sym_text,
      aux_sym_inline_repeat1,
  [1183] = 9,
    ACTIONS(192), 1,
      anon_sym_STAR,
    ACTIONS(194), 1,
      anon_sym__,
    ACTIONS(198), 1,
      anon_sym___,
    ACTIONS(200), 1,
      anon_sym_BQUOTE,
    ACTIONS(202), 1,
      aux_sym_text_token1,
    ACTIONS(204), 1,
      aux_sym_text_token2,
    ACTIONS(220), 1,
      anon_sym_STAR_STAR,
    STATE(68), 1,
      aux_sym_text_repeat1,
    STATE(54), 6,
      sym__inline_element,
      sym_emphasis,
      sym_strong_emphasis,
      sym_code_span,
      sym_text,
      aux_sym_inline_repeat1,
  [1216] = 9,
    ACTIONS(192), 1,
      anon_sym_STAR,
    ACTIONS(194), 1,
      anon_sym__,
    ACTIONS(200), 1,
      anon_sym_BQUOTE,
    ACTIONS(202), 1,
      aux_sym_text_token1,
    ACTIONS(204), 1,
      aux_sym_text_token2,
    ACTIONS(206), 1,
      anon_sym_STAR_STAR,
    ACTIONS(222), 1,
      anon_sym___,
    STATE(68), 1,
      aux_sym_text_repeat1,
    STATE(54), 6,
      sym__inline_element,
      sym_emphasis,
      sym_strong_emphasis,
      sym_code_span,
      sym_text,
      aux_sym_inline_repeat1,
  [1249] = 9,
    ACTIONS(192), 1,
      anon_sym_STAR,
    ACTIONS(194), 1,
      anon_sym__,
    ACTIONS(198), 1,
      anon_sym___,
    ACTIONS(200), 1,
      anon_sym_BQUOTE,
    ACTIONS(202), 1,
      aux_sym_text_token1,
    ACTIONS(204), 1,
      aux_sym_text_token2,
    ACTIONS(206), 1,
      anon_sym_STAR_STAR,
    STATE(68), 1,
      aux_sym_text_repeat1,
    STATE(44), 6,
      sym__inline_element,
      sym_emphasis,
      sym_strong_emphasis,
      sym_code_span,
      sym_text,
      aux_sym_inline_repeat1,
  [1282] = 9,
    ACTIONS(192), 1,
      anon_sym_STAR,
    ACTIONS(194), 1,
      anon_sym__,
    ACTIONS(198), 1,
      anon_sym___,
    ACTIONS(200), 1,
      anon_sym_BQUOTE,
    ACTIONS(202), 1,
      aux_sym_text_token1,
    ACTIONS(204), 1,
      aux_sym_text_token2,
    ACTIONS(206), 1,
      anon_sym_STAR_STAR,
    STATE(68), 1,
      aux_sym_text_repeat1,
    STATE(45), 6,
      sym__inline_element,
      sym_emphasis,
      sym_strong_emphasis,
      sym_code_span,
      sym_text,
      aux_sym_inline_repeat1,
  [1315] = 9,
    ACTIONS(192), 1,
      anon_sym_STAR,
    ACTIONS(194), 1,
      anon_sym__,
    ACTIONS(198), 1,
      anon_sym___,
    ACTIONS(200), 1,
      anon_sym_BQUOTE,
    ACTIONS(202), 1,
      aux_sym_text_token1,
    ACTIONS(204), 1,
      aux_sym_text_token2,
    ACTIONS(206), 1,
      anon_sym_STAR_STAR,
    STATE(68), 1,
      aux_sym_text_repeat1,
    STATE(32), 6,
      sym__inline_element,
      sym_emphasis,
      sym_strong_emphasis,
      sym_code_span,
      sym_text,
      aux_sym_inline_repeat1,
  [1348] = 9,
    ACTIONS(192), 1,
      anon_sym_STAR,
    ACTIONS(194), 1,
      anon_sym__,
    ACTIONS(198), 1,
      anon_sym___,
    ACTIONS(200), 1,
      anon_sym_BQUOTE,
    ACTIONS(202), 1,
      aux_sym_text_token1,
    ACTIONS(204), 1,
      aux_sym_text_token2,
    ACTIONS(206), 1,
      anon_sym_STAR_STAR,
    STATE(68), 1,
      aux_sym_text_repeat1,
    STATE(46), 6,
      sym__inline_element,
      sym_emphasis,
      sym_strong_emphasis,
      sym_code_span,
      sym_text,
      aux_sym_inline_repeat1,
  [1381] = 9,
    ACTIONS(192), 1,
      anon_sym_STAR,
    ACTIONS(194), 1,
      anon_sym__,
    ACTIONS(198), 1,
      anon_sym___,
    ACTIONS(200), 1,
      anon_sym_BQUOTE,
    ACTIONS(202), 1,
      aux_sym_text_token1,
    ACTIONS(204), 1,
      aux_sym_text_token2,
    ACTIONS(206), 1,
      anon_sym_STAR_STAR,
    STATE(68), 1,
      aux_sym_text_repeat1,
    STATE(47), 6,
      sym__inline_element,
      sym_emphasis,
      sym_strong_emphasis,
      sym_code_span,
      sym_text,
      aux_sym_inline_repeat1,
  [1414] = 9,
    ACTIONS(224), 1,
      anon_sym_STAR,
    ACTIONS(227), 1,
      anon_sym__,
    ACTIONS(230), 1,
      anon_sym_STAR_STAR,
    ACTIONS(233), 1,
      anon_sym___,
    ACTIONS(236), 1,
      anon_sym_BQUOTE,
    ACTIONS(239), 1,
      aux_sym_text_token1,
    ACTIONS(242), 1,
      aux_sym_text_token2,
    STATE(68), 1,
      aux_sym_text_repeat1,
    STATE(54), 6,
      sym__inline_element,
      sym_emphasis,
      sym_strong_emphasis,
      sym_code_span,
      sym_text,
      aux_sym_inline_repeat1,
  [1447] = 8,
    ACTIONS(245), 1,
      anon_sym__,
    ACTIONS(247), 1,
      anon_sym_STAR_STAR,
    ACTIONS(249), 1,
      anon_sym___,
    ACTIONS(251), 1,
      anon_sym_BQUOTE,
    ACTIONS(253), 1,
      aux_sym_text_token1,
    ACTIONS(255), 1,
      aux_sym_text_token2,
    STATE(77), 1,
      aux_sym_text_repeat1,
    STATE(59), 5,
      sym_strong_emphasis,
      sym__inline_no_underscore,
      sym_code_span,
      sym_text,
      aux_sym_emphasis_repeat2,
  [1476] = 8,
    ACTIONS(257), 1,
      anon_sym_STAR,
    ACTIONS(259), 1,
      anon_sym_STAR_STAR,
    ACTIONS(261), 1,
      anon_sym___,
    ACTIONS(263), 1,
      anon_sym_BQUOTE,
    ACTIONS(265), 1,
      aux_sym_text_token1,
    ACTIONS(267), 1,
      aux_sym_text_token2,
    STATE(73), 1,
      aux_sym_text_repeat1,
    STATE(58), 5,
      sym_strong_emphasis,
      sym__inline_no_star,
      sym_code_span,
      sym_text,
      aux_sym_emphasis_repeat1,
  [1505] = 8,
    ACTIONS(247), 1,
      anon_sym_STAR_STAR,
    ACTIONS(249), 1,
      anon_sym___,
    ACTIONS(251), 1,
      anon_sym_BQUOTE,
    ACTIONS(253), 1,
      aux_sym_text_token1,
    ACTIONS(255), 1,
      aux_sym_text_token2,
    ACTIONS(257), 1,
      anon_sym__,
    STATE(77), 1,
      aux_sym_text_repeat1,
    STATE(59), 5,
      sym_strong_emphasis,
      sym__inline_no_underscore,
      sym_code_span,
      sym_text,
      aux_sym_emphasis_repeat2,
  [1534] = 8,
    ACTIONS(269), 1,
      anon_sym_STAR,
    ACTIONS(271), 1,
      anon_sym_STAR_STAR,
    ACTIONS(274), 1,
      anon_sym___,
    ACTIONS(277), 1,
      anon_sym_BQUOTE,
    ACTIONS(280), 1,
      aux_sym_text_token1,
    ACTIONS(283), 1,
      aux_sym_text_token2,
    STATE(73), 1,
      aux_sym_text_repeat1,
    STATE(58), 5,
      sym_strong_emphasis,
      sym__inline_no_star,
      sym_code_span,
      sym_text,
      aux_sym_emphasis_repeat1,
  [1563] = 8,
    ACTIONS(286), 1,
      anon_sym__,
    ACTIONS(288), 1,
      anon_sym_STAR_STAR,
    ACTIONS(291), 1,
      anon_sym___,
    ACTIONS(294), 1,
      anon_sym_BQUOTE,
    ACTIONS(297), 1,
      aux_sym_text_token1,
    ACTIONS(300), 1,
      aux_sym_text_token2,
    STATE(77), 1,
      aux_sym_text_repeat1,
    STATE(59), 5,
      sym_strong_emphasis,
      sym__inline_no_underscore,
      sym_code_span,
      sym_text,
      aux_sym_emphasis_repeat2,
  [1592] = 8,
    ACTIONS(245), 1,
      anon_sym_STAR,
    ACTIONS(259), 1,
      anon_sym_STAR_STAR,
    ACTIONS(261), 1,
      anon_sym___,
    ACTIONS(263), 1,
      anon_sym_BQUOTE,
    ACTIONS(265), 1,
      aux_sym_text_token1,
    ACTIONS(267), 1,
      aux_sym_text_token2,
    STATE(73), 1,
      aux_sym_text_repeat1,
    STATE(58), 5,
      sym_strong_emphasis,
      sym__inline_no_star,
      sym_code_span,
      sym_text,
      aux_sym_emphasis_repeat1,
  [1621] = 7,
    ACTIONS(259), 1,
      anon_sym_STAR_STAR,
    ACTIONS(261), 1,
      anon_sym___,
    ACTIONS(263), 1,
      anon_sym_BQUOTE,
    ACTIONS(265), 1,
      aux_sym_text_token1,
    ACTIONS(267), 1,
      aux_sym_text_token2,
    STATE(73), 1,
      aux_sym_text_repeat1,
    STATE(60), 5,
      sym_strong_emphasis,
      sym__inline_no_star,
      sym_code_span,
      sym_text,
      aux_sym_emphasis_repeat1,
  [1647] = 7,
    ACTIONS(247), 1,
      anon_sym_STAR_STAR,
    ACTIONS(249), 1,
      anon_sym___,
    ACTIONS(251), 1,
      anon_sym_BQUOTE,
    ACTIONS(253), 1,
      aux_sym_text_token1,
    ACTIONS(255), 1,
      aux_sym_text_token2,
    STATE(77), 1,
      aux_sym_text_repeat1,
    STATE(57), 5,
      sym_strong_emphasis,
      sym__inline_no_underscore,
      sym_code_span,
      sym_text,
      aux_sym_emphasis_repeat2,
  [1673] = 7,
    ACTIONS(247), 1,
      anon_sym_STAR_STAR,
    ACTIONS(249), 1,
      anon_sym___,
    ACTIONS(251), 1,
      anon_sym_BQUOTE,
    ACTIONS(253), 1,
      aux_sym_text_token1,
    ACTIONS(255), 1,
      aux_sym_text_token2,
    STATE(77), 1,
      aux_sym_text_repeat1,
    STATE(55), 5,
      sym_strong_emphasis,
      sym__inline_no_underscore,
      sym_code_span,
      sym_text,
      aux_sym_emphasis_repeat2,
  [1699] = 7,
    ACTIONS(259), 1,
      anon_sym_STAR_STAR,
    ACTIONS(261), 1,
      anon_sym___,
    ACTIONS(263), 1,
      anon_sym_BQUOTE,
    ACTIONS(265), 1,
      aux_sym_text_token1,
    ACTIONS(267), 1,
      aux_sym_text_token2,
    STATE(73), 1,
      aux_sym_text_repeat1,
    STATE(56), 5,
      sym_strong_emphasis,
      sym__inline_no_star,
      sym_code_span,
      sym_text,
      aux_sym_emphasis_repeat1,
  [1725] = 3,
    STATE(66), 1,
      aux_sym_text_repeat1,
    ACTIONS(305), 2,
      aux_sym_text_token1,
      aux_sym_text_token2,
    ACTIONS(303), 6,
      aux_sym_atx_heading_token2,
      anon_sym_STAR,
      anon_sym__,
      anon_sym_STAR_STAR,
      anon_sym___,
      anon_sym_BQUOTE,
  [1741] = 3,
    STATE(66), 1,
      aux_sym_text_repeat1,
    ACTIONS(309), 2,
      aux_sym_text_token1,
      aux_sym_text_token2,
    ACTIONS(307), 6,
      aux_sym_atx_heading_token2,
      anon_sym_STAR,
      anon_sym__,
      anon_sym_STAR_STAR,
      anon_sym___,
      anon_sym_BQUOTE,
  [1757] = 1,
    ACTIONS(312), 8,
      aux_sym_atx_heading_token2,
      anon_sym_STAR,
      anon_sym__,
      anon_sym_STAR_STAR,
      anon_sym___,
      anon_sym_BQUOTE,
      aux_sym_text_token1,
      aux_sym_text_token2,
  [1768] = 4,
    ACTIONS(314), 1,
      aux_sym_text_token1,
    ACTIONS(316), 1,
      aux_sym_text_token2,
    STATE(70), 1,
      aux_sym_text_repeat1,
    ACTIONS(303), 5,
      anon_sym_STAR,
      anon_sym__,
      anon_sym_STAR_STAR,
      anon_sym___,
      anon_sym_BQUOTE,
  [1785] = 1,
    ACTIONS(318), 8,
      aux_sym_atx_heading_token2,
      anon_sym_STAR,
      anon_sym__,
      anon_sym_STAR_STAR,
      anon_sym___,
      anon_sym_BQUOTE,
      aux_sym_text_token1,
      aux_sym_text_token2,
  [1796] = 4,
    ACTIONS(320), 1,
      aux_sym_text_token1,
    ACTIONS(323), 1,
      aux_sym_text_token2,
    STATE(70), 1,
      aux_sym_text_repeat1,
    ACTIONS(307), 5,
      anon_sym_STAR,
      anon_sym__,
      anon_sym_STAR_STAR,
      anon_sym___,
      anon_sym_BQUOTE,
  [1813] = 1,
    ACTIONS(326), 8,
      aux_sym_atx_heading_token2,
      anon_sym_STAR,
      anon_sym__,
      anon_sym_STAR_STAR,
      anon_sym___,
      anon_sym_BQUOTE,
      aux_sym_text_token1,
      aux_sym_text_token2,
  [1824] = 2,
    ACTIONS(328), 1,
      aux_sym_text_token1,
    ACTIONS(312), 6,
      anon_sym_STAR,
      anon_sym__,
      anon_sym_STAR_STAR,
      anon_sym___,
      anon_sym_BQUOTE,
      aux_sym_text_token2,
  [1836] = 4,
    ACTIONS(330), 1,
      aux_sym_text_token1,
    ACTIONS(332), 1,
      aux_sym_text_token2,
    STATE(74), 1,
      aux_sym_text_repeat1,
    ACTIONS(303), 4,
      anon_sym_STAR,
      anon_sym_STAR_STAR,
      anon_sym___,
      anon_sym_BQUOTE,
  [1852] = 4,
    ACTIONS(334), 1,
      aux_sym_text_token1,
    ACTIONS(337), 1,
      aux_sym_text_token2,
    STATE(74), 1,
      aux_sym_text_repeat1,
    ACTIONS(307), 4,
      anon_sym_STAR,
      anon_sym_STAR_STAR,
      anon_sym___,
      anon_sym_BQUOTE,
  [1868] = 2,
    ACTIONS(340), 1,
      aux_sym_text_token1,
    ACTIONS(318), 6,
      anon_sym_STAR,
      anon_sym__,
      anon_sym_STAR_STAR,
      anon_sym___,
      anon_sym_BQUOTE,
      aux_sym_text_token2,
  [1880] = 2,
    ACTIONS(342), 1,
      aux_sym_text_token1,
    ACTIONS(326), 6,
      anon_sym_STAR,
      anon_sym__,
      anon_sym_STAR_STAR,
      anon_sym___,
      anon_sym_BQUOTE,
      aux_sym_text_token2,
  [1892] = 4,
    ACTIONS(344), 1,
      aux_sym_text_token1,
    ACTIONS(346), 1,
      aux_sym_text_token2,
    STATE(78), 1,
      aux_sym_text_repeat1,
    ACTIONS(303), 4,
      anon_sym__,
      anon_sym_STAR_STAR,
      anon_sym___,
      anon_sym_BQUOTE,
  [1908] = 4,
    ACTIONS(348), 1,
      aux_sym_text_token1,
    ACTIONS(351), 1,
      aux_sym_text_token2,
    STATE(78), 1,
      aux_sym_text_repeat1,
    ACTIONS(307), 4,
      anon_sym__,
      anon_sym_STAR_STAR,
      anon_sym___,
      anon_sym_BQUOTE,
  [1924] = 2,
    ACTIONS(342), 1,
      aux_sym_text_token1,
    ACTIONS(326), 5,
      anon_sym__,
      anon_sym_STAR_STAR,
      anon_sym___,
      anon_sym_BQUOTE,
      aux_sym_text_token2,
  [1935] = 2,
    ACTIONS(328), 1,
      aux_sym_text_token1,
    ACTIONS(312), 5,
      anon_sym_STAR,
      anon_sym_STAR_STAR,
      anon_sym___,
      anon_sym_BQUOTE,
      aux_sym_text_token2,
  [1946] = 2,
    ACTIONS(342), 1,
      aux_sym_text_token1,
    ACTIONS(326), 5,
      anon_sym_STAR,
      anon_sym_STAR_STAR,
      anon_sym___,
      anon_sym_BQUOTE,
      aux_sym_text_token2,
  [1957] = 2,
    ACTIONS(328), 1,
      aux_sym_text_token1,
    ACTIONS(312), 5,
      anon_sym__,
      anon_sym_STAR_STAR,
      anon_sym___,
      anon_sym_BQUOTE,
      aux_sym_text_token2,
  [1968] = 3,
    ACTIONS(354), 1,
      aux_sym_fenced_code_block_token1,
    ACTIONS(356), 1,
      aux_sym_fenced_code_block_token2,
    STATE(87), 1,
      aux_sym_fenced_code_block_repeat1,
  [1978] = 3,
    ACTIONS(358), 1,
      aux_sym_fenced_code_block_token1,
    ACTIONS(360), 1,
      aux_sym_fenced_code_block_token2,
    STATE(84), 1,
      aux_sym_fenced_code_block_repeat1,
  [1988] = 3,
    ACTIONS(356), 1,
      aux_sym_fenced_code_block_token2,
    ACTIONS(363), 1,
      aux_sym_fenced_code_block_token1,
    STATE(84), 1,
      aux_sym_fenced_code_block_repeat1,
  [1998] = 2,
    STATE(21), 1,
      sym_list_item,
    ACTIONS(365), 2,
      aux_sym_list_item_token1,
      aux_sym_list_item_token2,
  [2006] = 3,
    ACTIONS(356), 1,
      aux_sym_fenced_code_block_token2,
    ACTIONS(367), 1,
      aux_sym_fenced_code_block_token1,
    STATE(84), 1,
      aux_sym_fenced_code_block_repeat1,
  [2016] = 3,
    ACTIONS(356), 1,
      aux_sym_fenced_code_block_token2,
    ACTIONS(369), 1,
      aux_sym_fenced_code_block_token1,
    STATE(85), 1,
      aux_sym_fenced_code_block_repeat1,
  [2026] = 1,
    ACTIONS(110), 2,
      aux_sym_list_item_token1,
      aux_sym_list_item_token2,
  [2031] = 2,
    ACTIONS(371), 1,
      aux_sym_atx_heading_token2,
    ACTIONS(373), 1,
      sym_language,
  [2038] = 2,
    ACTIONS(375), 1,
      anon_sym_BQUOTE,
    ACTIONS(377), 1,
      aux_sym_code_span_token1,
  [2045] = 2,
    ACTIONS(379), 1,
      anon_sym_BQUOTE,
    ACTIONS(381), 1,
      aux_sym_code_span_token1,
  [2052] = 2,
    ACTIONS(383), 1,
      anon_sym_BQUOTE,
    ACTIONS(385), 1,
      aux_sym_code_span_token1,
  [2059] = 1,
    ACTIONS(358), 2,
      aux_sym_fenced_code_block_token1,
      aux_sym_fenced_code_block_token2,
  [2064] = 2,
    ACTIONS(387), 1,
      anon_sym_BQUOTE,
    ACTIONS(389), 1,
      aux_sym_code_span_token1,
  [2071] = 1,
    ACTIONS(391), 1,
      anon_sym_BQUOTE,
  [2075] = 1,
    ACTIONS(393), 1,
      aux_sym_atx_heading_token2,
  [2079] = 1,
    ACTIONS(395), 1,
      aux_sym_atx_heading_token2,
  [2083] = 1,
    ACTIONS(397), 1,
      aux_sym_atx_heading_token2,
  [2087] = 1,
    ACTIONS(399), 1,
      anon_sym_BQUOTE,
  [2091] = 1,
    ACTIONS(401), 1,
      aux_sym_atx_heading_token2,
  [2095] = 1,
    ACTIONS(403), 1,
      aux_sym_atx_heading_token2,
  [2099] = 1,
    ACTIONS(405), 1,
      anon_sym_BQUOTE,
  [2103] = 1,
    ACTIONS(407), 1,
      ts_builtin_sym_end,
  [2107] = 1,
    ACTIONS(409), 1,
      aux_sym_atx_heading_token2,
  [2111] = 1,
    ACTIONS(411), 1,
      aux_sym_atx_heading_token2,
  [2115] = 1,
    ACTIONS(413), 1,
      aux_sym_atx_heading_token2,
  [2119] = 1,
    ACTIONS(415), 1,
      aux_sym_atx_heading_token2,
  [2123] = 1,
    ACTIONS(417), 1,
      aux_sym_atx_heading_token2,
  [2127] = 1,
    ACTIONS(419), 1,
      anon_sym_BQUOTE,
  [2131] = 1,
    ACTIONS(421), 1,
      aux_sym_atx_heading_token2,
  [2135] = 1,
    ACTIONS(423), 1,
      aux_sym_atx_heading_token2,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(4)] = 0,
  [SMALL_STATE(5)] = 33,
  [SMALL_STATE(6)] = 66,
  [SMALL_STATE(7)] = 99,
  [SMALL_STATE(8)] = 127,
  [SMALL_STATE(9)] = 155,
  [SMALL_STATE(10)] = 181,
  [SMALL_STATE(11)] = 209,
  [SMALL_STATE(12)] = 231,
  [SMALL_STATE(13)] = 253,
  [SMALL_STATE(14)] = 275,
  [SMALL_STATE(15)] = 297,
  [SMALL_STATE(16)] = 319,
  [SMALL_STATE(17)] = 341,
  [SMALL_STATE(18)] = 363,
  [SMALL_STATE(19)] = 385,
  [SMALL_STATE(20)] = 407,
  [SMALL_STATE(21)] = 429,
  [SMALL_STATE(22)] = 451,
  [SMALL_STATE(23)] = 473,
  [SMALL_STATE(24)] = 495,
  [SMALL_STATE(25)] = 517,
  [SMALL_STATE(26)] = 554,
  [SMALL_STATE(27)] = 591,
  [SMALL_STATE(28)] = 628,
  [SMALL_STATE(29)] = 662,
  [SMALL_STATE(30)] = 696,
  [SMALL_STATE(31)] = 718,
  [SMALL_STATE(32)] = 740,
  [SMALL_STATE(33)] = 773,
  [SMALL_STATE(34)] = 806,
  [SMALL_STATE(35)] = 839,
  [SMALL_STATE(36)] = 872,
  [SMALL_STATE(37)] = 905,
  [SMALL_STATE(38)] = 938,
  [SMALL_STATE(39)] = 963,
  [SMALL_STATE(40)] = 988,
  [SMALL_STATE(41)] = 1013,
  [SMALL_STATE(42)] = 1038,
  [SMALL_STATE(43)] = 1061,
  [SMALL_STATE(44)] = 1084,
  [SMALL_STATE(45)] = 1117,
  [SMALL_STATE(46)] = 1150,
  [SMALL_STATE(47)] = 1183,
  [SMALL_STATE(48)] = 1216,
  [SMALL_STATE(49)] = 1249,
  [SMALL_STATE(50)] = 1282,
  [SMALL_STATE(51)] = 1315,
  [SMALL_STATE(52)] = 1348,
  [SMALL_STATE(53)] = 1381,
  [SMALL_STATE(54)] = 1414,
  [SMALL_STATE(55)] = 1447,
  [SMALL_STATE(56)] = 1476,
  [SMALL_STATE(57)] = 1505,
  [SMALL_STATE(58)] = 1534,
  [SMALL_STATE(59)] = 1563,
  [SMALL_STATE(60)] = 1592,
  [SMALL_STATE(61)] = 1621,
  [SMALL_STATE(62)] = 1647,
  [SMALL_STATE(63)] = 1673,
  [SMALL_STATE(64)] = 1699,
  [SMALL_STATE(65)] = 1725,
  [SMALL_STATE(66)] = 1741,
  [SMALL_STATE(67)] = 1757,
  [SMALL_STATE(68)] = 1768,
  [SMALL_STATE(69)] = 1785,
  [SMALL_STATE(70)] = 1796,
  [SMALL_STATE(71)] = 1813,
  [SMALL_STATE(72)] = 1824,
  [SMALL_STATE(73)] = 1836,
  [SMALL_STATE(74)] = 1852,
  [SMALL_STATE(75)] = 1868,
  [SMALL_STATE(76)] = 1880,
  [SMALL_STATE(77)] = 1892,
  [SMALL_STATE(78)] = 1908,
  [SMALL_STATE(79)] = 1924,
  [SMALL_STATE(80)] = 1935,
  [SMALL_STATE(81)] = 1946,
  [SMALL_STATE(82)] = 1957,
  [SMALL_STATE(83)] = 1968,
  [SMALL_STATE(84)] = 1978,
  [SMALL_STATE(85)] = 1988,
  [SMALL_STATE(86)] = 1998,
  [SMALL_STATE(87)] = 2006,
  [SMALL_STATE(88)] = 2016,
  [SMALL_STATE(89)] = 2026,
  [SMALL_STATE(90)] = 2031,
  [SMALL_STATE(91)] = 2038,
  [SMALL_STATE(92)] = 2045,
  [SMALL_STATE(93)] = 2052,
  [SMALL_STATE(94)] = 2059,
  [SMALL_STATE(95)] = 2064,
  [SMALL_STATE(96)] = 2071,
  [SMALL_STATE(97)] = 2075,
  [SMALL_STATE(98)] = 2079,
  [SMALL_STATE(99)] = 2083,
  [SMALL_STATE(100)] = 2087,
  [SMALL_STATE(101)] = 2091,
  [SMALL_STATE(102)] = 2095,
  [SMALL_STATE(103)] = 2099,
  [SMALL_STATE(104)] = 2103,
  [SMALL_STATE(105)] = 2107,
  [SMALL_STATE(106)] = 2111,
  [SMALL_STATE(107)] = 2115,
  [SMALL_STATE(108)] = 2119,
  [SMALL_STATE(109)] = 2123,
  [SMALL_STATE(110)] = 2127,
  [SMALL_STATE(111)] = 2131,
  [SMALL_STATE(112)] = 2135,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_document, 0, 0, 0),
  [5] = {.entry = {.count = 1, .reusable = false}}, SHIFT(27),
  [7] = {.entry = {.count = 1, .reusable = false}}, SHIFT(11),
  [9] = {.entry = {.count = 1, .reusable = false}}, SHIFT(25),
  [11] = {.entry = {.count = 1, .reusable = false}}, SHIFT(61),
  [13] = {.entry = {.count = 1, .reusable = false}}, SHIFT(63),
  [15] = {.entry = {.count = 1, .reusable = false}}, SHIFT(34),
  [17] = {.entry = {.count = 1, .reusable = false}}, SHIFT(35),
  [19] = {.entry = {.count = 1, .reusable = false}}, SHIFT(91),
  [21] = {.entry = {.count = 1, .reusable = false}}, SHIFT(65),
  [23] = {.entry = {.count = 1, .reusable = false}}, SHIFT(90),
  [25] = {.entry = {.count = 1, .reusable = false}}, SHIFT(26),
  [27] = {.entry = {.count = 1, .reusable = false}}, SHIFT(98),
  [29] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_document, 1, 0, 0),
  [31] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0),
  [33] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(27),
  [36] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(11),
  [39] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(25),
  [42] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(61),
  [45] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(63),
  [48] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(34),
  [51] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(35),
  [54] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(91),
  [57] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(65),
  [60] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(90),
  [63] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(26),
  [66] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(98),
  [69] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_list, 1, 0, 0),
  [71] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_list, 1, 0, 0),
  [73] = {.entry = {.count = 1, .reusable = false}}, SHIFT(89),
  [75] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_list, 2, 0, 0),
  [77] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_list, 2, 0, 0),
  [79] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_list_repeat1, 2, 0, 0),
  [81] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_list_repeat1, 2, 0, 0),
  [83] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_list_repeat1, 2, 0, 0), SHIFT_REPEAT(89),
  [86] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_list_repeat1, 2, 0, 0), SHIFT_REPEAT(26),
  [89] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block_quote, 1, 0, 0),
  [91] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_block_quote, 1, 0, 0),
  [93] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block_quote, 2, 0, 0),
  [95] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_block_quote, 2, 0, 0),
  [97] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_paragraph, 2, 0, 2),
  [99] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_paragraph, 2, 0, 2),
  [101] = {.entry = {.count = 1, .reusable = false}}, SHIFT(97),
  [103] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_block_quote_repeat1, 2, 0, 0),
  [105] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_block_quote_repeat1, 2, 0, 0),
  [107] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_block_quote_repeat1, 2, 0, 0), SHIFT_REPEAT(25),
  [110] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_blank_line, 1, 0, 0),
  [112] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_blank_line, 1, 0, 0),
  [114] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_list_item, 2, 0, 1),
  [116] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_list_item, 2, 0, 1),
  [118] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block_quote_line, 2, 0, 1),
  [120] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_block_quote_line, 2, 0, 1),
  [122] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_atx_heading, 2, 0, 1),
  [124] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_atx_heading, 2, 0, 1),
  [126] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_thematic_break, 2, 0, 0),
  [128] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_thematic_break, 2, 0, 0),
  [130] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_fenced_code_block, 4, 0, 5),
  [132] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_fenced_code_block, 4, 0, 5),
  [134] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_list_item, 3, 0, 3),
  [136] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_list_item, 3, 0, 3),
  [138] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_setext_heading, 4, 0, 6),
  [140] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_setext_heading, 4, 0, 6),
  [142] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_fenced_code_block, 5, 0, 7),
  [144] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_fenced_code_block, 5, 0, 7),
  [146] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block_quote_line, 3, 0, 3),
  [148] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_block_quote_line, 3, 0, 3),
  [150] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_atx_heading, 3, 0, 3),
  [152] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_atx_heading, 3, 0, 3),
  [154] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_fenced_code_block, 5, 0, 8),
  [156] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_fenced_code_block, 5, 0, 8),
  [158] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_fenced_code_block, 6, 0, 9),
  [160] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_fenced_code_block, 6, 0, 9),
  [162] = {.entry = {.count = 1, .reusable = false}}, SHIFT(13),
  [164] = {.entry = {.count = 1, .reusable = false}}, SHIFT(12),
  [166] = {.entry = {.count = 1, .reusable = false}}, SHIFT(14),
  [168] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_inline, 1, 0, 0),
  [170] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_inline_repeat1, 2, 0, 0),
  [172] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_inline_repeat1, 2, 0, 0), SHIFT_REPEAT(61),
  [175] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_inline_repeat1, 2, 0, 0), SHIFT_REPEAT(63),
  [178] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_inline_repeat1, 2, 0, 0), SHIFT_REPEAT(34),
  [181] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_inline_repeat1, 2, 0, 0), SHIFT_REPEAT(35),
  [184] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_inline_repeat1, 2, 0, 0), SHIFT_REPEAT(91),
  [187] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_inline_repeat1, 2, 0, 0), SHIFT_REPEAT(65),
  [190] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_strong_emphasis, 3, 0, 0),
  [192] = {.entry = {.count = 1, .reusable = false}}, SHIFT(64),
  [194] = {.entry = {.count = 1, .reusable = false}}, SHIFT(62),
  [196] = {.entry = {.count = 1, .reusable = false}}, SHIFT(40),
  [198] = {.entry = {.count = 1, .reusable = false}}, SHIFT(33),
  [200] = {.entry = {.count = 1, .reusable = false}}, SHIFT(93),
  [202] = {.entry = {.count = 1, .reusable = true}}, SHIFT(68),
  [204] = {.entry = {.count = 1, .reusable = false}}, SHIFT(68),
  [206] = {.entry = {.count = 1, .reusable = false}}, SHIFT(53),
  [208] = {.entry = {.count = 1, .reusable = false}}, SHIFT(30),
  [210] = {.entry = {.count = 1, .reusable = false}}, SHIFT(31),
  [212] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_strong_emphasis, 3, 0, 0),
  [214] = {.entry = {.count = 1, .reusable = false}}, SHIFT(38),
  [216] = {.entry = {.count = 1, .reusable = false}}, SHIFT(39),
  [218] = {.entry = {.count = 1, .reusable = false}}, SHIFT(41),
  [220] = {.entry = {.count = 1, .reusable = false}}, SHIFT(42),
  [222] = {.entry = {.count = 1, .reusable = false}}, SHIFT(43),
  [224] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_inline_repeat1, 2, 0, 0), SHIFT_REPEAT(64),
  [227] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_inline_repeat1, 2, 0, 0), SHIFT_REPEAT(62),
  [230] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_inline_repeat1, 2, 0, 0), SHIFT_REPEAT(53),
  [233] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_inline_repeat1, 2, 0, 0), SHIFT_REPEAT(33),
  [236] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_inline_repeat1, 2, 0, 0), SHIFT_REPEAT(93),
  [239] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_inline_repeat1, 2, 0, 0), SHIFT_REPEAT(68),
  [242] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_inline_repeat1, 2, 0, 0), SHIFT_REPEAT(68),
  [245] = {.entry = {.count = 1, .reusable = false}}, SHIFT(69),
  [247] = {.entry = {.count = 1, .reusable = false}}, SHIFT(51),
  [249] = {.entry = {.count = 1, .reusable = false}}, SHIFT(52),
  [251] = {.entry = {.count = 1, .reusable = false}}, SHIFT(95),
  [253] = {.entry = {.count = 1, .reusable = true}}, SHIFT(77),
  [255] = {.entry = {.count = 1, .reusable = false}}, SHIFT(77),
  [257] = {.entry = {.count = 1, .reusable = false}}, SHIFT(75),
  [259] = {.entry = {.count = 1, .reusable = false}}, SHIFT(49),
  [261] = {.entry = {.count = 1, .reusable = false}}, SHIFT(50),
  [263] = {.entry = {.count = 1, .reusable = false}}, SHIFT(92),
  [265] = {.entry = {.count = 1, .reusable = true}}, SHIFT(73),
  [267] = {.entry = {.count = 1, .reusable = false}}, SHIFT(73),
  [269] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_emphasis_repeat1, 2, 0, 0),
  [271] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_emphasis_repeat1, 2, 0, 0), SHIFT_REPEAT(49),
  [274] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_emphasis_repeat1, 2, 0, 0), SHIFT_REPEAT(50),
  [277] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_emphasis_repeat1, 2, 0, 0), SHIFT_REPEAT(92),
  [280] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_emphasis_repeat1, 2, 0, 0), SHIFT_REPEAT(73),
  [283] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_emphasis_repeat1, 2, 0, 0), SHIFT_REPEAT(73),
  [286] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_emphasis_repeat2, 2, 0, 0),
  [288] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_emphasis_repeat2, 2, 0, 0), SHIFT_REPEAT(51),
  [291] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_emphasis_repeat2, 2, 0, 0), SHIFT_REPEAT(52),
  [294] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_emphasis_repeat2, 2, 0, 0), SHIFT_REPEAT(95),
  [297] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_emphasis_repeat2, 2, 0, 0), SHIFT_REPEAT(77),
  [300] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_emphasis_repeat2, 2, 0, 0), SHIFT_REPEAT(77),
  [303] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_text, 1, 0, 0),
  [305] = {.entry = {.count = 1, .reusable = false}}, SHIFT(66),
  [307] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_text_repeat1, 2, 0, 0),
  [309] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_text_repeat1, 2, 0, 0), SHIFT_REPEAT(66),
  [312] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_code_span, 2, 0, 0),
  [314] = {.entry = {.count = 1, .reusable = true}}, SHIFT(70),
  [316] = {.entry = {.count = 1, .reusable = false}}, SHIFT(70),
  [318] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_emphasis, 3, 0, 0),
  [320] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_text_repeat1, 2, 0, 0), SHIFT_REPEAT(70),
  [323] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_text_repeat1, 2, 0, 0), SHIFT_REPEAT(70),
  [326] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_code_span, 3, 0, 4),
  [328] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_code_span, 2, 0, 0),
  [330] = {.entry = {.count = 1, .reusable = true}}, SHIFT(74),
  [332] = {.entry = {.count = 1, .reusable = false}}, SHIFT(74),
  [334] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_text_repeat1, 2, 0, 0), SHIFT_REPEAT(74),
  [337] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_text_repeat1, 2, 0, 0), SHIFT_REPEAT(74),
  [340] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_emphasis, 3, 0, 0),
  [342] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_code_span, 3, 0, 4),
  [344] = {.entry = {.count = 1, .reusable = true}}, SHIFT(78),
  [346] = {.entry = {.count = 1, .reusable = false}}, SHIFT(78),
  [348] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_text_repeat1, 2, 0, 0), SHIFT_REPEAT(78),
  [351] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_text_repeat1, 2, 0, 0), SHIFT_REPEAT(78),
  [354] = {.entry = {.count = 1, .reusable = false}}, SHIFT(107),
  [356] = {.entry = {.count = 1, .reusable = false}}, SHIFT(108),
  [358] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_fenced_code_block_repeat1, 2, 0, 0),
  [360] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_fenced_code_block_repeat1, 2, 0, 0), SHIFT_REPEAT(108),
  [363] = {.entry = {.count = 1, .reusable = false}}, SHIFT(109),
  [365] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [367] = {.entry = {.count = 1, .reusable = false}}, SHIFT(105),
  [369] = {.entry = {.count = 1, .reusable = false}}, SHIFT(102),
  [371] = {.entry = {.count = 1, .reusable = false}}, SHIFT(83),
  [373] = {.entry = {.count = 1, .reusable = false}}, SHIFT(112),
  [375] = {.entry = {.count = 1, .reusable = false}}, SHIFT(67),
  [377] = {.entry = {.count = 1, .reusable = true}}, SHIFT(103),
  [379] = {.entry = {.count = 1, .reusable = false}}, SHIFT(80),
  [381] = {.entry = {.count = 1, .reusable = true}}, SHIFT(110),
  [383] = {.entry = {.count = 1, .reusable = false}}, SHIFT(72),
  [385] = {.entry = {.count = 1, .reusable = true}}, SHIFT(96),
  [387] = {.entry = {.count = 1, .reusable = false}}, SHIFT(82),
  [389] = {.entry = {.count = 1, .reusable = true}}, SHIFT(100),
  [391] = {.entry = {.count = 1, .reusable = true}}, SHIFT(76),
  [393] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [395] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [397] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [399] = {.entry = {.count = 1, .reusable = true}}, SHIFT(79),
  [401] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [403] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [405] = {.entry = {.count = 1, .reusable = true}}, SHIFT(71),
  [407] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [409] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [411] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [413] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [415] = {.entry = {.count = 1, .reusable = true}}, SHIFT(94),
  [417] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [419] = {.entry = {.count = 1, .reusable = true}}, SHIFT(81),
  [421] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [423] = {.entry = {.count = 1, .reusable = true}}, SHIFT(88),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_pandoc_markdown(void) {
  static const TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
